### ISSUE TITLE
如何自定义层 custom layer

### ISSUE THREAD

**Issue by Dynmi** [MegEngine/MegEngine#101]
## 背景
我想使用megengine按照需要定制一个RNN层

## 任务描述
使用megengine自定义一个层

## 目标
使用megengine实现一个自定义层

**Comment by lixiangyin666** [comment]
自定义一个层也就是自定义一个Module，可以继承megengine.module中的Module，然后实现自己的__init__和forward就可以了.可以参考https://megengine.org.cn/doc/basic/network_build.html 中基于Module搭建网络部分的文档来搭建自己的Module(层)
另外可以参考Pytorch的RNN搭建方式来实现MegEngine的RNN层，[Pytorch RNN module](https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html#creating-the-network)

**Comment by 21miracle** [comment]
能不能不要发了！！！？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Chai&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月5日(星期四) 下午5:58
收件人:&nbsp;&quot;MegEngine/MegEngine&quot;<MegEngine@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [MegEngine/MegEngine] 如何自定义层 custom layer (#101)

**Comment by MegChai** [comment]
> 能不能不要发了！！！？------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;Chai&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月5日(星期四) 下午5:58 收件人:&nbsp;&quot;MegEngine/MegEngine&quot;<MegEngine@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [MegEngine/MegEngine] 如何自定义层 custom layer (#101)

在 GitHub 中取消 Watching 某存储库即可停止收到相关邮件。
