### ISSUE TITLE
默认使用 uuid 作为随机种子生成器

### ISSUE THREAD

**Issue by Leymore** [MegEngine/MegEngine#104]
使用 uuid 作为随机种子生成器

## 背景
在多机训练的过程中，对于模型并行非共享部分的参数，我希望它们默认为不同的初始化值。

## 需求描述
具体地，我希望以下代码中设置 random_seed 的部分，使用 uuid.uuid4().int，而不是原本的实现。

https://github.com/MegEngine/MegEngine/blob/f91881ffdc051ab49314b1bd12c4a07a862dc9c6/python_module/megengine/random/rng.py#L20

在原本的实现中，相邻编号的两个 worker 有极高的可能相差 1s 启动，此时它们的 random_seed 就是相同的，所初始化的参数也是相同的。我认为这在许多情况下会导致恶性 bug 且难以 debug

**Comment by a419775258** [comment]
感谢，后面我们会考略改进的
