### ISSUE TITLE
训练时间超长

### ISSUE THREAD

**Issue by heiheihei-ops** [MegEngine/MegEngine#105]
![image](https://user-images.githubusercontent.com/66516707/92693051-a39f3800-f377-11ea-9323-df9b8bcf9fc5.png)
![image](https://user-images.githubusercontent.com/66516707/92693317-0db7dd00-f378-11ea-9b08-e5f1c1e58869.png)
在gpu下一个epoch要五个小时是认真的吗！我是什么姿势不对。。。

**Comment by a419775258** [comment]
模型里可能有什么opr跑里navie的实现了

**Comment by heiheihei-ops** [comment]
请问一下跑了navie的实现具体是指什么呢？

**Comment by a419775258** [comment]
要看看你模型里的opr会计算哪种尺寸的输入，如果没有优化过的算法，那就有可能通过最朴素的实现计算。

**Comment by heiheihei-ops** [comment]
再朴素也不能五个小时吧 况且我在本地用pytorch实现的同一个网络根本不会这么长时间

**Comment by heiheihei-ops** [comment]
![image](https://user-images.githubusercontent.com/66516707/92708962-1d8bed00-f389-11ea-9512-012b76caee11.png)
不过训练的时候cpu爆满了好像，是不是因为cpu的原因

**Comment by a419775258** [comment]
用set_log_level把log的级别设置到debug看看每个opr到底跑了什么算法吧，应该很快就可以定位到问题。
