### ISSUE TITLE
LocalConv2d无法使用

### ISSUE THREAD

**Issue by Zheng222** [MegEngine/MegEngine#112]
## 环境
1.系统环境：Ubuntu 16.04, TITAN X(Pascal), CUDA 10.1
2.MegEngine版本：0.6
3.python版本：3.6

## 请提供关键的代码片段便于追查问题

```
import megengine.module as M
from megengine import tensor
import numpy as np
inp = tensor(np.zeros((1, 3, 100, 100)), dtype=np.float32)
local = M.LocalConv2d(3, 3, 100, 100, 3, padding=1)
local(inp)
```

## 请提供完整的日志及报错信息
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/hz/.virtualenvs/mge_0.6/lib/python3.6/site-packages/megengine/module/module.py", line 71, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hz/.virtualenvs/mge_0.6/lib/python3.6/site-packages/megengine/module/conv.py", line 380, in forward
    inp, self.weight, self.stride, self.padding, self.dilation, self.conv_mode
  File "/home/hz/.virtualenvs/mge_0.6/lib/python3.6/site-packages/megengine/core/tensor.py", line 42, in wrapper
    ret = func(*new_args, **new_kwargs)
  File "/home/hz/.virtualenvs/mge_0.6/lib/python3.6/site-packages/megengine/functional/nn.py", line 202, in local_conv2d
    mode=conv_mode,
  File "/home/hz/.virtualenvs/mge_0.6/lib/python3.6/site-packages/megengine/_internal/opr.py", line 826, in group_local
    outputs = _mgb._create_opr("GroupLocalV1", all_inputs, all_params, config)
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::MegDNNError
No usable kernel for local conv, src: {1(30000),3(10000),100(100),100(1)} filter: {100(8100),100(81),3(27),3(9),3(3),3(1)} 
+ bt:/home/hz/.virtualenvs/mge_0.6/lib/python3.6/site-packages/megengine/_internal/_mgb.cpython-36m-x86_64-linux-gnu.so{1dee859,1e870b1,2170084,2de2d9a}
| Associated operator: id=4 name=glocal(shared[0])[4] type=mgb::opr::GroupLocalForward
|   input variables: 
|     0: {id:1, layout:{1(30000),3(10000),100(100),100(1)}, Float32, owner:shared[0]{VolatileSharedDeviceTensor}, name:shared[0], slot:0, gpu0:0, s, 4, 1}
|     1: {id:3, layout:{1(810000),100(8100),100(81),3(27),3(9),3(3),3(1)}, Float32, owner:shared[2]{VolatileSharedDeviceTensor}, name:shared[2], slot:0, gpu0:0, s, 4, 1}
|   output variables: 
|     0: {id:5, layout:{1(30000),3(10000),100(100),100(1)}, Float32, owner:glocal(shared[0])[4]{GroupLocalForward}, name:glocal(shared[0])[4], slot:0, gpu0:0, d, 4, 1}
|     1: {id:6, layout:{0(1)}, Byte, owner:glocal(shared[0])[4]{GroupLocalForward}, name:glocal(shared[0])[4]:workspace, slot:1, gpu0:0, d, 4, 1}

**Comment by chenqy4933** [comment]
感谢你的问题，这个bug是已知问题，正在修复。

**Comment by wllvcxz** [comment]
这个问题将在十月份发布的v1.0.0版本中修复

**Comment by MegChai** [comment]
这个问题已经修复，请更新到 megengine v1.0.0 正式版
