### ISSUE TITLE
studio上的那个自动生成的.ipynb_checkpoints太烦人了，求让它不自动生成

### ISSUE THREAD

**Issue by fenghansen** [MegEngine/MegEngine#113]
有的时候程序跑着跑着突然就暴毙了，尤其是在输出测试集的时候，那个自动生成的

## 背景
视频超分比赛，输出测试集的时候，那个自动生成的.ipynb_checkpoints经常导致程序暴毙，耽误训练计划，浪费算力时间。
rm -rf每次输入的指令都比较长，而且要删好几个文件夹，所以希望能够有个一劳永逸的解决方案。

## 需求描述
我看有个issue提到了个人用JupyterNotebook解决这个问题的方法，在https://github.com/jupyterlab/jupyterlab/issues/5809。如果我没理解错的话，好像是要在jupyter启动的时候添加这条命令，studio里的jupyter是自动启动的，所以可以麻烦贵司尝试解决一下这个麻烦的东西么，感激不尽！

**Comment by ChaiMind** [comment]
你可以尝试一下在单元格（Cell）中暂时性地关闭自动保存功能：

```
%autosave 0
```

在 Jupyter Lab 中这个已经变成了一个可视化的选项 https://github.com/jupyterlab/jupyterlab/pull/3734

**Comment by fenghansen** [comment]
十分感谢！
