### ISSUE TITLE
目前是否还没有单独的pad算子？

### ISSUE THREAD

**Issue by zhen8838** [MegEngine/MegEngine#114]
## 请简要描述您的需求
`1.0rc`版本，我想单独使用Pad，不过找了下文档，看了下源码里的算子，好像没有单独的Pad算子？

**Comment by haolongzhangm** [comment]
能简单描述一下单独使用pad的场景吗

**Comment by zhen8838** [comment]
想要像`torch`里的`ReflectionPad2d`。

顺便再问一下，在`megengine`里加载`pytorch`网络，可以对其进行训练的吗，还是只能拿来推理？

**Comment by fzhangscorec** [comment]
目前没有torch里的ReflectionPad2d算子，可以使用tensor的advanced indexing 和functional中的concat dimshuffle等价的实现一个ReflectionPad2d。 megengine 1.0rc 暂时不支持加载pytorch网络

**Comment by zhen8838** [comment]
@fzhangscorec 谢谢你，我研究研究。

**Comment by ChaiMind** [comment]
@xxr3376 这个需求非常值得考虑

**Comment by xxr3376** [comment]
@zhen8838 目前已经有了 https://megengine.org.cn/doc/stable/en/reference/api/megengine.functional.nn.pad.html?highlight=pad#megengine.functional.nn.pad
