### ISSUE TITLE
天元初步调试实践反馈

### ISSUE THREAD

**Issue by HMAJG** [MegEngine/MegEngine#117]
## 文档链接

	
	(1)安装说明对环境说明不明确
			
	(2)基础学习部分存在编程习惯问题
		
	(3)cuda调用状态和使用状态检测方法问题
		
## 问题描述
安装说明对环境说明不明确
		官方文档中说明支持多种硬件平台（ARM、CPU、GPU）源码中确实支持但是对新手配置没有选择性体验不好，容易让人迷糊
		
	基础学习部分存在编程习惯问题
		代码编写中从基础学习11行可以看出确实比较方便，但是在基于model搭建教程中首先存在一个没全部导入库函数问题，这个个人理解为编程习惯
		对于新手来说如果py普通基础情况下容易迷惑，这个个人估计是案例在自己环境中实验，没考虑到新手在一个新环境下配置。
	cuda调用状态和使用状态检测方法问题
		在没cuda的windows环境下官方给出的lenet例子中出现了cuda的number设置错误，初步猜想没有对cuda调用写try和expect

**Comment by ChaiMind** [comment]
谢谢反馈，能否针对这三条内容提供更加具体的描述？

- 对一些能给出链接的地方，尽量给出链接。
- 如果可以，提供你预期的形式。

**Comment by HMAJG** [comment]
## 安装说明

**注意:** MegEngine 现在仅支持 Linux 平台安装，以及 Python3.5 及以上的版本（不支持 Python2 ）。对于 Windows 10 用户，可以通过安装 [WSL(Windows Subsystem for Linux)](https://docs.microsoft.com/en-us/windows/wsl) 进行体验。

*****************************************************************************************************************
在这里 希望可以选择不同的系统环境 windows10、ubuntu、centos、freeRTOS
                                               python环境：3.x  
                                                CUDA版本：
                                                cudnn版本：
                                                快速构建的 shell方法

*****************************************************************************************************************

**Comment by HMAJG** [comment]
> 谢谢反馈，能否针对这三条内容提供更加具体的描述？
> 
> * 对一些能给出链接的地方，尽量给出链接。
> * 如果可以，提供你预期的形式。

好的  ，我会持续关注    拜读     分析    客观做出真切的设计观点。

**Comment by ChaiMind** [comment]
> ## 安装说明
> **注意:** MegEngine 现在仅支持 Linux 平台安装，以及 Python3.5 及以上的版本（不支持 Python2 ）。对于 Windows 10 用户，可以通过安装 [WSL(Windows Subsystem for Linux)](https://docs.microsoft.com/en-us/windows/wsl) 进行体验。
> 
> 在这里 希望可以选择不同的系统环境 windows10、ubuntu、centos、freeRTOS
> python环境：3.x
> CUDA版本：
> cudnn版本：
> 快速构建的 shell方法

---

因为提供了统一的基于 pip 的安装方法，对不同的系统环境和 Python 环境都进行了打包，所以命令行是完全一致的。
CUDA 和 cudnn 版本只对 Build from Source 的需求有一定的影响，不会影响到天元 MegEngine 的 pip 安装。
Build from Source 是一门精细活，所以一般不会为初学者提供一键脚本，最好有大型项目的编译经验再进行尝试。

**Comment by ChaiMind** [comment]
> 基础学习部分存在编程习惯问题
>	代码编写中从基础学习11行可以看出确实比较方便，但是在基于model搭建教程中首先存在一个没全部导入库函数问题，这个个人理解为编程习惯
> 对于新手来说如果py普通基础情况下容易迷惑，这个个人估计是案例在自己环境中实验，没考虑到新手在一个新环境下配置。

这个是因为 [网络搭建](https://megengine.org.cn/doc/basic/network_build.html) 部分的文档默认用户是顺序执行里面的代码的，如果你是部分性质的阅读，会出现没有 impoirt 相应包的需求，后续可以考虑提供相应的 jupyter notebook 文件。

**Comment by ChaiMind** [comment]
> 在没cuda的windows环境下官方给出的lenet例子中出现了cuda的number设置错误，初步猜想没有对cuda调用写try和expect

这个需要你另外开一个 Issue，提供复现的环境配置和相应的代码。

**Comment by ChaiMind** [comment]
应用户要求，该 Issue 转至论坛进行讨论。

**Comment by HMAJG** [comment]
## 安装说明

**注意:** MegEngine 现在仅支持 Linux 平台安装， Python3.5 及以上的版本（不支持 Python2 ）。对于 Windows 10 用户，可以通过powershell、WSL、anaconda  prompt进行pip和conda方式安装


******************************************************************************************************************************
安装方法一：pip    xxxxxx
                温馨提示：如果出现错误请修改pip源或者升级最高版本pip并且核对操作系统和python版本是否支持

安装方法二：conda  xxxxxx
                温馨提示：(1)直接环境下配置xxxxxx；  (2)虚拟环境下配置xxxxxx

安装方法三：docker 

                温馨提示：
安装方法四：源码编译   
                温馨提示： 系统环境，cmake版本xxxx， gcc版本xxxxx

*****************************************************************************************************************************
