### ISSUE TITLE
RuntimeError: not recording

### ISSUE THREAD

**Issue by AndrewNoah** [MegEngine/MegEngine#119]
## 文档链接

https://megengine.org.cn/doc/basic/basic_concepts.html

## 问题描述

```python3
gm1 = GradManager().attach([w,b])
gm1.record()

p = F.matmul(x,w)
y = p+b

gm1.backward(y)
gm1.release()
```
以上代码计算求导出现问题
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-86ee9da2c5e9> in <module>
      6 
      7 gm1.backward(y)
----> 8 gm1.release()

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/autodiff/grad_manager.py in release(self)
    160         """
    161         if not self._recording:
--> 162             raise RuntimeError("not recording")
    163         self._stop_record()
    164 

RuntimeError: not recording
```

**Comment by xxr3376** [comment]
在已经调用 `gm1.backward(y)` 后，gm1 已经不处于 recording 状态，无需再 release。即 GradManager 要么以 `.backward()` 结尾，要么以 `.release()` 结尾。

建议参考[文档](https://megengine.org.cn/doc/basic/train_and_evaluation.html#train-and-evaluation)使用 `with gm1:` 的语法，来避免这类情况的发生。

**Comment by AndrewNoah** [comment]
> ~在已经调用 `gm1.backward(y)` 后，gm1 已经不处于 recording 状态，无需再 release。即 GradManager 要么以 `.backward()` 结尾，要么以 `.release()` 结尾。~ 应该是这里代码实现的行为错了，你的用法本身应该没问题，我们修复一下。
> 
> 另外现在建议参考[文档](https://megengine.org.cn/doc/basic/train_and_evaluation.html#train-and-evaluation)使用 `with gm1:` 的语法，来避免这类情况的发生。

好的
