### ISSUE TITLE
对于Tensor Core指令的支持

### ISSUE THREAD

**Issue by Anjiang-Wei** [MegEngine/MegEngine#128]
请问目前MegEngine对于Tensor Core指令支持到何种程度？比如针对Conv2d, Conv3d, GEMM算子，以及对应的各种type(fp16, bf16, tf32, int8, bool)的支持如何呢？

**Comment by MegChai** [comment]
MegEngine 目前只开源了 conv int8 的 Tensor Core 支持，其他的靠官方的 CuDNN 和 TensorRT 库支持。

（欢迎一起来贡献代码呀～～）

**Comment by MegChai** [comment]
由于这个 Issue 长时间没有得到答复，我们决定先关闭它。如果有任何后续信息或新的疑问，欢迎重新打开～

**Comment by twmht** [comment]
@ChaiByte 

目前有支援 fp16 的 tensorcore 嗎?
