### ISSUE TITLE
是否刷星

### ISSUE THREAD

**Issue by KeyoungLau** [MegEngine/MegEngine#130]
https://linux.cn/article-12950-1.html
新闻报道这个软件刷星？

**Comment by megvii-mge** [comment]
Keyoung 您好，不好意思这么晚才来回复。如果这是一个平常的 Issue，社区成员通常会在 24 小时内收到来自研发团队成员的答复。但您所说的刷 Star 行为，对我们而言实在“事发突然”，所以需要经过调查确认后才能给出答复。

对于在 GitHub 上刷 Star这一行为，我们的一贯态度是：**不接受、不参与。**

经过沟通确认，我们发现，9月份，我们与第三方平台进行了天元 MegEngine 线上推广合作，而后第三方平台在未经我们许可的情况下进行了不当推广行为，我们发现后第一时间要求推广平台下线了该活动。在与第三方平台合作的过程中，我们的管理和监督不到位，导致了不当推广的出现。**我们对此深感愧疚，也在此向所有关注天元 MegEngine 的开发者们致歉。**

作为开源项目，Star 量是常见的衡量指标。我们自然希望自家的框架能够获得一定的关注度，平时也会在用户交流群中半开玩笑似的说：“求各位给天元点个 Star 吧。” 但我们内心更希望的是：**能有更多用户开始使用天元MegEngine 框架并且受益于它；整个社区能够收获更多的忠实用户与开发者，通过开源能够让这款深度学习框架走得更远。**

我们对刷 Star 行为的态度始终一致：不接受、不参与。此次事件也让我们意识到，团队成员需要向成熟开源社区进行学习。我们将花更多的时间与社区进行交流互动，为实现“深度学习、简单开发”的目标而努力。

最后感谢您的质询，欢迎您继续关注、监督天元 MegEngine 社区的发展。

天元 MegEngine 开源团队

**Comment by cnbattle** [comment]
![](https://starchart.cc/MegEngine/MegEngine.svg)

**Comment by MegChai** [comment]
@cnbattle 你好，我们从 9 月开始为了推广天元 MegEngine 框架，还举办了如下活动：

- [零基础入门旷视天元MegEngine系列课程（全6节）](https://www.bilibili.com/video/BV1Zf4y1Q7aZ) 
- [旷视超分辨率开源大赛 - 比赛经验分享](https://www.bilibili.com/video/BV1Mi4y177nf)
- [CV Master训练营-检测专题（共3课时）](https://www.bilibili.com/video/BV1Xp4y1r7WV)
- [CV Master训练营-识别专题（共4课时）](https://www.bilibili.com/video/BV1Cz4y1y7k1)
- [【旷视天元精品课程】现代实用化深度视觉模型](https://www.bilibili.com/video/BV11y4y1m7BP)

每项活动都对天元 MegEngine Star 量的上涨起到了推广宣传的作用，耗费了大量人力物力，还请客观看待。

**Comment by bigeagle** [comment]
@MegChai 您说这话是什么意思呢？因为做了很多事情所以就不存在刷星行为了吗？

**Comment by MegChai** [comment]
> @MegChai 您说这话是什么意思呢？因为做了很多事情所以就不存在刷星行为了吗？

上图记录了 MegEngine Star 量的变化趋势，可以看出，从 2020 年 9 月开始较之前平滑的曲线有明显上升趋势。

如果基于刷 Star 事情这样的背景下，直接在这个 Issue 里抛出这样一张图片，容易给不知道整体情况的人造成误读，会让人认为 9 - 12 月的 Star 上涨完全上由于刷 Star 这种不正常推广活动造成的。我只是补充了更多的信息而已，并没有否认由于团队自身的过失导致了不正常推广行为的产生。

我认为你过分解读了上面的信息补充。
