### ISSUE TITLE
Megengine Cannot Split the Tensor

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#133]
## 环境
1.系统环境：Windows 10 专业版 64-bit
2.MegEngine版本：1.1.0
3.python版本：3.7.9

## 复现步骤
1.创建Tensor x
2.组卷积处理Tensor x，得到结果y
3.使用megengine.functional.split 对y进行通道切分

## 请提供关键的代码片段便于追查问题
import megengine as mge
import megengine.module as M
import megengine.functional as F
import numpy as np
numpy_x = np.random.random((1, 64, 64, 64))
x = mge.tensor(numpy_x, dtype=np.float32)
y = M.Conv2d(64, 64*2, 3, 1, padding=1, groups=2*2, dilation=1)(x)
bs, rchannels = y.shape[:2]
splited = np.split(y.detach().numpy(), rchannels // 2, axis=1)
print(len(splited))
print(splited[0].shape)
splited = F.split(y, rchannels // 2, axis=1)

## 请提供完整的日志及报错信息
Traceback (most recent call last):
  File "d:/workspace/lab/MegVision/models/classification/utils.py", line 236, in <module>
    splited = F.split(y, rchannels // 2, axis=1)
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\functional\tensor.py", line 370, in split
    sub_tensors.append(swapaxis(inp[st:se], axis, 0))
    shape = [i for i in range(inp.ndim)]
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\core\tensor\tensor_wrapper.py", line 358, in ndim
    shape = self.__wrapped__.shape
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\core\tensor\tensor.py", line 43, in shape
    return self._data.shape
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\core\tensor\raw_tensor\__init__.py", line 55, in shape
    return get_shape(self._handle)
RuntimeError: assertion `begin >= 0 && end >= begin && end <= size_ax' failed at ..\..\..\src\core\impl\tensor.cpp:151: mgb::SubTensorSpec mgb::Slice::apply(megdnn::TensorLayout, int) const
extra message: index out of bound: layout={128(4096),1(4096),64(64),64(1)}; request begin=66 end=130 step=None axis=0
bt:}
PS D:\workspace\lab\megmodel\Megvision> & D:/ProgramData/Miniconda3/envs/megengine/python.exe d:/workspace/lab/MegVision/models/classification/utils.py
64
(1, 2, 64, 64)
Traceback (most recent call last):
  File "d:/workspace/lab/MegVision/models/classification/utils.py", line 237, in <module>
    splited = F.split(y, rchannels // 2, axis=1)
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\functional\tensor.py", line 370, in split
    sub_tensors.append(swapaxis(inp[st:se], axis, 0))
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\functional\tensor.py", line 351, in swapaxis
    shape = [i for i in range(inp.ndim)]
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\core\tensor\tensor_wrapper.py", line 358, in ndim
    shape = self.__wrapped__.shape
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\core\tensor\tensor.py", line 43, in shape
    return self._data.shape
  File "D:\ProgramData\Miniconda3\envs\megengine\lib\site-packages\megengine\core\tensor\raw_tensor\__init__.py", line 55, in shape
    return get_shape(self._handle)
RuntimeError: assertion `begin >= 0 && end >= begin && end <= size_ax' failed at ..\..\..\src\core\impl\tensor.cpp:151: mgb::SubTensorSpec mgb::Slice::apply(megdnn::TensorLayout, int) const
extra message: index out of bound: layout={128(4096),1(4096),64(64),64(1)}; request begin=66 end=130 step=None axis=0
bt:}

**Comment by qliu93** [comment]
您好，这是我们代码中的一个 bug，我们立刻修复并在下一版本中更新，感谢您的反馈～

**Comment by Qsingle** [comment]
> 您好，这是我们代码中的一个 bug，我们立刻修复并在下一版本中更新，感谢您的反馈～

好的，谢谢

**Comment by Qsingle** [comment]
尝试在原版split上进行更改，解决了上述报错，更改后的代码如下
`
def split(inp, nsplits_or_sections, axis=0):
    """
    Splits the input tensor into several smaller tensors.
    When nsplits_or_sections is int, the last tensor may be smaller than others.

    :param inp: input tensor.
    :param nsplits_or_sections: number of sub tensors or sections information list.
    :param axis: which axis will be splited.
    :return: output tensor list.

    Examples:

    .. testcode::

        import numpy as np
        from megengine import tensor
        import megengine.functional as F

        x = tensor(np.random.random((2,3,4,5)), dtype=np.float32)
        out = F.split(x, 2, axis=3)
        print(out[0].numpy().shape, out[1].numpy().shape)

    Outputs:

    .. testoutput::

        (2, 3, 4, 3) (2, 3, 4, 2)

    """
    sub_tensors = []
    sections = []
    
    def swapaxis(inp, src, dst):
        if src == dst:
            return inp
        shape = [i for i in range(inp.ndim)]
        shape[src] = dst
        shape[dst] = src
        return inp.transpose(shape)
        
    inp = swapaxis(inp, 0, axis)
    if isinstance(nsplits_or_sections, int)  :
        incr_step =  nsplits_or_sections
        nsplits = np.ceil(int(inp.shape[0]) / nsplits_or_sections)
        while nsplits > 0:
            nsplits -= 1
            sections.append(incr_step)
            incr_step += incr_step
    else:
        sections = nsplits_or_sections
    st = 0
    for se in sections:
        sub_tensors.append(swapaxis(inp[st:se], axis, 0))
        st = se

    if st < inp.shape[0]:
        sub_tensors.append(swapaxis(inp[st:], axis, 0))

    return sub_tensors
`
测试代码如下
`
from megengine.jit import trace
import megengine as mge
import megengine.module as M
import megengine.functional as F
import numpy as np
@trace
def split_test(x):
    y = M.Conv2d(64, 64*2, 3, 1, padding=1, groups=2*1, dilation=1)(x)
    bs, rchannels = y.shape[:2]
    splited = split(y, int(rchannels // 2), axis=1)
    return splited

trace.enable = True
numpy_x = np.random.random((1, 64, 64, 64))
x = mge.tensor(numpy_x, dtype=np.float32)
splited = split_test(x)
print(splited[0].shape, splited[1].shape)
`

**Comment by MegChai** [comment]
你好，该 Bug 已经在 v1.2.0 版本中修复，对应 Commits 为https://github.com/MegEngine/MegEngine/commit/5c7d48cdb9c473c80563a95c53099caabd219687 欢迎使用 👏
