### ISSUE TITLE
使用 hub.load 报错 No module named 'megengine.module.normalization'

### ISSUE THREAD

**Issue by phoenix0526** [MegEngine/MegEngine#134]
## 环境
1.系统环境：使用MegStudio
2.MegEngine版本：MegEngine 1.0.0
3.python版本：Python 3.7

## 复现步骤
1.使用hub加载resnet50预训练权重

## 请提供关键的代码片段便于追查问题
```python
import megengine
from megengine import hub
model_ft = megengine.hub.load('megengine/models', 'resnet50', pretrained=True)
```

## 请提供完整的日志及报错信息
```shell
1.66MiB [01:49, 15.2kiB/s]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e15048950c0b> in <module>
----> 1 model_ft = megengine.hub.load('megengine/models', 'resnet50', pretrained=True)

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/hub/hub.py in load(repo_info, entry, git_host, use_cache, commit, protocol, *args, **kwargs)
    197         a single model with corresponding pretrained weights.
    198     """
--> 199     hubmodule = _init_hub(repo_info, git_host, use_cache, commit, protocol)
    200 
    201     if not hasattr(hubmodule, entry) or not callable(getattr(hubmodule, entry)):

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/hub/hub.py in _init_hub(repo_info, git_host, use_cache, commit, protocol)
    120     )
    121     sys.path.insert(0, absolute_repo_dir)
--> 122     hubmodule = load_module(HUBCONF, os.path.join(absolute_repo_dir, HUBCONF))
    123     sys.path.remove(absolute_repo_dir)
    124 

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/hub/tools.py in load_module(name, path)
     23     spec = importlib.util.spec_from_file_location(name, path)
     24     module = importlib.util.module_from_spec(spec)
---> 25     spec.loader.exec_module(module)
     26     return module
     27 

~/.miniconda/envs/xuan/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module)

~/.miniconda/envs/xuan/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/.cache/megengine/hub/e093aa62cdf8f313/hubconf.py in <module>
     28     shufflenet_v2_x2_0,
     29 )
---> 30 from official.vision.detection.configs import (
     31     faster_rcnn_res50_coco_1x_800size,
     32     faster_rcnn_res101_coco_2x_800size,

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/configs/__init__.py in <module>
----> 1 from .atss_res50_coco_1x_800size import atss_res50_coco_1x_800size
      2 from .atss_res101_coco_2x_800size import atss_res101_coco_2x_800size
      3 from .atss_resx101_coco_2x_800size import atss_resx101_coco_2x_800size
      4 from .faster_rcnn_res50_coco_1x_800size import faster_rcnn_res50_coco_1x_800size
      5 from .faster_rcnn_res101_coco_2x_800size import faster_rcnn_res101_coco_2x_800size

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/configs/atss_res50_coco_1x_800size.py in <module>
      9 from megengine import hub
     10 
---> 11 from official.vision.detection import models
     12 
     13 

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/models/__init__.py in <module>
      7 # software distributed under the License is distributed on an
      8 # "AS IS" BASIS, WITHOUT ARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
----> 9 from .atss import *
     10 from .faster_rcnn import *
     11 from .fcos import *

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/models/atss.py in <module>
     13 
     14 import official.vision.classification.resnet.model as resnet
---> 15 from official.vision.detection import layers
     16 
     17 

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/layers/__init__.py in <module>
      7 # software distributed under the License is distributed on an
      8 # "AS IS" BASIS, WITHOUT ARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
----> 9 from .basic import *
     10 from .det import *
     11 

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/layers/basic/__init__.py in <module>
      9 from .functional import *
     10 from .nn import *
---> 11 from .norm import *
     12 
     13 _EXCLUDE = {}

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/layers/basic/norm.py in <module>
     28 
     29 import megengine.module as M
---> 30 from megengine.module.normalization import GroupNorm, InstanceNorm, LayerNorm
     31 
     32 

ModuleNotFoundError: No module named 'megengine.module.normalization'
```

**Comment by qliu93** [comment]
您试一下 rm -r ~/.cache/megengine/hub 可以吗？可能是当前 MegEngine 版本与 cache 中的 model 脚本版本不同，有些 API 变化了～

**Comment by phoenix0526** [comment]
> 您试一下 rm -r ~/.cache/megengine/hub 可以吗？可能是当前 MegEngine 版本与 cache 中的 model 脚本版本不同，有些 API 变化了～
执行“ rm -r ~/.cache/megengine/hub “后：
rm: cannot remove '/home/megstudio/.cache/megengine/hub': No such file or directory

**Comment by qliu93** [comment]
您好，请试一下在 megengine.hub.load 函数中使用参数 use_cache=False

这确实是我们缓存机制设计的不太科学，我们已记录此问题并会尽快修复，也欢迎开源社区的开发者提交 pull request

**Comment by phoenix0526** [comment]
> 您好，请试一下在 megengine.hub.load 函数中使用参数 use_cache=False
> 
> 这确实是我们缓存机制设计的不太科学，我们已记录此问题并会尽快修复，也欢迎开源社区的开发者提交 pull request

执行代码：“model_ft = megengine.hub.load('megengine/models', 'resnet50', pretrained=True,use_cache=False)”后，仍然出现同样的错误，错误如下：
1.66MiB [00:19, 85.3kiB/s]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-ca4cfd5cfca9> in <module>
----> 1 model_ft = megengine.hub.load('megengine/models', 'resnet50', pretrained=True,use_cache=False)

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/hub/hub.py in load(repo_info, entry, git_host, use_cache, commit, protocol, *args, **kwargs)
    197         a single model with corresponding pretrained weights.
    198     """
--> 199     hubmodule = _init_hub(repo_info, git_host, use_cache, commit, protocol)
    200 
    201     if not hasattr(hubmodule, entry) or not callable(getattr(hubmodule, entry)):

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/hub/hub.py in _init_hub(repo_info, git_host, use_cache, commit, protocol)
    120     )
    121     sys.path.insert(0, absolute_repo_dir)
--> 122     hubmodule = load_module(HUBCONF, os.path.join(absolute_repo_dir, HUBCONF))
    123     sys.path.remove(absolute_repo_dir)
    124 

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/hub/tools.py in load_module(name, path)
     23     spec = importlib.util.spec_from_file_location(name, path)
     24     module = importlib.util.module_from_spec(spec)
---> 25     spec.loader.exec_module(module)
     26     return module
     27 

~/.miniconda/envs/xuan/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module)

~/.miniconda/envs/xuan/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/.cache/megengine/hub/e093aa62cdf8f313/hubconf.py in <module>
     28     shufflenet_v2_x2_0,
     29 )
---> 30 from official.vision.detection.configs import (
     31     faster_rcnn_res50_coco_1x_800size,
     32     faster_rcnn_res101_coco_2x_800size,

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/configs/__init__.py in <module>
----> 1 from .atss_res50_coco_1x_800size import atss_res50_coco_1x_800size
      2 from .atss_res101_coco_2x_800size import atss_res101_coco_2x_800size
      3 from .atss_resx101_coco_2x_800size import atss_resx101_coco_2x_800size
      4 from .faster_rcnn_res50_coco_1x_800size import faster_rcnn_res50_coco_1x_800size
      5 from .faster_rcnn_res101_coco_2x_800size import faster_rcnn_res101_coco_2x_800size

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/configs/atss_res50_coco_1x_800size.py in <module>
      9 from megengine import hub
     10 
---> 11 from official.vision.detection import models
     12 
     13 

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/models/__init__.py in <module>
      7 # software distributed under the License is distributed on an
      8 # "AS IS" BASIS, WITHOUT ARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
----> 9 from .atss import *
     10 from .faster_rcnn import *
     11 from .fcos import *

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/models/atss.py in <module>
     13 
     14 import official.vision.classification.resnet.model as resnet
---> 15 from official.vision.detection import layers
     16 
     17 

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/layers/__init__.py in <module>
      7 # software distributed under the License is distributed on an
      8 # "AS IS" BASIS, WITHOUT ARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
----> 9 from .basic import *
     10 from .det import *
     11 

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/layers/basic/__init__.py in <module>
      9 from .functional import *
     10 from .nn import *
---> 11 from .norm import *
     12 
     13 _EXCLUDE = {}

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/detection/layers/basic/norm.py in <module>
     28 
     29 import megengine.module as M
---> 30 from megengine.module.normalization import GroupNorm, InstanceNorm, LayerNorm
     31 
     32 

ModuleNotFoundError: No module named 'megengine.module.normalization'

**Comment by qliu93** [comment]
您若直接在 python3 交互环境下执行

`from megengine.module.normalization import GroupNorm, InstanceNorm, LayerNorm`

会报错吗？

**Comment by phoenix0526** [comment]
> 您若直接在 python3 交互环境下执行
> 
> `from megengine.module.normalization import GroupNorm, InstanceNorm, LayerNorm`
> 
> 会报错，错误如下：
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-f05c52f3604a> in <module>
----> 1 from megengine.module.normalization import GroupNorm, InstanceNorm, LayerNorm

ModuleNotFoundError: No module named 'megengine.module.normalization'

**Comment by qliu93** [comment]
您是在 MegStudio 环境下使用是吧～ 这看起来是 MegStudio 上 MegEngine 版本太老了，出现了 API 兼容性问题，我向相关的同事问一下情况～

**Comment by MegChai** [comment]
@qliu93 是在 MegStudio 上面，我们得想想看怎么让 Studio 也能友好地用上 Hub

**Comment by qliu93** [comment]
我刚看了一下，MegStudio 上还是 0.5.1，唉～

**Comment by MegChai** [comment]
> 我刚看了一下，MegStudio 上还是 0.5.1，唉～

MegStudio 目前对外提供 0.5.1 和 1.0.0 版本（所以如何设计能让 0.5.1 版本的人知道自己要升级呢...)

**Comment by MegChai** [comment]
MegEngine 升级到 1.1.0 版本后便可以正常使用 `hub` 模块，MegStudio 目前仅支持到 1.0.0 版本，已经和相关人员反馈了提供最新版本 MegEngine 的需求。
