### ISSUE TITLE
Conv 和 AvgPool 的 API 行为不一致

### ISSUE THREAD

**Issue by bigeagle** [MegEngine/MegEngine#136]
## 环境
1.系统环境：ubuntu18.04
2.MegEngine版本： 1.1.0
3.python版本：3.6.9

## 请提供关键的代码片段便于追查问题

```python
class NetA(M.Module):
    
    def __init__(self):
        super().__init__()
        self.conv = M.Conv2d(4, 4, kernel_size=1, stride=1, padding=0, bias=False)
    
    def forward(self, inp):
        return self.conv(inp)

    
class NetB(M.Module):
    
    def __init__(self):
        super().__init__()
        self.avg_pool = M.AvgPool2d(2, 2)
    
    def forward(self, inp):
        return self.avg_pool(inp)

    
neta = NetA()
netb = NetB()
neta(np.random.randn(1, 4, 3, 3).astype(np.float32))               # 运行通过
netb(mge.tensor(np.random.randn(1, 4, 3, 3).astype(np.float32)))    # 运行通过
netb(np.random.randn(1, 4, 3, 3).astype(np.float32))    # 报 TypeError
```

**Comment by qliu93** [comment]
已复现，我来查一下

**Comment by MegChai** [comment]
@bigeagle 您好，目前的类型检查确实不一致。对于请问您在使用 MegEngine Functional 的过程中是倾向于强制要求输入参数为 MegEngine 的 Tensor，还是倾向于觉得由 MegEngine 内部将 numpy.ndarray 自动地转化为 Tensor 会比较好呢？前者比较规范但体验不是那么地好，后者隐式转换体验好，但可能会造成一些非用户预期的情况（比如用户真的希望 Functional 是做纯 Numpy 层面的处理）。这点希望得到包括您在内的更多人的建议。

**Comment by bigeagle** [comment]
我看目前的普遍情况上 Functional API 都要求输入是 `mge.Tensor`，但是 `M.Module.forward` 好像没有要求。

我个人认为明确要求输入输出都是 `mge.Tensor` 挺好的，避免歧义，用户理解也没有困难。

**Comment by qliu93** [comment]
我们组内刚刚也讨论了一下，看起来明确 functional 和 module 都强制以 Tensor 作为输入比较自洽。

唯一需要自动转 Tensor 的地方是涉及 shape 时，传入的可能不是 Tensor 而是 tuple of int，需要转一下。

**Comment by xxr3376** [comment]
目前 MegEngine 明确了不接受 numpy array 的行为，上述代码现在会明确报错 `TypeError: py_apply expects tensor as inputs`
