### ISSUE TITLE
序列化后的静态图，如何在 python 应用中 load_and_run ？

### ISSUE THREAD

**Issue by bigeagle** [MegEngine/MegEngine#137]
## 背景
我有一个 Python 应用，需要运行 MegEngine 模型

### 训练与发布侧
- 假设有一个 `M.Module` 对象是 `network`，已经加载训练好的参数
- `jit.trace` 出来 network 的推理函数 `eval_func`
- `eval_func.dump('model.mge')`

### 应用侧

```python
import megengine.core.tensor.megbrain_graph as G

graph = G.load_graph("model.mge")

execute_graph(graph, inp_img)
```

现在我不知道 `execute_graph` 是否有封装好的 python 接口，我在 [文档](https://megengine.org.cn/doc/advanced/how_to_use_load_and_run.html) 里只找到了 C++  load 模型并执行的方法，没有找到 python API。

**Comment by bigeagle** [comment]
找到了，[megengine.utils.comp_graph_tools.load_and_inference](https://megengine.org.cn/api/latest/zh/api/megengine.utils.html?highlight=load_and_inference#megengine.utils.comp_graph_tools.load_and_inference)

**Comment by MegChai** [comment]
您好，目前 MegEngine 官网的确缺少应用侧的文档和教程，也欢迎您来贡献：

1. 您可以在天元 MegEngine 论坛分享你的应用经验

**Comment by MegChai** [comment]
@bigeagle  针对 `megengine.utils.comp_graph_tools.load_and_inference` 比较难用的情况，还希望您能够提供更多的信息，比如具体难用在哪儿，您期待的使用方式是什么样的等等。任何信息都会很有帮助！非常感谢！～

**Comment by bigeagle** [comment]
我希望 API 长这样:

```python
_, out_dict, out_list = G.load_graph(fileobj_or_name)

outspec = out_list[0]
inference_func = GraphFunction().compile(outspec)
out : np.ndarray = inference_func(inp1, inp2, arg3=inp3)

outspec = {'out': out_list[0]}
inference_func = GraphFunction().compile(outspec)
out : Dict[str, np.ndarray] = inference_func(inp1, inp2, arg3=inp3)

outspec = out_list
inference_func = GraphFunction().compile(outspec)
out : List[np.ndarray] = inference_func(inp1, inp2, arg3=inp3) 
```

这里面有个实现上的难点: graph dump 的时候可以选择指定或不指定 input / output 的名称，所以 `inference_func` 对于 input 参数的顺序、名称之类的可能比较麻烦。

**Comment by bigeagle** [comment]
```python
class GraphFunction:
    
    def __init__(self, filename):
        *_, out_list = G.load_graph(filename)
        inputs = cgtools.get_dep_vars(out_list, "Host2DeviceCopy")
        replace_dict = {}
        inp_node_list = []
        for i in inputs:
            inp_node = G.InputNode(
                device="xpux", dtype=inputs[0].dtype, graph=inputs[0].graph
            )
            replace_dict[i] = inp_node.outputs[0]
            inp_node_list.append(inp_node)
        new_out = cgtools.replace_vars(out_list, replace_dict)
        out_node_list = [G.OutputNode(i) for i in new_out]
        new_out_list = [i.outputs[0] for i in out_node_list]
        cg = new_out_list[0].graph
        self._func = cg.compile(new_out_list)
        self._inp_node_list = inp_node_list
        self._out_node_list = out_node_list
        
    def __call__(self, *inp_data_list):
        for node, value in zip(self._inp_node_list, inp_data_list):
            node.set_value(as_raw_tensor(value)._dev_tensor())
        self._func.execute()
        out_data_list = [o.get_value().numpy() for o in self._out_node_list]
        return out_data_list
```

我自己用的时候是把 `megengine.utils.comp_graph_tools.load_and_inference` 拆了一下，但是 input / output 参数就不太好处理。

**Comment by lixiangyin666** [comment]
目前load_and_inference是给定模型和输入，然后输出结果，而用户的需求是load, and inference，即load一次，inference多次。需求很合理，我们跟进修改

**Comment by megvii-mge** [comment]
https://github.com/MegEngine/MegEngine/commit/8e50a6daa771a621d445c9513a9553ec46478cdd#diff-6b7b73be0ff9c60bf1f2989c8768d72b60177a0337125ac24748a5ca2ee75d7e
您好，此需求已经在以上commit 中完成
此issue先关闭，如果有更多问题欢迎提交issue沟通～
