### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by HanochZzhou** [MegEngine/MegEngine#14]
## 请简要描述您的需求
![problem](https://user-images.githubusercontent.com/32918541/77551628-8f609f00-6eed-11ea-9be8-ee870eaf6e1f.png)

我按照官网的描述在虚拟环境中执行了安装命令，但是导入的时候报错了。
如图片所示，
请问该怎么解决，谢谢~

**Comment by chengyumeng** [comment]
megengine 在 megstudio 中已经预装了，无须自己安装。

**Comment by wjy9** [comment]
pip需要使用19.0以上版本

**Comment by HanochZzhou** [comment]
@chengyumeng 您好，谢谢您的帮助，我是自己创建的虚拟环境，然后在jupyter notebook 里面测试的，没有使用megstudio，

**Comment by HanochZzhou** [comment]
@wjy9 您好，我检查了pip 的版本，是20.0.2
