### ISSUE TITLE
how to close the warning logging words ?

### ISSUE THREAD

**Issue by yexiguafuqihao** [MegEngine/MegEngine#143]
## 背景

在训练FPN的过程中存在很多的数组索引,定义的检测模型文件是可以跑起来的,但是在训练过程中总是回出现warning文件,样子很不美观:

## 任务描述

20 20:03:40[mgb] WRN indexing_multi_axis_vec(device_value[746096494])[746096498]{IndexingMultiAxisVec}: no vector indexer; consider using Subtensor family for better performance; you can set MGB_THROW_ON_SCALAR_IDX to throw an exception to help tracking the related operator
20 20:03:40[mgb] WRN indexing_set_multi_axis_vec(device_value[746096531],device_value[746096533])[746096537]{IndexingSetMultiAxisVec}: no vector indexer; consider using Subtensor family for better performance; you can set MGB_THROW_ON_SCALAR_IDX to throw an exception to help tracking the related operator
20 20:03:40[mgb] WRN indexing_multi_axis_vec(device_value[746123394])[746123398]{IndexingMultiAxisVec}: no vector indexer; consider using Subtensor family for better performance; you can set MGB_THROW_ON_SCALAR_IDX to throw an exception to help tracking the related operator
这些字体均为红色字体.
## 目标

一行或者几行代码关闭这些没用的logging文字,让显示更加的美观.

**Comment by xpmemeda** [comment]
试试这个：

```python3
from megengine.core._imperative_rt.utils import Logger
Logger.set_log_level(Logger.LogLevel.Error)
```

**Comment by yexiguafuqihao** [comment]
It certainly works, thank you so much.
