### ISSUE TITLE
在MegEngine中如何修改加载了预训练权重的模型的输入或输出 

### ISSUE THREAD

**Issue by phoenix0526** [MegEngine/MegEngine#144]
## 背景
使用迁移学习训练网络

## 任务描述
加载MegEngine的resnet50预训练权重，并对最后一层进行修改以适应本模型分类任务
代码示例：
```
model = megengine.hub.load('megengine/models', 'resnet50', pretrained=True)
model.fc = M.Conv2d(in_channels=2048, out_channels=3, kernel_size=(1, 1), stride=(1, 1))
```
## 问题分析
不对预训练权重进行任何改动的话 可以正常进行测试 
代码示例：
```
import megengine.hub
model = megengine.hub.load('megengine/models', 'resnet50', pretrained=True)
model.eval()
import urllib
url, filename = ("https://data.megengine.org.cn/images/cat.jpg", "cat.jpg")
try: urllib.URLopener().retrieve(url, filename)
except: urllib.request.urlretrieve(url, filename)

import cv2
import numpy as np
import megengine.data.transform as T
import megengine.functional as F

image = cv2.imread("cat.jpg")
transform = T.Compose([
    T.Resize(256),
    T.CenterCrop(224),
    T.Normalize(mean=[103.530, 116.280, 123.675], std=[57.375, 57.120, 58.395]),  # BGR
    T.ToMode("CHW"),
])
processed_img = transform.apply(image)[np.newaxis, :]  # CHW -> 1CHW
logits = model(processed_img)
probs = F.softmax(logits)
print(probs)
```
但对加载的预训练权重resnet50模型的输出进行修改后，会报维数不对的错误 
 错误如下:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-bd9e03beb726> in <module>
     20 ])
     21 processed_img = transform.apply(image)[np.newaxis, :]  # CHW -> 1CHW
---> 22 logits = model(processed_img)
     23 probs = F.softmax(logits)
     24 print(logits.shape)

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/module/module.py in __call__(self, *inputs, **kwargs)
    111                 inputs = modified_inputs
    112 
--> 113         outputs = self.forward(*inputs, **kwargs)
    114 
    115         for hook in self._forward_hooks.values():

~/.cache/megengine/hub/e093aa62cdf8f313/official/vision/classification/resnet/model.py in forward(self, x)
    298         x = F.avg_pool2d(x, 7)
    299         x = F.flatten(x, 1)
--> 300         x = self.fc(x)
    301 
    302         return x

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/module/module.py in __call__(self, *inputs, **kwargs)
    111                 inputs = modified_inputs
    112 
--> 113         outputs = self.forward(*inputs, **kwargs)
    114 
    115         for hook in self._forward_hooks.values():

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/module/conv.py in forward(self, inp)
    376 
    377     def forward(self, inp):
--> 378         return self.calc_conv(inp, self.weight, self.bias)
    379 
    380 

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/module/conv.py in calc_conv(self, inp, weight, bias)
    372             self.groups,
    373             self.conv_mode,
--> 374             self.compute_mode,
    375         )
    376 

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/functional/nn.py in conv2d(inp, weight, bias, stride, padding, dilation, groups, conv_mode, compute_mode)
    155     )
    156     inp, weight = utils.convert_inputs(inp, weight)
--> 157     (output,) = apply(op, inp, weight)
    158     if bias is not None:
    159         output += bias

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/core/ops/builtin/__init__.py in _(op, *args)
     22 @apply.register()
     23 def _(op: PodOpVisitor, *args: Union[TensorBase, TensorWrapperBase]):
---> 24     return apply(op.to_c(), *args)
     25 
     26 

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/core/tensor/core.py in _(op, *args)
     44     assert args
     45     Wrapper = type(args[0])
---> 46     outputs = apply(op, *(i.__wrapped__ for i in args))
     47     assert isinstance(outputs, tuple)
     48     return tuple(map(Wrapper, outputs))

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/core/tensor/tensor.py in tensor_apply(op, *args)
     87     # type(Tensor._data) is RawTensor
     88     # dispached to apply.add@RawTensor.py if passed Tensor args
---> 89     outputs = apply(op, *data)
     90     ret = tuple(map(Tensor, outputs))
     91 

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/core/tensor/raw_tensor/__init__.py in _(op, *args)
     78 @apply.register()
     79 def _(op: OpDef, *args: RawTensor):
---> 80     outputs = apply_op(op, tuple(i._handle for i in args))
     81     return tuple(map(RawTensor, outputs))
     82 

RuntimeError: assertion `src.ndim >= 3_z' failed at /home/code/dnn/src/common/convolution.cpp:674: megdnn::ConvolutionBase<Parameter>::CanonizedFilterMeta megdnn::ConvolutionBase<Parameter>::deduce_layout_fwd(const megdnn::TensorLayout&, const megdnn::TensorLayout&, megdnn::TensorLayout&) const [with Parameter = megdnn::param::Convolution]
extra message: src={1(2048),2048(1)}, filter={3(2048),2048(1),1(1),1(1)}, dst={}, is_nchw=1, is_xcorr=1, pad_h=0, pad_w=0, stride_h=1, stride_w=1, dilate_h=1, dilate_w=1
bt:/home/megstudio/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/core/_imperative_rt.cpython-37m-x86_64-linux-gnu.so{1e80906,1f69561,227db14,227f0e2}
​```

**Comment by xpmemeda** [comment]
在 fc 之前 x 被 F.flatten 压缩成 2 维，而 conv 的输入应该是 4 维。
建议到 [MegEngine/Models ](https://github.com/MegEngine/Models)仓库下载代码修改。

**Comment by phoenix0526** [comment]
> 在 fc 之前 x 被 F.flatten 压缩成 2 维，而 conv 的输入应该是 4 维。
> 建议到 [MegEngine/Models ](https://github.com/MegEngine/Models)仓库下载代码修改。

老师您好，没有明白您的意思，我想知道在MegEngine中应该如何修改resnet50预训练权重模型的输出，比如pytorch的这个https://blog.csdn.net/Accepted_Lam/article/details/104711237?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-1.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-1.control，如何将resnet50最终的1000分类改为3分类呢？

**Comment by xpmemeda** [comment]
你可以尝试这样来写：
```python3
model.fc = M.Linear(in_features=2048, out_features=3)
```
模型大部分参数保持不变，但是最后分类器的权重是新的，仍然需要训练。

**Comment by phoenix0526** [comment]
> 你可以尝试这样来写：
> 
> ```python
> model.fc = M.Linear(in_features=2048, out_features=3)
> ```
> 
> 模型大部分参数保持不变，但是最后分类器的权重是新的，仍然需要训练。

老师您好，这样的话，可以只训练最后一层的参数吗？前面的参数固定不变

**Comment by xpmemeda** [comment]
> 可以只训练最后一层的参数吗？前面的参数固定不变

参考[这里](https://github.com/MegEngine/Models/blob/master/official/vision/classification/resnet/train.py#L153)，替换成你想要训练的参数就行。

**Comment by phoenix0526** [comment]
> > 可以只训练最后一层的参数吗？前面的参数固定不变
> 
> 参考[这里](https://github.com/MegEngine/Models/blob/master/official/vision/classification/resnet/train.py#L153)，替换成你想要训练的参数就行。

老师，这样修改的话，意思是需要使用ImageNet数据集对整个修改后的网络结构进行从头训练了吗？

> > 可以只训练最后一层的参数吗？前面的参数固定不变
> 
> 参考[这里](https://github.com/MegEngine/Models/blob/master/official/vision/classification/resnet/train.py#L153)，替换成你想要训练的参数就行。

老师，最后一层可以不接M.Linear，改为接一个卷积层吗（比如：model.fc = M.Conv2d(in_channels=2048, out_channels=3, kernel_size=(1, 1), stride=(1, 1))）

**Comment by MegChai** [comment]
@xpmemeda 她的需求是使用 ResNet50 的预训练好的权重来在一个新的任务上做迁移，相较于原版的 ResNet50 输出是 1000 个分类的情况，新的任务的输出只有 3 个分类，所以在 Model 定义的时候最后输出的结构要做对应的修改。这个时候就出现了两个问题：
1. 预训练好的权重里面的参数如何在指定位置进行修改并使用？能否有一个例子？
2. 由于预训练模型前面很多层的参数都是训练得比较好的，能不能在训练的时候冻结住（`freeze` ）它们，让这些层只做前向传播而不更新权重，只在最后一层做更新。

**Comment by phoenix0526** [comment]
> @xpmemeda 她的需求是使用 ResNet50 的预训练好的权重来在一个新的任务上做迁移，相较于原版的 ResNet50 输出是 1000 个分类的情况，新的任务的输出只有 3 个分类，所以在 Model 定义的时候最后输出的结构要做对应的修改。这个时候就出现了两个问题：
> 
> 1. 预训练好的权重里面的参数如何在指定位置进行修改并使用？能否有一个例子？
> 2. 由于预训练模型前面很多层的参数都是训练得比较好的，能不能在训练的时候冻结住（`freeze` ）它们，让这些层只做前向传播而不更新权重，只在最后一层做更新。

老师 不是这样的，修改最后一层输出为3层，训练的时候使用本数据集对整个网络参数进行训练，无需冻结前面已经预训练好的权重，我们现在只是把resnet50的模型参数作为初始化参数，后面训练会一直更新，这样做只是为了加快训练速度，避免过拟合。

**Comment by MegChai** [comment]
> > 你可以尝试这样来写：
> > ```python
> > model.fc = M.Linear(in_features=2048, out_features=3)
> > ```
> > 
> > 
> > 模型大部分参数保持不变，但是最后分类器的权重是新的，仍然需要训练。
> 
> 老师您好，这样的话，可以只训练最后一层的参数吗？前面的参数固定不变

额，那你这里的 “只训练最后一层的参数” 是指什么呀，前面的参数不训练的话就是冻住了呀。

**Comment by phoenix0526** [comment]
> > > 你可以尝试这样来写：
> > > ```python
> > > model.fc = M.Linear(in_features=2048, out_features=3)
> > > ```
> > > 
> > > 
> > > 模型大部分参数保持不变，但是最后分类器的权重是新的，仍然需要训练。
> > 
> > 
> > 老师您好，这样的话，可以只训练最后一层的参数吗？前面的参数固定不变
> 
> 额，那你这里的 “只训练最后一层的参数” 是指什么呀，前面的参数不训练的话就是冻住了呀。

老师，只训练最后一层的参数也是其中一种思想，我和师姐确认过了，我们采取的不是这种思想，而是不冻结预训练好的权重的思想

**Comment by MegChai** [comment]
> > 在 fc 之前 x 被 F.flatten 压缩成 2 维，而 conv 的输入应该是 4 维。
> > 建议到 [MegEngine/Models ](https://github.com/MegEngine/Models)仓库下载代码修改。
> 
> 老师您好，没有明白您的意思，我想知道在MegEngine中应该如何修改resnet50预训练权重模型的输出，比如pytorch的这个：
> https://blog.csdn.net/Accepted_Lam/article/details/104711237?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-1.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-1.control
> 如何将resnet50最终的1000分类改为3分类呢？同时保留在ImageNet上训练好的权重，并非重新使用ImageNet数据集从头训练（仅是一个finetune操作）

你引用处这里的需求是 “将resnet50最终的1000分类改为3分类”，那么说明改的是最后一层的 out_features 变成 `M.Linear(in_features=2048, out_features=3)`。

如果按照你上面说的 “修改最后一层输出为3层”，就等于对最后面的模型结构做了修改，一层 fc 变成了 conv+relu+fc 三层，这是层数上直接的变化。

两个需求的表述还是不太一样的。

**Comment by xpmemeda** [comment]
> 最后一层可以不接M.Linear，改为接一个卷积层吗

可以的，只不过由于 ``M.Linear`` 和 ``M.Conv2d`` 要求输入的格式不同，你只改最后一层是不行的。你需要：

- 下载模型代码，修改它的 ``forward``函数。
- 下载预训练好的权重，使用 ``load_state_dict`` 并设置参数 ``strict=False`` 来加载他们。

**Comment by phoenix0526** [comment]
> > 最后一层可以不接M.Linear，改为接一个卷积层吗
> 
> 可以的，只不过由于 `M.Linear` 和 `M.Conv2d` 要求输入的格式不同，你只改最后一层是不行的。你需要：
> 
> * 下载模型代码，修改它的 `forward`函数。
> * 下载预训练好的权重，使用 `load_state_dict` 并设置参数 `strict=False` 来加载他们。

好的老师
