### ISSUE TITLE
custom C++ AND CUDA EXTENSIONS

### ISSUE THREAD

**Issue by Feynman1999** [MegEngine/MegEngine#147]
## 问题描述
how to custom C++ AND CUDA EXTENSIONS （for efficiency）?
for example,  pytorch's document:  [https://pytorch.org/tutorials/advanced/cpp_extension.html?highlight=pybind11_module](https://pytorch.org/tutorials/advanced/cpp_extension.html?highlight=pybind11_module)
If you can provide such documents, I think it will be very helpful!

**Comment by dc3671** [comment]
Thank you for your question. External C op is under developing for version 1.0+

**Comment by xxr3376** [comment]
@Feynman1999 Please check custom op support in https://www.megengine.org.cn/doc/stable/zh/user-guide/tools/customop.html
