### ISSUE TITLE
初始化 tensor 卡住

### ISSUE THREAD

**Issue by SuTanTank** [MegEngine/MegEngine#151]
## 环境
1.系统环境：同一台电脑 Windows, Linux 下都出现（ 5800X + RTX3070 ）
2.MegEngine版本：1.2.0
3.python版本：3.8
4. CUDA 11.1 

## 复现步骤
1. 执行最简单的 Tensor 指令，如 ```mge.tensor(range(10))``` 无响应。看上去显示仍在执行，但是许久没有结果。
2. 
3.

## 请提供关键的代码片段便于追查问题
```
import numpy as np
import megengine as mge
mge.tensor(range(10))
```
单步执行发现卡在 ```_Tensor.new()```

**Comment by MegChai** [comment]
您好，1.2.0 版本的 MegEngine 尚未正式支持 CUDA 11 以及 30 系显卡。

后台设备驱动在运行时执行在线编译，使用 PTX 代码生成二进制代码，因此会导致程序启动的用时变得非常长。您可以尝试等待这个过程结束，看是否依旧会有报错（对于大模型的训练用时，这些时间还是可以接受的，具体用时根据机器性能而定）。

对于体验 MegEngine 的用户而言，如果您手头上没有其它的非 30 系显卡，可以尝试在 [MegStudio](https://studio.brainpp.com/) 上进行 MegEngine 的初体验。

我们会在下一个 1.3 版本支持 CUDA 11 的 Build from Source. 还请您耐心等待。

由于最近是春节假期，回复可能会不及时，还请您理解。给您拜个早年了～

**Comment by MegChai** [comment]
您好，v1.3 版本已经发布，欢迎试用和反馈～

**Comment by haolongzhangm** [comment]
@SuTanTank  try  https://github.com/Qsingle/MegEngine_CU11

**Comment by SuTanTank** [comment]
> @SuTanTank try https://github.com/Qsingle/MegEngine_CU11

安装了11.2 + Python 3.8 的版本，上述代码可以执行，不过似乎仍然是JIT

> 10 22:57:54[mgb] WRN [dnn] 
        Cudnn8 will jit ptx code with cache. You can set 
        CUDA_CACHE_MAXSIZE and CUDA_CACHE_PATH environment var to avoid repeat jit(very slow).
        For example `export CUDA_CACHE_MAXSIZE=2147483647` and `export CUDA_CACHE_PATH=/data/.cuda_cache`

**Comment by haolongzhangm** [comment]
> > @SuTanTank try https://github.com/Qsingle/MegEngine_CU11
> 
> 安装了11.2 + Python 3.8 的版本，上述代码可以执行，不过似乎仍然是JIT
> 
> > 10 22:57:54[mgb] WRN [dnn]
> > Cudnn8 will jit ptx code with cache. You can set
> > CUDA_CACHE_MAXSIZE and CUDA_CACHE_PATH environment var to avoid repeat jit(very slow).
> > For example `export CUDA_CACHE_MAXSIZE=2147483647` and `export CUDA_CACHE_PATH=/data/.cuda_cache`

这个是cudnn 自己部分kernel 需要在线编译，但是这个init时间很短，且可以按照提示，保留他的cache

**Comment by xxr3376** [comment]
Already support CUDA11 version after v1.11
