### ISSUE TITLE
SyncBatchNorm 的 Freeze 属性无效

### ISSUE THREAD

**Issue by bigeagle** [MegEngine/MegEngine#153]
## 环境
1.系统环境：ubuntu18.04
2.MegEngine版本：1.2.0
3.python版本：3.6

## 请提供关键的代码片段便于追查问题
在 [SyncBatchNorm](https://github.com/MegEngine/MegEngine/blob/master/imperative/python/megengine/module/batchnorm.py#L185) 的 `forward` 逻辑中，未包含 `freeze=True` 时的处理，导致 `Freeze` 属性设置无效。

**Comment by fzhangscorec** [comment]
`freeze=True` 时传给 `sync_batch_norm` 的 `training=False`，https://github.com/MegEngine/MegEngine/blob/master/imperative/python/megengine/module/batchnorm.py#L205

**Comment by bigeagle** [comment]
看起来是master上修掉了…… 
https://github.com/MegEngine/MegEngine/blob/release-1.2/imperative/python/megengine/module/batchnorm.py
