### ISSUE TITLE
CMake build error when set MGE_WITH_JIT_MLIR ON

### ISSUE THREAD

**Issue by hqli** [MegEngine/MegEngine#160]
## 环境
1.系统环境：Ubuntu18.04
2.MegEngine版本：release-1.2
3.python版本：3.6.9

## 复现步骤
1. `export EXTRA_CMAKE_ARGS=-DMGE_WITH_JIT_MLIR=ON`
2. `./scripts/cmake-build/host_build.sh -d`

## 请提供关键的代码片段便于追查问题

见复现步骤

## 请提供完整的日志及报错信息

```
EXTRA_CMAKE_ARGS: -DMGE_WITH_JIT_MLIR=ON./scripts/cmake-build/host_build.sh
Build with Debug mode
------------------------------------
build config summary:
BUILD_TYPE: Debug
MGE_WITH_CUDA: OFF
MGE_INFERENCE_ONLY: ON
.......
-- GPU support is disabled
-- Intel(R) MKL: include /data1/xxx/_Git/MegEngine/third_party/mkl/x86_64/include
-- Intel(R) MKL: lib libmkl
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Error at CMakeLists.txt:868 (add_subdirectory):
  add_subdirectory given source "tools/mlir/mgb-opt" which is not an existing
  directory.


CMake Error at CMakeLists.txt:869 (add_subdirectory):
  add_subdirectory given source "tools/mlir/mgb-file-check" which is not an
  existing directory.


-- Configuring incomplete, errors occurred!
See also "/data1/xxx/_Git/MegEngine/build_dir/host/MGE_WITH_CUDA_OFF/MGE_INFERENCE_ONLY_ON/Debug/build/CMakeFiles/CMakeOutput.log".
See also "/data1/xxx/_Git/MegEngine/build_dir/host/MGE_WITH_CUDA_OFF/MGE_INFERENCE_ONLY_ON/Debug/build/CMakeFiles/CMakeError.log".
```

**Comment by haolongzhangm** [comment]
看起来是少了  ./third_party/prepare.sh

**Comment by haolongzhangm** [comment]
看起来是代码同步有点问题， 另外等修复后， 你要开 MGE_WITH_JIT_MLIR 这个话， 需要同时开   scripts/cmake-build/host_build.sh -c  把cuda开起来，否则内部会把 MGE_WITH_JIT_MLIR 一起关闭掉

**Comment by hqli** [comment]
回复好及时。十分感谢。
最近在研究MLIR，比较看好深度学习编译器的未来。
也在看MegEngine的源码，架构很清晰，上手很快。

**Comment by sethbrin** [comment]
没有将`tools/mlir`目录同步出来，@haolongzhangm MLIR没有强制需要和cuda绑定，感觉需要修一下

**Comment by haolongzhangm** [comment]
@sethbrin  曾叔叔，tools/mlir 会在下次import 出来， 另外你提到的"MLIR没有强制需要和cuda绑定"会在 后面修复

**Comment by xxr3376** [comment]
Solved with c85eefded4f2b6b3a818dd90e451bcfc3707cebe , @hqli You can have a try now

**Comment by Haoran-Solar** [comment]
使用同样的步骤，出现新的问题
![image](https://user-images.githubusercontent.com/56677718/116197408-4ff72880-a767-11eb-8c5d-651b37ce3395.png)

wired

**Comment by haolongzhangm** [comment]
@Haoran-Solar  你最新的构建命令是什么
