### ISSUE TITLE
在 megengine 中有什么 API 可以获取到“显存峰值”等这些状态信息吗？

### ISSUE THREAD

**Issue by MegChai** [MegEngine/MegEngine#169]
已将该问题移动到 MegEngine 主存储库。 cc @lijiansong 

https://github.com/MegEngine/Documentation/pull/148#commitcomment-50120715

**Comment by lijiansong** [comment]
感谢。
补充一下，这个问题是针对最近1.4.0版本的DTR大模型训练显存优化功能的。
有没有什么好用的API可以获取到gpu显存的状态信息？

**Comment by MegChai** [comment]
目前提供了 [megengine.get_mem_status_bytes](https://megengine.org.cn/doc/stable/zh/reference/api/megengine.get_mem_status_bytes.html#megengine.get_mem_status_bytes) 接口，不知道是否能满足需求

**Comment by lijiansong** [comment]
@MegChai 感谢！虽然这个接口能读到gpu的显存占用信息，但是只能看到某一瞬时的。无法满足需求。

训练时想拿到peak active bytes等信息，还是需要修改megaengine的代码，显式调用`cudaMemGetInfo`才是最准确的。
后续MegEngine可以考虑把内存状态的信息暴露出来，这样也方便调试和二次开发。

**Comment by lijiansong** [comment]
@MegChai This issue can be closed!
