### ISSUE TITLE
是否可以添加类似torch.Tensor.expand相类似的函数

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#170]
希望可以提供torch.Tensor.expand的实现。

## 背景
在复现EncNet的过程中存在一个tensor扩展的需求，尝试repeat与expand_dims搭配与tail进行替代，但是这带来了很大的显存占用，一张64x64的图像都无法在8G显存搞定。

**Comment by fzhangscorec** [comment]
您好，已有的megengine.functional.broadcast_to 预计是torch.Tensor.expand的等价实现，目前还没有实现类似torch通过修改tensor stride来节省显存，相关的开发在进行中。

**Comment by Qsingle** [comment]
好的，感谢，期待变得更好。

**Comment by Qsingle** [comment]
Feature
