### ISSUE TITLE
when is fake_quantization operation performed in QAT?

### ISSUE THREAD

**Issue by NewEricWang** [MegEngine/MegEngine#179]
Two questions about QAT model:
* I think fake_quantization of weights is performed once  a batch only because they are remained unchanged in each training batch.  So observer of weight quantization is counted after weight is updated each batch. Is it right?
* Observers of other tensors except weight are counted in forward procedure from each sample. Afterwards, the scale and  zero_point from these observers is applied to fake_quantize these tensor for next sample. In other words, observers of other tensors except weight as well as  the scale and  zero_point for their fake_quantization are constantly updated along with training data input.

**Comment by xpmemeda** [comment]
Fake quant will be performed whenever the weight and activation values are needed. 

As you said, the scale/zeropoint of the activation changes all over the time, while that of the weight remains unchanged in each training epoch.

**Comment by NewEricWang** [comment]
Thanks!
I wonder when fake quant for the weight will be performed.  If it is performed on each data in forward procedure, it is not necessary. 
Is my thought about it correct?

**Comment by xpmemeda** [comment]
you are right.

**Comment by NewEricWang** [comment]
Ok! 
Thanks for your patient interpretation！
