### ISSUE TITLE
CMakeLists.txt cuda10.1+cudnn7.6.3 版本引用 cublasLt.a 失败

### ISSUE THREAD

**Issue by tpoisonooo** [MegEngine/MegEngine#183]
## 请简要描述您的需求

我的 cuda10.1 + cudnn7.6.3 并没有 cublasLt.a，印象里是 cuda11 才有。求大佬确认一下版本没有搞错。

![image](https://user-images.githubusercontent.com/7872421/123250610-d7210c80-d51c-11eb-948f-2b3233bdec1d.png)

注释掉了以下几行，感觉不太对。目前编译通过 ：
![image](https://user-images.githubusercontent.com/7872421/123250883-2a935a80-d51d-11eb-8047-7e23610cffb4.png)

**Comment by qliu93** [comment]
cuda-10.1 的 lib64 目录下应该有一个 libcublasLt_static.a，你看看有没有，如果没有的话可以尝试换一个 cuda 安装包

**Comment by tpoisonooo** [comment]
![image](https://user-images.githubusercontent.com/7872421/123368138-d08ea580-d5ad-11eb-8236-c3a77816a484.png)


![image](https://user-images.githubusercontent.com/7872421/123368089-b9e84e80-d5ad-11eb-917c-0a0deb8268ca.png)

cuda11.0 才有。

**Comment by MegChai** [comment]
这个问题已经解决了吗？

**Comment by tpoisonooo** [comment]
我先彻底跑起来 python import mge 最后再看要不要提 issue.

**Comment by MegChai** [comment]
好的，如果过程中遇到什么其它问题，欢迎咨询。

**Comment by tpoisonooo** [comment]
> 好的，如果过程中遇到什么其它问题，欢迎咨询。

啊抱歉，是开发环境里的 cuda10.1 缺了这个文件。 重新下载新的是有的。
