### ISSUE TITLE
./third_party/prepare.sh error

### ISSUE THREAD

**Issue by hello-lx** [MegEngine/MegEngine#189]
根据官网进行 cmake，会出错

yuan@Y:~/XSpace/Project/MegEngine/build$ cmake .. -DMGE_WITH_CUDA=OFF -DMGE_WITH_TEST=OFF
-- CMAKE_GENERATOR: Unix Makefiles
CMake Warning at CMakeLists.txt:4 (message):
  CMAKE_GENERATOR NOT EQUAL Ninja, which we do not recommend

-- Building MegBrain 8.9999.0
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 6.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXX_SUPPORT_WCLASS_MEMACCESS
-- Performing Test CXX_SUPPORT_WCLASS_MEMACCESS - Failed
-- Enable cpuinfo runtime check and little kernel optimize.
CMake Error at cmake/cpuinfo.cmake:19 (add_subdirectory):
  The source directory

   /home/yuan/XSpace/Project/MegEngine/third_party/cpuinfo

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:170 (include)

-- Performing Test CXX_SUPPORT_GOLD
-- Performing Test CXX_SUPPORT_GOLD - Success
-- Using GNU gold linker.
-- Disable TensorRT support, as CUDA is not enabled.
-- Found PythonInterp: /home/yuan/anaconda3/bin/python3 (found suitable version "3.6.5", minimum required is "3") 
-- use python3 as PYTHON3_EXECUTABLE_WITHOUT_VERSION
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Disable distributed support, as both CUDA and ROCm are disabled.
CMake Error at cmake/llvm-project.cmake:69 (add_subdirectory):
  add_subdirectory given source "third_party/llvm-project/llvm" which is not
  an existing directory.
Call Stack (most recent call first):
  cmake/llvm-project.cmake:86 (add_mge_mlir_src_dep)
  CMakeLists.txt:371 (include)

CMake Error at cmake/flatbuffers.cmake:28 (add_subdirectory):
  The source directory

 /home/yuan/XSpace/Project/MegEngine/third_party/flatbuffers

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)

CMake Error at cmake/flatbuffers.cmake:30 (add_library):
  add_library cannot create ALIAS target "flatbuffers::flatbuffers" because
  target "flatbuffers" does not already exist.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)

CMake Error at cmake/mkl.cmake:14 (message):
  Can not find MKL
Call Stack (most recent call first):
  CMakeLists.txt:658 (include)

-- Configuring incomplete, errors occurred!
See also "/home/yuan/XSpace/Project/MegEngine/build/CMakeFiles/CMakeOutput.log".
See also "/home/yuan/XSpace/Project/MegEngine/build/CMakeFiles/CMakeError.log".

**Comment by MegChai** [comment]
看起来是没有安装环境依赖，请参考  https://megengine-docs.iap.hh-b.brainpp.cn/user-guide/install/index.html#id3

**Comment by hello-lx** [comment]
> 看起来是没有安装环境依赖，请参考 https://megengine-docs.iap.hh-b.brainpp.cn/user-guide/install/index.html#id3

.......
进入 'llvm-project'
进入 'midout'
进入 'protobuf'
进入 'pybind11'
进入 'range-v3'
remote: Total 0 (delta 0), reused 0 (delta 0)
error: 服务器不允许请求未公开的对象 3b8ae875a9e5c95031aca5edcc4233051d774eb5
获取了子模组路径 'midout'，但是它没有包含 3b8ae875a9e5c95031aca5edcc4233051d774eb5。直接获取该提交失败。

在安装环境中，用git下载依赖库的时候出现这个情况有什么好的解决办法吗

**Comment by MegChai** [comment]
> error: 服务器不允许请求未公开的对象

看起来是 git 相关处理出现了问题，我这边是能够正常使用的：

![image](https://user-images.githubusercontent.com/21091736/125033082-728bb300-e0c1-11eb-8331-ad764f050cc4.png)

你可以考虑删除掉该 `midout` 文件夹，重新执行 prepare.sh

**Comment by hello-lx** [comment]
yuan@X:/media/yuan/D/Linux/Xstudio/MegEngine/third_party$ rm -r midout/
yuan@X:/media/yuan/D/Linux/Xstudio/MegEngine/third_party$ cd ..
yuan@X:/media/yuan/D/Linux/Xstudio/MegEngine$ ./third_party/prepare.sh 
为 'midout' 同步子模组 url
error: 服务器不允许请求未公开的对象 3b8ae875a9e5c95031aca5edcc4233051d774eb5
获取了子模组路径 'midout'，但是它没有包含 3b8ae875a9e5c95031aca5edcc4233051d774eb5。直接获取该提交失败。

**Comment by xxr3376** [comment]
closed due to inactivate
