### ISSUE TITLE
model initialize error

### ISSUE THREAD

**Issue by ustbzjf1** [MegEngine/MegEngine#192]
## 环境
1.系统环境：linux
2.MegEngine版本：1.2
3.python版本：3.6.9

## 复现步骤
目前还没有找到最小复现。问题背景是这样：我需要用megengine进行搜参，基于megengine定义了一个retinanet。搜参过程可以简化为如下流程：获取超参组合1——训练模型1——测试模型1——再获取超参组合2——**训练模型2**——测试模型2。这个时候问题发生了，报错信息见后文。这个错误显示我的网络在启动第二轮训练（训练模型2）的时候网络定义初始化直接失败了。神奇的是：获取超参组合1——训练模型1——获取超参组合2——训练模型2 。。。，这个流程可以一直迭代下去，但是一加入测试流程，下一次训练网络初始化就出问题了。debug1：发现在return [tensor(self.generate_base_anchors(scale, ratio)) for scale, ratio in zip(scales, ratios)]这一句代码处前后两次训练输入数据没有发生任何变化，包括数值以及类型、精度。每一次启动训练或者测试都会重新定义网络，案例就算测试设置了.eval也不应该影响下一次网络定义和初始化，神奇的是第二次训练网络定义时的初始化就是通不过。debug2：尝试不进行超参更换，同样一组超参，训练1——测试1——训练2——测试2，发现即便是同一组超参，只要网络经过测试，再回头定义相同的网络结构用于训练依然会失败。报错信息就是下文最后一句。

## 请提供完整的日志及报错信息
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhengjunfeng/megengine-retinanet/hpo/engine/mge_trainer.py", line 71, in worker
    model = current_network.Net(config)
  **File "/home/zhengjunfeng/megengine-retinanet/models/retinanet.py", line 31, in __init__
    offset=self.cfg.anchor_offset,
  File "/home/zhengjunfeng/megengine-retinanet/layers/det/anchor.py", line 84, in __init__
    self.base_anchors = self._different_level_anchors(anchor_scales, anchor_ratios)**
  File "/home/zhengjunfeng/megengine-retinanet/layers/det/anchor.py", line 98, in _different_level_anchors
    return [tensor(self.generate_base_anchors(scale, ratio)) for scale, ratio in zip(scales, ratios)]
  File "/home/zhengjunfeng/megengine-retinanet/layers/det/anchor.py", line 98, in <listcomp>
    return [tensor(self.generate_base_anchors(scale, ratio)) for scale, ratio in zip(scales, ratios)]
  File "/home/zhengjunfeng/.local/lib/python3.6/site-packages/megengine/tensor.py", line 52, in __new__
    obj = _Tensor.__new__(cls, data, dtype, cn, is_const, no_cache)
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
其中加黑部分是我的网络初始化代码

**Comment by wllvcxz** [comment]
看报错信息应该是主进程初始化完cuda之后又进行了fork (FYI: [link](https://stackoverflow.com/questions/22950047/cuda-initialization-error-after-fork))，请确认一下"测试模型1"是不是在主进程里进行的，然后"训练模型2"fork了一些进程并在这些子进程里调用了cuda。如果是的话，可以尝试把"测试模型1"放到子进程里做，避免在主进程里初始化cuda。

**Comment by ustbzjf1** [comment]
对的，按照你的提示，把测试放到子进程里面执行就没事了

**Comment by ustbzjf1** [comment]
不过很奇怪的是用megbrain的时候没有出现过这种问题，不知道后面有没有可能把这个地方优化一下

**Comment by wllvcxz** [comment]
> 不过很奇怪的是用megbrain的时候没有出现过这种问题，不知道后面有没有可能把这个地方优化一下

megbrain是单进程运行的，所以不会有这个问题。 近期会发布v1.5版本，会改善报错信息，让报错更加明确，可以关注一下。
