### ISSUE TITLE
使用 30 系卡需要等待非常久时间才行

### ISSUE THREAD

**Issue by rfslzy** [MegEngine/MegEngine#204]
使用MegEngine，无论是调用conv2d，还是调用简单的megengine.tensor都需要极其长的时间等待（半小时以上），其任务没有使用网络，但是内存和CPU占用都很高，这是为什么呢？
## 环境
1.系统环境：windows 10 20H2 19042.1165
2.MegEngine版本：1.5
3.python版本：3.7.10

## 复现步骤
1.使用python
2.创建列表
3.将列表变为tensor（陷入等待）

## 请提供关键的代码片段便于追查问题
python
import megengine as mge
a = [1,2,3,4]
b = mge.tensor(a)  # 陷入漫长等待，但最后可以出结果

## 请提供完整的日志及报错信息
没有报错，但是每次等待时间都极其漫长
<img width="506" alt="1" src="https://user-images.githubusercontent.com/86888207/131056792-c58c5c1d-ce89-4abe-8fdb-dd4dd628b63d.PNG">

![2](https://user-images.githubusercontent.com/86888207/131056817-a09ae6cb-7284-4526-97f3-5145172a3803.png)

**Comment by xxr3376** [comment]
Already support CUDA11 after v1.11.0
