### ISSUE TITLE
BUG Issue

### ISSUE THREAD

**Issue by cuge1995** [MegEngine/MegEngine#206]
when `./scripts/cmake-build/host_build.sh -c`

```
cmake/cudnn.cmake:31 (message):
  Can not find CuDNN Library
```

**Comment by youzhedian** [comment]
应该是还没安装cuda环境？可以阅读该脚本同目录下的BUILD_README.md文档，根据实际编译平台类型完成对应的prepare操作

**Comment by cuge1995** [comment]
有cuda环境的

**Comment by haolongzhangm** [comment]
cuda 三件套，env 设置，参考： https://github.com/MegEngine/MegEngine/blob/master/scripts/whl/BUILD_PYTHON_WHL_README.md

```
export CUDA_ROOT_DIR=/path/to/cuda
export CUDNN_ROOT_DIR=/path/to/cudnn
export TENSORRT_ROOT_DIR=/path/to/tensorrt
```


嗯， 感觉这点env 应该迁移到 https://github.com/MegEngine/MegEngine/blob/master/scripts/cmake-build/BUILD_README.md


more info: 
当一些env 发生变更或者新增后， 建议把build目录的CMakecache.txt 删除一下， 或者./scripts/cmake-build/host_build.sh 后面加一个-r
