### ISSUE TITLE
Hang on std::call_once when loading model with GPU which may due to a bug in stdlibc++

### ISSUE THREAD

**Issue by MarsTechHAN** [MegEngine/MegEngine#212]
## 环境
1.系统环境：
* Ubuntu 20.04.2 LTS x86_64 
* GLIBCXX: 3.4.28 (libstdc++.so.6.0.28)
* GPU:
![image](https://user-images.githubusercontent.com/10462805/133961357-2b17d448-c680-4cac-8fc9-76db9f17a417.png)

2.MegEngine版本：1.6.0rc1
3.python版本：Python 3.8.10

The program stuck at **net.load** when I was trying to use the MegFlow. I wait for more than 10min and there is no sign of finishing it.

```python3
device_type = mgelite.LiteDeviceType.LITE_CUDA #It will work under CPU, but not CUDA

net_config = mgelite.LiteConfig(device_type=device_type)
ios = mgelite.LiteNetworkIO()
ios.add_input(mgelite.LiteIO("data", is_host=True))
# ios.add_input(LiteIO("idx", is_host=True))
# ios.add_input(LiteIO("roi", is_host=True))

net = mgelite.LiteNetwork(config=net_config, io=ios)
net.device_id = device_id

print('Start loading model...')
net.load(path)
print('Load model succ.')

...
```

![8R$MJC(@M UJ1G0FV U}DIF](https://user-images.githubusercontent.com/10462805/133960953-509da233-a534-4f4e-a9a1-03d6ac5163dc.png)

When it stuck at the loading, the program using 100% on one cpu thread, so I thought it might be something related to the threading, and I tried 
```bash
gdb --args python3 lite.py -c ../../models/cat_finder_models/yolox_s.mge
```
and broke when it stuck for over 5 seconds.
![image](https://user-images.githubusercontent.com/10462805/133961002-01da0b67-ee48-4fc5-b2fe-e549f7ac090a.png)

The function called_once was only used for GPU in **cusolver_handle**. I was able to load the model smoothly when I set the device type to CPU: (the Tensorflow and Pytorch run ok on my machine, so I dont think it was cuda.)
```c++
device_type = mgelite.LiteDeviceType.LITE_CPU;
```

After some search and digging inside the megengine, I find this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66146, which I think maybe related to what is going on.

I attached my stdlibc++ file which is what system shipped with, maybe you can test in a docker :p
[libstdc++.so.6.0.28.zip](https://github.com/MegEngine/MegEngine/files/7193765/libstdc%2B%2B.so.6.0.28.zip)

**Comment by MarsTechHAN** [comment]
I think the #204 is kind of related to what I am facing. 

To proof the program is doing nothing, I ran a strace, and indeed, the program stuck at **FUTEX_WAIT**.
```
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffd091e4bf0) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffd091e4c60) = 0
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffd091e4c60) = 0
clone(child_stack=0x7f4f6278cfb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[3881490], tls=0x7f4f6278d700, child_tidptr=0x7f4f6278d9d0) = 3881490
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
futex(0x7f4f6278d9d0, FUTEX_WAIT, 3881490, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
futex(0x7f4f6278d9d0, FUTEX_WAIT, 3881490, NULL
```

**Comment by MarsTechHAN** [comment]
To further further prove this is not a CUDA issue. I installed the MegEngine built with CUDA11.2, and it is still not working as expected.
![image](https://user-images.githubusercontent.com/10462805/133962863-086b4b80-9285-4895-886b-b36624e7c3b5.png)
![image](https://user-images.githubusercontent.com/10462805/133962908-cee9c9cc-9f2a-44a9-88e6-819dcc492300.png)

**Comment by xxr3376** [comment]
Yes you are right, it does related with #204. It doesn't stuck, it just compiling PTX for your GPU.

For some legal reasons (EAR limit for megvii), we can't provide you prebuilt CUDA11 binary or settings for now. You may need to change [these lines](https://github.com/MegEngine/MegEngine/blob/master/CMakeLists.txt#L563) to make cuda compile proper binary code for you 30xx series GPU. Any contribution is welcomed!

**Comment by xxr3376** [comment]
@MarsTechHAN Here's some tips about CUDA support for 30xx series GPU card for you https://discuss.megengine.org.cn/t/topic/1106
