### ISSUE TITLE
关于megengine.data.dataset.ImageNet的解压路径设置

### ISSUE THREAD

**Issue by Asthestarsfalll** [MegEngine/MegEngine#217]
在MegStudio中使用挂载的ImageNet数据集时，似乎会将文件直接解压在当前文件夹，然而挂载的文件夹被设置为只读，希望能够设置解压的路径
![image](https://user-images.githubusercontent.com/72954905/135386759-9305cd7d-d855-42f4-8769-c30b55476cb6.png)

**Comment by qq332982511** [comment]
可以把挂载的数据集拷贝或链接到可写目录来绕过...

**Comment by Asthestarsfalll** [comment]
> 可以把挂载的数据集拷贝或链接压缩包到可写目录来绕过...

但是就给了100g的空间，复制过来塞不下，软链接也不行

**Comment by qq332982511** [comment]
完整的imagenet数据集解压出来会超过100G，如果你挂载的imagenet数据只是tar包，那一定需要一个大于100G的可写目录来解压。
建议挂载一个已经解压好的数据集，或者扩展可写空间

**Comment by qq332982511** [comment]
问了一下，预计10月中旬会上线解压版本imagenet数据集
