### ISSUE TITLE
megengine.functional.mul

### ISSUE THREAD

**Issue by MegChai** [MegEngine/MegEngine#251]
该 API 为 MegEngine Tensor 生成操作相关的 API, 对应文档页面在 [megengine.functional.mul](https://megengine.org.cn/doc/stable/zh/reference/api/megengine.functional.mul.html)

请按照 《[Python 文档字符串风格指南](https://megengine.org.cn/doc/stable/zh/development/docs/python-docstring-style-guide.html)》中的说明进行改进。

**Comment by MegChai** [comment]
GitHub 限制，@ErikQQY 需要在这个 Issue 下做个简单回复，才能被 Assign.

**Comment by ErikQQY** [comment]
Hello, 正在修改
