### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [MegEngine/MegEngine#27]
Would you like to [wrap any pointers](https://github.com/MegEngine/MegEngine/blob/b938b1cf3cd50cf46a746d416824bd0d3e70060a/dnn/src/common/cv/mat.cpp#L112 "Update candidate: Mat<T>::equals()") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by windreamer** [comment]
Hi @elfring 

I think this is an improvement should be well considered. But these `Mat<T>::equals` are mainly used in test cases. We are evaluating the impact of exception safety in these cases.

Thank you for your kind suggestion.

**Comment by xxr3376** [comment]
Fixed in 944a125c68cea8798b8e195fa138ae68ef8eb2c9.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/MegEngine/MegEngine/commit/944a125c68cea8798b8e195fa138ae68ef8eb2c9 "Usage of two smart pointers").

Would you like to improve the software another bit?
