### ISSUE TITLE
修了几处英文文档错误

### ISSUE THREAD

**Issue by hookex** [MegEngine/MegEngine#31]
## 文档链接
https://github.com/MegEngine/MegEngine/pull/23/files

## 问题描述
修了几处英文文档错误

**Comment by megvii-mge** [comment]
您好，我们正在全力构建此开源项目的 CI，并准备 CLA 签署系统，在此之前此 MR 暂时不能合并，我们预计会在 4.15 左右完成这些工作。非常感谢您的贡献，也请您持续关注 MegEngine 项目

**Comment by ChaiMind** [comment]
该问题将转入 #23 页面处理，因此关闭此 Issue.
