### ISSUE TITLE
程序无法正常退出（CPU速度是pytroch9倍）

### ISSUE THREAD

**Issue by zihaozhang9** [MegEngine/MegEngine#32]
首先，惊叹MegEngine的速度。从torchvision拷贝个resnet18在cpu测试，MegEngine是pytorch速度的9倍。这个速度比opencv还快，opencv大概是pytroch的4倍。
但是，我运行程序后发现可能无法正常退出。
![image](https://user-images.githubusercontent.com/21007783/77729280-3c93fe00-7039-11ea-81a2-8804a7e2af94.png)

环境
ubuntu 
没有GPU
megengine 0.3.1 
我的代码：
```
import megengine as mge
import megengine.module as M
import cv2
import numpy as np
import megengine.functional as F
def conv3x3(in_planes, out_planes, stride=1, groups=1, dilation=1):
    """3x3 convolution with padding"""
    return M.Conv2d(in_planes, out_planes, kernel_size=3, stride=stride,
                     padding=dilation, groups=groups, bias=False, dilation=dilation)


def conv1x1(in_planes, out_planes, stride=1):
    """1x1 convolution"""
    return M.Conv2d(in_planes, out_planes, kernel_size=1, stride=stride, bias=False)


class BasicBlock(M.Module):
    expansion = 1

    def __init__(self, inplanes, planes, stride=1, downsample=None, groups=1,
                 base_width=64, dilation=1, norm_layer=None):
        super(BasicBlock, self).__init__()
        if norm_layer is None:
            norm_layer = M.BatchNorm2d
        if groups != 1 or base_width != 64:
            raise ValueError('BasicBlock only supports groups=1 and base_width=64')
        if dilation > 1:
            raise NotImplementedError("Dilation > 1 not supported in BasicBlock")
        # Both self.conv1 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv3x3(inplanes, planes, stride)
        self.bn1 = norm_layer(planes)
        self.relu = M.ReLU()
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = norm_layer(planes)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out


class ResNet(M.Module):

    def __init__(self, block, layers, num_classes=1000, zero_init_residual=False,
                 groups=1, width_per_group=64, replace_stride_with_dilation=None,
                 norm_layer=None):
        super(ResNet, self).__init__()
        if norm_layer is None:
            norm_layer = M.BatchNorm2d
        self._norm_layer = norm_layer

        self.inplanes = 64
        self.dilation = 1
        if replace_stride_with_dilation is None:
            # each element in the tuple indicates if we should replace
            # the 2x2 stride with a dilated convolution instead
            replace_stride_with_dilation = [False, False, False]
        if len(replace_stride_with_dilation) != 3:
            raise ValueError("replace_stride_with_dilation should be None "
                             "or a 3-element tuple, got {}".format(replace_stride_with_dilation))
        self.groups = groups
        self.base_width = width_per_group
        self.conv1 = M.Conv2d(3, self.inplanes, kernel_size=7, stride=2, padding=3,
                               bias=False)
        self.bn1 = norm_layer(self.inplanes)
        self.relu = M.ReLU()
        self.maxpool = M.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2,
                                       dilate=replace_stride_with_dilation[0])
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2,
                                       dilate=replace_stride_with_dilation[1])
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2,
                                       dilate=replace_stride_with_dilation[2])
                                              
        
        self.avgpool = M.AvgPool2d((7,7))#M.AdaptiveAvgPool2d((1, 1))
        self.fc = M.Linear(512 * block.expansion, num_classes)

        #for m in self.modules():
        #    if isinstance(m, M.Conv2d):
        #        M.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
        #    elif isinstance(m,M.BatchNorm2d):
        #        M.init.constant_(m.weight, 1)
        #        M.init.constant_(m.bias, 0)

        # Zero-initialize the last BN in each residual branch,
        # so that the residual branch starts with zeros, and each residual block behaves like an identity.
        # This improves the model by 0.2~0.3% according to https://arxiv.org/abs/1706.02677
        if zero_init_residual:
            for m in self.modules():
                if isinstance(m, Bottleneck):
                    M.init.constant_(m.bn3.weight, 0)
                elif isinstance(m, BasicBlock):
                    M.init.constant_(m.bn2.weight, 0)

    def _make_layer(self, block, planes, blocks, stride=1, dilate=False):
        norm_layer = self._norm_layer
        downsample = None
        previous_dilation = self.dilation
        if dilate:
            self.dilation *= stride
            stride = 1
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = M.Sequential(
                conv1x1(self.inplanes, planes * block.expansion, stride),
                norm_layer(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample, self.groups,
                            self.base_width, previous_dilation, norm_layer))
        self.inplanes = planes * block.expansion
        for _ in range(1, blocks):
            layers.append(block(self.inplanes, planes, groups=self.groups,
                                base_width=self.base_width, dilation=self.dilation,
                                norm_layer=norm_layer))

        return M.Sequential(*layers)

    def _forward_impl(self, x):
        # See note [TorchScript super()]
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = F.flatten(x, 1)
        x = self.fc(x)

        return x

    def forward(self, x):
        return self._forward_impl(x)


def _resnet(arch, block, layers, pretrained, progress, **kwargs):
    model = ResNet(block, layers, **kwargs)
    if pretrained:
        state_dict = load_state_dict_from_url(model_urls[arch],
                                              progress=progress)
        model.load_state_dict(state_dict)
    return model


def resnet18(pretrained=False, progress=True, **kwargs):
    r"""ResNet-18 model from
    `"Deep Residual Learning for Image Recognition" <https://arxiv.org/pdf/1512.03385.pdf>`_
    Args:
        pretrained (bool): If True, returns a model pre-trained on ImageNet
        progress (bool): If True, displays a progress bar of the download to stderr
    """
    return _resnet('resnet18', BasicBlock, [2, 2, 2, 2], pretrained, progress,
                   **kwargs)

def test_fps():
    model = resnet18()
    model.eval()
    x = mge.tensor(np.random.randn(1, 3, 224, 224).astype(np.float32))
    count = 0
    t0 = cv2.getTickCount()
    while True:
        count+=1
        model(x)
        if count>100:break
    t = (cv2.getTickCount()-t0)/cv2.getTickFrequency()
    fps = (1.0 / t)*count;
    print(fps)
                   
if __name__ == "__main__":
    model = resnet18()
    model.eval()
    x = mge.tensor(np.random.randn(1, 3, 224, 224).astype(np.float32))
    out = model(x)
    print(out.shape)  
    test_fps()
```

**Comment by zihaozhang9** [comment]
顺便。MegEngine也非常好上手。不过好像没有[AdaptiveAvgPool2d](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L157)层。

**Comment by megvii-mge** [comment]
您好，非常感谢您对 MegEngine 项目的关注和支持，我们在 cpu 环境下运行您提供的代码，可以正常退出，还请您进一步看一下程序 block 在哪里。也非常欢迎您加入到 MegEngine 的开发中来，增加更多实用的功能 ：）

**Comment by xieliang11111** [comment]
Traceback (most recent call last):
  File "inference.py", line 97, in <module>
    main()
  File "inference.py", line 40, in main
    model = getattr(M, args.arch)(pretrained=(args.model is None))
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/megengine/hub/hub.py", line 316, in pretrained_model_func
    model = func(**kwargs)
  File "/home/xieliang/project_xieliang/framework/megengine/Models/official/vision/classification/resnet/model.py", line 311, in resnet18
    return ResNet(BasicBlock, [2, 2, 2, 2], **kwargs)
  File "/home/xieliang/project_xieliang/framework/megengine/Models/official/vision/classification/resnet/model.py", line 183, in __init__
    3, self.in_channels, kernel_size=7, stride=2, padding=3, bias=False
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/megengine/module/conv.py", line 159, in __init__
    bias,
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/megengine/module/conv.py", line 52, in __init__
    self.weight = Parameter(np.zeros(self._infer_weight_shape(), dtype=np.float32))
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/megengine/core/tensor_nn.py", line 28, in __init__
    t = tensor(value, dtype=dtype, device=device, requires_grad=requires_grad)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/megengine/core/tensor.py", line 517, in tensor
    shared_nd = mgb.make_shared(device, value=data, dtype=dtype)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/megengine/_internal/__init__.py", line 115, in make_shared
    comp_node = _detail.as_comp_node(comp_node)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/megengine/_internal/mgb.py", line 966, in as_comp_node
    return CompNode_load(desc)
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::AssertionError
assertion `locator.device >= 0 && locator.device < nr_gpu' failed at /home/code/src/core/impl/comp_node/cuda/comp_node.cpp:609: static mgb::CompNode::Impl* mgb::CudaCompNode::load_cuda(const mgb::CompNode::Locator&, const mgb::CompNode::Locator&)
extra message: request gpu0 out of valid range [0, 0)
+ bt:/usr/local/python3.7.5/lib/python3.7/site-packages/megengine/_internal/_mgb.cpython-37m-x86_64-linux-gnu.so{1bd7df2,1be533d,1bd8f48,1b03f44}
调用GPU推理GPU设置正确，为什么一直显示GPU没在范围内？

**Comment by xieliang11111** [comment]
（１）resnet18		单张图片（ms）
============== time:0.10605716705322266 ==============
0: class = lynx                 with probability = 25.2 %
1: class = Siamese_cat          with probability = 12.3 %
2: class = Egyptian_cat         with probability =  8.7 %
3: class = Persian_cat          with probability =  8.3 %
4: class = tabby                with probability =  6.5 %
为什么我在CPU上推理单张图片是0.1ms，这个应该有问题？

**Comment by xxr3376** [comment]
请尝试手动调用 is_cuda_available 判断是否正确配置了 CUDA。
https://megengine.org.cn/doc/latest/autogen/megengine.core.html?highlight=cuda#megengine.core.device.is_cuda_available

**Comment by xieliang11111** [comment]
手动调用显示false, 我cuda配置都是正确的，请问还有哪里需要修改。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xinran Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 下午4:01
收件人:&nbsp;"MegEngine/MegEngine"<MegEngine@noreply.github.com&gt;;
抄送:&nbsp;"735944309"<735944309@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MegEngine/MegEngine] 程序无法正常退出（CPU速度是pytroch9倍） (#32)





 
请尝试手动调用 is_cuda_available 判断是否正确配置了 CUDA。
 https://megengine.org.cn/doc/latest/autogen/megengine.core.html?highlight=cuda#megengine.core.device.is_cuda_available

**Comment by xxr3376** [comment]
@xieliang11111 请检查是否满足官网上说的：`Nvidia驱动版本： 418.39及以上`，以及`CUDA®计算能力： 5.2及以上`

另外可以检查一下 `LD_LIBRARY_PATH` 是否包含 NVIDIA驱动的 /lib64 目录

**Comment by xieliang11111** [comment]
那在请问下GPU上推理速度，跟TF和Pytorch对比，有没有测试对比数据可以发出了解下。

**Comment by ChaiMind** [comment]
该问题似乎已经解决（更新驱动和 CUDA 版本），因此该 Issue 将被关闭。

> 那在请问下GPU上推理速度，跟TF和Pytorch对比，有没有测试对比数据可以发出了解下。

如果有新类型的问题，请在另外的新 Issue 页面讨论。
