### ISSUE TITLE
pip安装无法使用

### ISSUE THREAD

**Issue by fantadominator** [MegEngine/MegEngine#33]
## 环境
1.系统环境：Ubuntu 19.04 (GNU/Linux 5.0.0-38-generic x86_64)
2.MegEngine版本：默认版本
3.python版本：3.7
4.pip版本：**20.0**

## 复现步骤
1.pip3 install megengine -f https://megengine.org.cn/whl/mge.html
2.import megengine as mge

## 报错信息：ValueError
This is an placeholder only, please install by 'pip3 install megengine -f https://megengine.org.cn/whl/mge.html'. Please make sure your pip version is higher than 19.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/frb/.local/lib/python3.7/site-packages/megengine/__init__.py", line 3, in <module>
    raise ValueError("This is an placeholder only")
ValueError: This is an placeholder only
##追加##
翻看issues后发现相同的问题，按照提示将pip升为version=20.0 后仍然出现此问题

**Comment by megvii-mge** [comment]
您好，请您升级 pip 版本之后先 uninstall 再重新 install 试一下

**Comment by fantadominator** [comment]
尝试过了，最后发现原本的pip版本就是20.0

**Comment by fantadominator** [comment]
> 您好，请您升级 pip 版本之后先 uninstall 再重新 install 试一下

尝试过了，最后发现原本的pip版本就是20.0

**Comment by megvii-mge** [comment]
> > 您好，请您升级 pip 版本之后先 uninstall 再重新 install 试一下
> 
> 尝试过了，最后发现原本的pip版本就是20.0

您好，您试一下增加 --no-cache-dir 选项，看看能不能下载到正确的 whl 包

pip3 install megengine -f https://megengine.org.cn/whl/mge.html --no-cache-dir

**Comment by RyuGuo** [comment]
> > > 您好，请您升级 pip 版本之后先 uninstall 再重新 install 试一下
> > 
> > 
> > 尝试过了，最后发现原本的pip版本就是20.0
> 
> 您好，您试一下增加 --no-cache-dir 选项，看看能不能下载到正确的 whl 包
> 
> pip3 install megengine -f https://megengine.org.cn/whl/mge.html --no-cache-dir

我在使用了您这个方法后依然没有解决这个问题。我的系统配置是这样的：Linux Ubuntu 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:19 UTC 2019 i686 i686 i686 GNU/Linux，使用的Python版本是3.7.7。

**Comment by xxr3376** [comment]
@RyuGuo 请问你遇到的情况是`This is an placeholder only` 还是根本无法安装呢？

另外请确认一下运行的那个 pip3 确实是 3.7.7 python 的 pip，如果不确定可以通过 `python3 -m pip ...` 的方式来运行

**Comment by xxr3376** [comment]
Close due to inactive.
