### ISSUE TITLE
fusion pass typo

### ISSUE THREAD

**Issue by Joejiong** [MegEngine/MegEngine#34]
## 文档链接
https://github.com/MegEngine/MegEngine/blob/master/src/jit/impl/fusion_pass.cpp

## 问题描述

MegEngine/src/jit/impl/fusion_pass.cpp
function name typo for all "generator" related name.
e.g you wrote the following: 

bool test_all_readers_in_the_graph(VarNode* var,
                                       InternalGraph**_Genrator_*** i_graph);

**Comment by megvii-mge** [comment]
Thank you very much for pointing out this mistake. We will correct it in the next version : )

**Comment by Joejiong** [comment]
very interesting project keep going.

**Comment by ChaiMind** [comment]
This typo has been fixed in commit 5fe7cd1457e03431f02b87613250e4c975bbea40 .

Thank you very much again and we will close the issue now.
