### ISSUE TITLE
请问是否支持sync bn?

### ISSUE THREAD

**Issue by wangli1426** [MegEngine/MegEngine#36]
RT. 谢谢

**Comment by xxr3376** [comment]
目前的开源版本尚不支持，Sync BN 已经记录在我们的需求列表当中，后续会排期支持。
FYI @qliu93

**Comment by Randolph87xxx** [comment]
现在已经加入了sync bn，commit链接如下

https://github.com/MegEngine/MegEngine/commit/40412e2688a96f018851b08945659bd5ca1bfa13
