### ISSUE TITLE
希望支持megengine.where直接返回坐标

### ISSUE THREAD

**Issue by CVWangZH** [MegEngine/MegEngine#384]
## 背景
从heatmap中取出大于阈值的坐标，尝试使用MegEngine算子[megengine.functional.where](https://megengine.org.cn/doc/stable/zh/reference/api/megengine.functional.where.html?highlight=where#megengine.functional.where)但是不支持直接返回坐标，比如有x和y（对齐np.where和torch.where可以直接返回坐标）。没有找到其他合适的算子。

## 任务描述
megengine.functional.where 希望支持可以不传入x, y，仅传入condition，直接返回符合条件的坐标。或者是否有满足以上需求的算子

## 目标
megengine.where对齐np.where和torch.where

**Comment by xxr3376** [comment]
你可能想要的是 [megengine.functional.cond_take](https://megengine.org.cn/doc/stable/zh/reference/api/megengine.functional.cond_take.html)

**Comment by MegChai** [comment]
@CVWangZH 能不能请教一下，为什么之前没有发现 `cond_take`, 文档这块如何改进可以更方便你找到想要的 API 呢？

**Comment by CVWangZH** [comment]
> @CVWangZH 能不能请教一下，为什么之前没有发现 `cond_take`, 文档这块如何改进可以更方便你找到想要的 API 呢？

我在做框架迁移，pytorch代码里面使用的算子是torch.where，于是我在文档里面找到了如下对应关系：
![image](https://user-images.githubusercontent.com/50662995/140003912-a5c604e4-4750-42b9-be1f-869df03d7ee8.png)

```
megengine.where -> torch.where
megengine.cond_take -> torch.take
```

* where的功能并不是完全对齐，实际上是torch.where对齐megengine.where+megengine.cond_take，这里是否可以增加注释说明
* torch.take、np.take和megengine.cond_take的接口也并不是对齐的，这里的对比不知道是否合适

**Comment by MegChai** [comment]
> where的功能并不是完全对齐 

@CVWangZH 感谢反馈，很有益的信息！ 😄 

实际上 MegEngine 中 Functional 的 API 设计并不是完全参照 NumPy 和 Pytorch 的实现去做的，在  [MEP 3](https://megengine.org.cn/doc/stable/zh/development/meps/mep-0003.html#mep-0003) 中规定应当以《数组 API 标准》作为参考实现，因此实际上  `functional.where` 的参考实现应当是：

https://data-apis.org/array-api/latest/API_specification/searching_functions.html#where-condition-x1-x2

![image](https://user-images.githubusercontent.com/21091736/140010154-e3f7eab7-1b73-46b3-9136-c9e2ecf3d092.png)

从这个层面看，实现是对齐的。不过在满足《数组 API 标准》后是否要对 `where` 的功能进行扩充，还有待商议。

![image](https://user-images.githubusercontent.com/21091736/140010323-e25b6e7b-aee2-426c-ac77-c78aa357432c.png)


你是否有意愿去修改一下这个对比表格的内容，贡献一下 PR 呢？

* 源文件地址：https://github.com/MegEngine/Documentation/blob/main/source/reference/comparison.rst
* 文档贡献指南：https://megengine.org.cn/doc/stable/zh/development/contribute-to-docs/index.html
