### ISSUE TITLE
Feature Request: 类似torch.diag的算子

### ISSUE THREAD

**Issue by hiyyg** [MegEngine/MegEngine#385]
torch.diag能将一个向量转化为对角阵，也能取矩阵的某一对角线的元素。尽管这可以用一些操作例如F.eye, F.cond_take组合，但感觉并不是很直观，而且不一定高效。

## 背景

基本算子，涉及很多场景

**Comment by dzy97** [comment]
我们会在下个版本支持这个算子～

**Comment by xxr3376** [comment]
Already supported in v1.10.1
Check here: https://www.megengine.org.cn/doc/stable/zh/reference/api/megengine.functional.diag.html?highlight=diag#megengine.functional.diag
