### ISSUE TITLE
error when building from source

### ISSUE THREAD

**Issue by YuejiYang** [MegEngine/MegEngine#39]
## 环境
1.系统环境：ubuntu 16
2.MegEngine版本：current version
3.python版本：3.6

## 复现步骤
1.
2.
3.

## 请提供完整的日志及报错信息
/home/yjyang/test-MegEngine/MegEngine/third_party/intel-mkl-dnn/src/cpu/nspc_batch_normalization.cpp: In lambda function:
/home/yjyang/test-MegEngine/MegEngine/third_party/intel-mkl-dnn/src/cpu/nspc_batch_normalization.cpp:386:10: error: ‘simdlen’ is not valid for ‘#pragma omp simd’
                 PRAGMA_OMP_SIMD(SIMD_LEN_16)
          ^
src/cpu/CMakeFiles/dnnl_cpu.dir/build.make:1574: recipe for target 'src/cpu/CMakeFiles/dnnl_cpu.dir/nspc_batch_normalization.cpp.o' failed
make[5]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/nspc_batch_normalization.cpp.o] Error 1
CMakeFiles/Makefile2:276: recipe for target 'src/cpu/CMakeFiles/dnnl_cpu.dir/all' failed
make[4]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/all] Error 2
Makefile:157: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/mkl_dnn.dir/build.make:128: recipe for target 'third_party/intel-mkl-dnn/src/mkl_dnn-stamp/mkl_dnn-build' failed
make[2]: *** [third_party/intel-mkl-dnn/src/mkl_dnn-stamp/mkl_dnn-build] Error 2
CMakeFiles/Makefile2:356: recipe for target 'CMakeFiles/mkl_dnn.dir/all' failed
make[1]: *** [CMakeFiles/mkl_dnn.dir/all] Error 2
Makefile:168: recipe for target 'all' failed
make: *** [all] Error 

Any clue what causes this problem??
Thank you!

**Comment by xxr3376** [comment]
请提供一下您的 gcc 版本，谢谢。

**Comment by YuejiYang** [comment]
gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by xxr3376** [comment]
@YuejiYang 你的 gcc 版本过低了，请尝试升到 gcc7 或以上试试，最低的版本我们尚未确定。
