### ISSUE TITLE
Bug Issue：module 'megengine.functional.nn' has no attribute 'pad'

### ISSUE THREAD

**Issue by Asthestarsfalll** [MegEngine/MegEngine#390]
## 环境
1.系统环境：win11
2.MegEngine版本：1.6.0
3.python版本：3.7.1

## 复现步骤
![image](https://user-images.githubusercontent.com/72954905/141741331-df20044b-49dd-41c3-8c87-dc71c17be568.png)

**Comment by chen-2569** [comment]
你好，可以试试看卸载重新安装一下megengine，
python3 -m pip uninstall megengine
python3 -m pip install --upgrade pip
python3 -m pip install megengine -f https://megengine.org.cn/whl/mge.html

**Comment by Asthestarsfalll** [comment]
> 

还是不行呢

**Comment by haolongzhangm** [comment]
megengine.functional.nn.pad only support from next version (1.7)

**Comment by Asthestarsfalll** [comment]
> 

好的，但是我在linux系统上确实可以在1.6版本使用pad

**Comment by haolongzhangm** [comment]
@Asthestarsfalll 是的， 因为1.6 版本出包出了一点小插曲，导致Windows 1.6 没有包含相应的提交，

但是原则上，我们不重新上传包， 所以对windows而言， 这个提交就只能体现在1.7了， 请谅解

对你的需求而言， windows上想使用这个pad， 有两个方法：
* 等我们发1.7
* 参考 scripts/whl/BUILD_PYTHON_WHL_README.md  ， 基于最新的master 自己构建一个whl包

**Comment by Asthestarsfalll** [comment]
@haolongzhangm 好的，感谢！
