### ISSUE TITLE
是否有用CPU版的二进制文件安装包？

### ISSUE THREAD

**Issue by AsakusaRinne** [MegEngine/MegEngine#392]
## 背景

想在只有CPU的计算机上运行MegEngine，有没有不build from source的方法呢？

## 任务描述

平台：x86_64
系统：Ubuntu20.04 LTS
Python版本：3.8

但是直接```pip install megengine```并在对应环境下启动python，运行```import megengine```的时候，出现以下信息：

```
err: Failed to load cuda API library
err: failed to load cuda func: cuCtxGetCurrent
```

## 目标

安装cpu版本的Megengine

**Comment by qq332982511** [comment]
找不到cuda的情况下应该会默认用cpu, 现在是会崩溃吗？

**Comment by haolongzhangm** [comment]
@AsakusaRinne  
1: 目前官方发布的包，是支持CUDA的，但是 cpu only 的环境， 会自动回退到CPU 版本
2: 如果你自己确实想build from src cpu 版本， 请参考：  https://github.com/MegEngine/MegEngine/blob/master/scripts/whl/BUILD_PYTHON_WHL_README.md 

里面会告诉怎么自己编译CPU only 的版本

**Comment by AsakusaRinne** [comment]
如@qq332982511和@haolongzhangm所说，找不到cuda会自动回退成使用CPU，刚才又试了一下，是可以跑通的，是我的问题，昨天看到```import megengine```都报了err，就没有继续往下尝试。

但是这个地方如果找不到CUDA，改成报一个Warning是不是比较好一些？许多人在自己的python环境下安装了新的包，想要验证是否安装成功，都会打开python命令行然后import使用一下试试，这时候报了error感觉容易造成误会。

**Comment by qq332982511** [comment]
可以把err改成wrn，后面再补上说明。比如`wrn: Failed to load cuda API library, If you need cuda, this is a error. If you only use cpu, ignore it. `

**Comment by haolongzhangm** [comment]
> 可以把err改成wrn，后面再补上说明。比如`wrn: Failed to load cuda API library, If you need cuda, this is a error. If you only use cpu, ignore it. `

@qq332982511  不错的建议， 方便的话，帮忙提一个PR 改进一下这个log ， 文件在： dnn/cuda-stub/src/dlopen_helper.h
