### ISSUE TITLE
MegEngine会在/tmp/路径下创建大量mge_plasma_*的文件

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#394]
## 环境
1.系统环境：Ubuntu 18.04.5
2.MegEngine版本：1.6.0
3.python版本：3.7.10

## 现象:
如下图所示，在/tmp文件夹下出现了大量的mge_plasma_开头的空文件
![image](https://user-images.githubusercontent.com/36066805/142788518-5b641d60-33b0-4c3e-8a5c-acb5d2ad6b37.png)

**Comment by CeryZhai** [comment]
这个是因为  pyarrow的对象存储会建立一个 协议 链接的 协议是 file:// ,  在执行多机的时候，对于每个卡 会建立1个 对象存储的头，默认会删除的，如果异常中断的话不会删除，它的大小是空的，只占一个inode，基本不影响任何，如果觉得有问题可以手动删除它们...

**Comment by Qsingle** [comment]
谢谢，应该是num_worker开的比较大，是不是异常退出导致的

**Comment by CeryZhai** [comment]
> 谢谢，应该是num_worker开的比较大，是不是异常退出导致的

目前看下来，异常退出经常是在做多机通信的时候 oom 或者 其他问题退出，然而，由于 plasma queue是共享内存队列，导致某些进程退出，某些尚未退出，megengine 并不能清空正在被使用的队列，所导致

**Comment by Qsingle** [comment]
疑问已解答
