### ISSUE TITLE
dtype 参数不支持 int 和 float

### ISSUE THREAD

**Issue by Olalaye** [MegEngine/MegEngine#406]
## 环境
1.系统环境：MegStudio
2.MegEngine版本：1.6.0
3.python版本：Python 3.7

## 复现步骤
1.
```python
import megengine.functional as F

F.full((2, 2), 1.0, dtype=int)
```
当``dtype``为`'int8'` 或 `'float32'`等字符串类型，表现正常，当``dtype``为 ``int``或 `float`等Python基本数据类型时，报错。

为``bool``时，也正常。

## 请提供完整的日志及报错信息
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_166/2211199313.py in <module>
----> 1 F.full((2, 2), 1.0, dtype=int)

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/functional/tensor.py in full(shape, value, dtype, device)
    134     if device is None:
    135         device = get_default_device()
--> 136     (x,) = Const(value, dtype=dtype, device=device)()
    137     if shape is ():  # scalar.shape
    138         return x

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/core/ops/special.py in __call__(self, *reference)
     38                 return (rst,)
     39 
---> 40         return (Tensor(self.value, self.dtype, self.device, True),)

~/.miniconda/envs/xuan/lib/python3.7/site-packages/megengine/tensor.py in __new__(cls, data, dtype, device, is_const, no_cache, name)
     72                 if 0 in data.strides:
     73                     data = data.squeeze().reshape(data.shape)
---> 74             obj = _Tensor.__new__(cls, data, dtype, cn, is_const, no_cache, name)
     75         return obj
     76 

RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

**Comment by daisycx** [comment]
MegEngine中的`tensor`数据类型 期望是个 `np.dtype`，可以传字符串或者 `np.int32` 之类：
https://github.com/MegEngine/MegEngine/blob/master/imperative/python/megengine/tensor.py#L47
python中的int可以有任意精度，具体差异可参考：
https://stackoverflow.com/questions/21851985/difference-between-np-int-np-int-int-and-np-int-t-in-cython

**Comment by MegChai** [comment]
你可能需要参考这个页面：https://megengine.org.cn/doc/stable/zh/user-guide/model-development/tensor/dtype.html

![image](https://user-images.githubusercontent.com/21091736/145359990-84ba96b9-f77d-4602-a3d4-da1844da64d8.png)

**Comment by MegChai** [comment]
这不能算 bug, 只能算是一个 feature request. 希望支持默认字符串 `int` -> `int32` / `float` -> `float32`

**Comment by Olalaye** [comment]
@daisycx @MegChai 感谢回复。
因为numpy和PyTorch的`full()`的`dtype`参数均可以传入`int`和`float`。
我想知道，是否可以在megengine内部做处理，让他们具有同样的表现

**Comment by daisycx** [comment]
python 的 int 和 float 表示 int64 和 float64，MegEngine目前不支持这两种 dtype。如果把 int 和 float 映射到 int32 和 float32，以后增加 int64 和 float64 dtype 会出现和 numpy 不一致的行为，所以讨论后目前不支持传入int和float。
