### ISSUE TITLE
源码编译安装时编译nccl报错

### ISSUE THREAD

**Issue by oxygenman** [MegEngine/MegEngine#41]
编译时built target nccl时报错
## 环境
1.系统环境：ubuntu16.04
2.MegEngine版本：
3.python版本：3.7.7
4.cuda:10.1
5.tensorrt 6.0.1.5
6.llvm clang 6.0

![image](https://user-images.githubusercontent.com/28856502/79038673-ba493380-7c0d-11ea-8d77-97dbec1d4492.png)

**Comment by dc3671** [comment]
可以找一下类似以下语句的地方，或者提示Error的地方

```
dnn/src/CMakeFiles/megdnn.dir/flags.make:7: *** missing target pattern.  Stop.
```

**Comment by xxr3376** [comment]
由于 make 是并行的，请往上寻找原因。

另外有一些常见的问题，比如您是否执行了 `third_party/install-mkl.sh` 脚本？

**Comment by oxygenman** [comment]
好像是gcc 和g++的版本太低引起的，已编译成功
