### ISSUE TITLE
MegEngine CI修复通知

### ISSUE THREAD

**Issue by GetUpEarlier** [MegEngine/MegEngine#420]
## MegEngine CI修复通知
在过去一段时间内，我们发现MegEngine的ci经常在pytest中的test_persistent_cache步骤挂掉，正在尝试修复。在正式修复之前，我们暂时禁用了该测试（在实际环境中尚未复现该错误）。遇到该问题的同学可以自行rebase最新的master分支以绕开问题
#404 #402 #400 #397

**Comment by MegChai** [comment]
persistence cache 的问题已经修复，故关闭此 Issue.
