### ISSUE TITLE
PixelShuffle好像有问题

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#424]
## 环境
1.系统环境：Windows10
2.MegEngine版本：1.7.0
3.python版本：3.7.11

## 请提供关键的代码片段便于追查问题
```python
import megengine as mge
x = mge.random.normal(size=(1,12,26, 26))
pixelshuffle = mge.module.PixelShuffle(2)
out = pixelshuffle(x)
```

## 请提供完整的日志及报错信息
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\tools\Miniconda3\envs\megengine\lib\site-packages\megengine\module\module.py", line 148, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\tools\Miniconda3\envs\megengine\lib\site-packages\megengine\module\pixel_shuffle.py", line 24, in forward
    return pixel_shuffle(x, self.upscale_factor)
  File "D:\tools\Miniconda3\envs\megengine\lib\site-packages\megengine\functional\nn.py", line 1901, in pixel_shuffle
    outvar, *_ = apply(layerPixelShuffle(), inp, shape_0, shape_1)
RuntimeError: attempt to access dtype Float32 as Int32

backtrace:
2 null

3 null

4 null

5 null

6 null

7 null

8 null

9 null

10 null

11 null
```

**Comment by xiaocenxiaocen** [comment]
这是一个bug，如果想要快速修复的话，找到 megengine 的安装目录。我这里是`~/.local/lib/python3.7/site-packages/megengine`。修改一下该目录下的`functional/nn.py`这个文件，下面两行
https://github.com/MegEngine/MegEngine/blob/master/imperative/python/megengine/functional/nn.py#L1901-L1902
改为
```
shape_0 = convert_single_value(shape_0, dtype="int32", device=inp.device)
shape_1 = convert_single_value(shape_1, dtype="int32", device=inp.device)
```
然后再试一下。

**Comment by Qsingle** [comment]
> 这是一个bug，如果想要快速修复的话，找到 megengine 的安装目录。我这里是`~/.local/lib/python3.7/site-packages/megengine`。修改一下该目录下的`functional/nn.py`这个文件，下面两行 https://github.com/MegEngine/MegEngine/blob/master/imperative/python/megengine/functional/nn.py#L1901-L1902 改为
> 
> ```
> shape_0 = convert_single_value(shape_0, dtype="int32", device=inp.device)
> shape_1 = convert_single_value(shape_1, dtype="int32", device=inp.device)
> ```
> 
> 然后再试一下。

   ###感谢，我已修改，这理论上来说不加dtype,仅改变device也行,所以提了这个[PR](https://github.com/MegEngine/MegEngine/pull/425)
