### ISSUE TITLE
warp affine默认设置NHWC也太怪了

### ISSUE THREAD

**Issue by YachiZhang** [MegEngine/MegEngine#427]
在整个训练环境默认是NCHW的情况下，warp affine的format默认是NHWC。。。。
warp affine训练的时候不指定out shape和NCHW类型正常训练没报错，但是推理的时候报错了。

**Comment by xiaocenxiaocen** [comment]
你是不是设置了全局的`_config.__conv_format`，如果这个不是`default`，而是比如：`NCHW`的话，就会偷偷的把`warp_affine`的默认format改成`NCHW`。。。
行为却是很奇怪。。。

**Comment by xiaocenxiaocen** [comment]
所以默认值应该改成 NHWC ？

**Comment by xiaocenxiaocen** [comment]
文档里说是历史遗留问题，感觉是没法改了。

**Comment by xiaocenxiaocen** [comment]
要不就麻烦您显式设置成`NCHW`?这样就不报错了应该。。

**Comment by YachiZhang** [comment]
> 要不就麻烦您显式设置成`NCHW`?这样就不报错了应该。。

显示设置成NCHW就好了，就是觉得这样不是很友好。一个是pytorch风格一个是TensorFlow风格。所以我训练的时候warp_affine的default被悄悄改成了NCHW，所以训练没报错。但是推理的时候就会报错了。

**Comment by xiaocenxiaocen** [comment]
这个改动会影响api的默认行为，需要内部讨论一下。

**Comment by xiaocenxiaocen** [comment]
问了一下，历史上这个api是针对图像做的，并没有要支持在模型里面进行训练，所以默认是nhwc的格式。  
这个改掉的话，可能还要影响一些内部的东西，需要进一步讨论。

**Comment by YachiZhang** [comment]
> 

好的，十分感谢~
