### ISSUE TITLE
[Feature Request]关于ImageNet dataset的建议

### ISSUE THREAD

**Issue by Asthestarsfalll** [MegEngine/MegEngine#429]
使用megengine提供的`ImageNet`类发现了一个不太方便的地方，其期望的验证集文件夹形式是val/cls/xxx.${img_ext}，但如果是用户自行下载解压的话并不会有各种cls的子文件夹，这就会导致一张图片也读不到。
注意到`ImageNet`在解压时会调用`_organize_val_data`方法来创建上述形式的子文件夹，所以直接加一个判断如果val文件夹中直接包含五万张图片就进行`_organize_val_data`会不会更方便点呢？

**Comment by qq332982511** [comment]
如果发现val有5万张图片就执行_organize_val_data感觉不是很干净, 因为用户指定了imagenet是作为只读数据集, 执行_organize_val_data会导致目录被修改, 相当于修改了只读数据集的内容.  用户如果有一个依赖于val里直接存放5万张图目录的处理脚本也会因此失效

**Comment by qq332982511** [comment]
如果还能找到压缩包可以构建一个megengine能识别的未解压压缩包目录, 让megengine去构建能识别的imagenet数据集

**Comment by Asthestarsfalll** [comment]
确实，或许可以在注释中提示有这个方法，让用户自行决定是否调用，毕竟自己写还挺麻烦来着。

**Comment by qq332982511** [comment]
有种方式是实现一个可以命令行调整val目录的方法, 再不加一个目录结构检测. 当发现val目录没有调整就打印一个命令行调整该目录的命令, 用户自己去执行这条命令
