### ISSUE TITLE
avgpool/maxpool文档补全时ci挂掉

### ISSUE THREAD

**Issue by Seeker98** [MegEngine/MegEngine#444]
## 请简要描述您的需求
#442 #441 这两个的ci fail掉了，能帮忙查看一下失败原因吗

**Comment by cqchu** [comment]
#442 这个看起来是因为当时网络波动，下载MKL过慢导致超时了，建议重新跑一下

**Comment by Seeker98** [comment]
请问一下重跑/ci相关的指令在哪里看呢，我翻文档没找到…



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cqchu ***@***.***&gt;
发送时间: 2022年3月9日 17:10
收件人: MegEngine/MegEngine ***@***.***&gt;
抄送: Victor Chen ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MegEngine/MegEngine] avgpool/maxpool文档补全时ci挂掉 (Issue #444)

**Comment by cqchu** [comment]
已经重新跑了，看起来之前出问题的地方也已经顺利过去了

**Comment by Seeker98** [comment]
重新跑的 #442 卡在了和 #441 一样的地方。。。

**Comment by Seeker98** [comment]
好的，多谢~

**Comment by chen-2569** [comment]
> 重新跑的 #442 卡在了和 #441 一样的地方。。。

你好，现在可以 rebease 一下，rebease 后会自动重新跑 ci 就可以跑过了。

**Comment by Seeker98** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chen-2569 ***@***.***&gt;
发送时间: 2022年4月15日 16:33
收件人: MegEngine/MegEngine ***@***.***&gt;
抄送: Victor Chen ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MegEngine/MegEngine] avgpool/maxpool文档补全时ci挂掉 (Issue #444)





  
重新跑的 #442 卡在了和 #441 一样的地方。。。
  
你好，现在可以 rebease 一下，rebease 后会自动重新跑 ci 就可以跑过了。

**Comment by Seeker98** [comment]
> > 重新跑的 #442 卡在了和 #441 一样的地方。。。
> 
> 你好，现在可以 rebease 一下，rebease 后会自动重新跑 ci 就可以跑过了。

已经rebase并提交了，提示需要一个maintainer的确认，可以协助一下吗
