### ISSUE TITLE
DeformablePsRoiPooling cpu实现疑问

### ISSUE THREAD

**Issue by Seeker98** [MegEngine/MegEngine#446]
## 任务描述

dnn\src\naive\deformable_ps_roi_pooling\opr_impl.cpp中的deformable_ps_roi_pooling_forward似乎没有做并行化处理吗，如果以此实现代码为基础做并行化，根据算法本身有何修改意见和方向？

**Comment by gaohuazuo** [comment]
naive 目录下的 kernel 都是不做任何优化的，主要目的是作为参考实现和没有优化 kernel 可用时的 fallback。因此，dnn\src\naive\deformable_ps_roi_pooling\opr_impl.cpp 也没有做优化。

就算法本身的优化方向而言，注意到这是一个访存密集型算子，总体思路是优化访存局部性。但对于不同的输入和硬件平台，具体的优化实现可能需要针对性的设计，不一定能由一个 kernel 实现覆盖。
