### ISSUE TITLE
实现 WGAN-GP 中的梯度惩罚损失过程中报错

### ISSUE THREAD

**Issue by miemie2013** [MegEngine/MegEngine#447]
比如这样写

```
import megengine as mge
import megengine.functional as F
import megengine.module as M
import numpy as np
from megengine.autodiff import GradManager



class FullyConnectedLayer(M.Module):
    def __init__(self,
        in_features,                # Number of input features.
        out_features,               # Number of output features.
        bias            = True,     # Apply additive bias before the activation function?
        activation      = 'linear', # Activation function: 'relu', 'lrelu', etc.
        lr_multiplier   = 1,        # Learning rate multiplier.
        bias_init       = 0,        # Initial value for the additive bias.
    ):
        super().__init__()
        self.activation = activation
        self.weight = mge.Parameter(mge.tensor(np.random.randn(out_features, in_features).astype(np.float32)) / lr_multiplier)
        self.bias = mge.Parameter(mge.tensor(np.ones(out_features, ).astype(np.float32) * bias_init)) if bias else None
        self.weight_gain = lr_multiplier / np.sqrt(in_features)
        self.weight_gain = float(self.weight_gain)
        self.bias_gain = lr_multiplier

    def forward(self, x):
        w = self.weight * self.weight_gain
        b = self.bias
        if b is not None:
            if self.bias_gain != 1:
                b = b * self.bias_gain
        out = F.matmul(x, w, transpose_b=True) + F.expand_dims(b, 0)
        return out



batch_size = 2
in_channels = 512
w_dim = 512
lr = 0.0001
activation = 'sigmoid'

model = FullyConnectedLayer(w_dim, in_channels, activation=activation, bias_init=1)


model.train()
optimizer = mge.optimizer.SGD(model.parameters(), lr=lr, momentum=0.9)


for batch_idx in range(20):
    print('======================== batch_%.3d ========================'%batch_idx)
    optimizer.zero_grad()

    ws = np.random.randn(batch_size, 512)
    ws = mge.tensor(ws)
    ws.stop_gradient = False

    gm = GradManager().attach([ws])
    gm2 = GradManager().attach([ws])


    with gm:
        with gm2:
            styles = model(ws)
            # styles = F.cos(ws)
            styles2 = F.sigmoid(styles)

            gm2.backward(styles2)
            dstyles2_dws = ws.grad
            ws.grad = None

            loss = dstyles2_dws.sum() + styles2.sum()
            gm.backward(loss)
    optimizer.step()
print()
```
我要把一阶梯度和styles2作为损失训练网络，但是报错：
```
D:/GitHub/ppgan/test_grad/test2_01_FullyConnectedLayer_grad_mge222.py:52: DeprecationWarning: Call to deprecated method zero_grad. (use clear_grad instead) -- Deprecated since version 1.0.
  optimizer.zero_grad()
Traceback (most recent call last):
  File "D:/GitHub/ppgan/test_grad/test2_01_FullyConnectedLayer_grad_mge222.py", line 64, in <module>
    styles = model(ws)
  File "D:\Python38\lib\site-packages\megengine\module\module.py", line 148, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:/GitHub/ppgan/test_grad/test2_01_FullyConnectedLayer_grad_mge222.py", line 32, in forward
    out = F.matmul(x, w, transpose_b=True) + F.expand_dims(b, 0)
  File "D:\Python38\lib\site-packages\megengine\functional\math.py", line 1069, in matmul
    (result,) = apply(extentedMatrixMulOp(), inp1, inp2)
RuntimeError: Unknown exception
```
谢谢官方解答！

**Comment by Zhiy-Zhang** [comment]
我来看一下

**Comment by Zhiy-Zhang** [comment]
能否提供下您使用的版本那？

**Comment by miemie2013** [comment]
> 能否提供下您使用的版本那？

1.6.0  win10  cuda10.2 python3.8

**Comment by Zhiy-Zhang** [comment]
麻烦您升级下版本，试了下1.6，1.7 版本都有此问题，您可以试下1.8.1 或者1.8.2 版本

**Comment by miemie2013** [comment]
> 麻烦您升级下版本，试了下1.6，1.7 版本都有此问题，您可以试下1.8.1 或者1.8.2 版本

大佬您好！非常感谢您的解答，升级版本后不报错了，但是我遇到了新的问题。就是写出的梯度惩罚损失不能和pytorch对齐，不知道是不是因为我的写法有问题。劳请您再帮我看看！是最小代码复现，只有一个全连接层。

代码地址：https://github.com/miemie2013/ppgan
进入test_grad文件夹。首先运行test2_01_FullyConnectedLayer_grad.py，这是pytorch写的全连接层，跑20步训练，用输出styles2、输出对输入的梯度dstyles2_dws作为损失，保存训练之前模型的权重为pytorch_fullyConnectedLayer.pth，保存每一步输入ws、模型输出styles、梯度dstyles2_dws为文件01_fullyConnectedLayer_grad.npz；
接着，跑test2_01_FullyConnectedLayer_grad_2mge.py，全连接层用megengine实现一遍，将pytorch_fullyConnectedLayer.pth的权重复制给megengine的全连接层，保存为文件pytorch_fullyConnectedLayer.pkl；

最后，跑test2_01_FullyConnectedLayer_grad_mge.py，建立megengine的全连接层，加载权重pytorch_fullyConnectedLayer.pkl，读取01_fullyConnectedLayer_grad.npz中保存的输入作为输入，跑20次训练。即此时megengine版全连接层与pytorch版全连接层有相同的输入，我们期望megengine与pytorch有相同的输出、相同的梯度。但是跑20次训练后的结果发现，第一步之后输出、梯度就开始有差异。优化器的超参数是一样的。

希望能得到官方的帮助！谢谢！

**Comment by Zhiy-Zhang** [comment]
抱歉抱歉，您的回复好像没有提醒，导致我没有看到您最新的问题，我现在来看下

**Comment by Zhiy-Zhang** [comment]
你好，我看了下正向的结果就对不齐，同样load两个模型加state_dict输入同样的随机值，结果并不一样，可能需要麻烦您先对齐下正向的结果，目前看来使用上没什么问题，可能得详细对下模型。

**Comment by Zhiy-Zhang** [comment]
你好，想先跟您确认下，您这边测试得时候只测正向能够对齐嘛？我在第三个文件中load两个模型加载state_dict 然后输入随机数据但是发现正向也是对不齐都

**Comment by Zhiy-Zhang** [comment]
`model = mge_model(w_dim, in_channels, activation=activation, bias_init=1)
model.train()
optimizer = mge.optimizer.SGD(model.parameters(), lr=lr, momentum=0.9)
model.load_state_dict(mge.load("pytorch_fullyConnectedLayer.pkl", map_location="cpu"))


torch_model = torch_model(w_dim, in_channels, activation=activation, bias_init=1)
torch_model.train()
torch_model.load_state_dict(torch.load("pytorch_fullyConnectedLayer.pth", map_location="cpu"))

torch_input = torch.randn([2, 512])
mge_input=mge.tensor(torch_input.cpu().detach().numpy())
mge_out = model(mge_input)
torch_out = torch_model(torch_input)

ddd = np.sum((mge_out.numpy() - torch_out.cpu().detach().numpy()) ** 2)

print(ddd)
`
如果能够对齐的话那这段代码应该是始终等于0的把，想问下您这边是这样吗？因为一开始以为反向的梯度更新有问题，但是自己测试这段代码也是对不齐的

**Comment by Zhiy-Zhang** [comment]
`model = mge_model(w_dim, in_channels, activation=activation, bias_init=1)
model.train()
optimizer = mge.optimizer.SGD(model.parameters(), lr=lr, momentum=0.9)
model.load_state_dict(mge.load("pytorch_fullyConnectedLayer.pkl", map_location="cpu"))


torch_model = torch_model(w_dim, in_channels, activation=activation, bias_init=1)
torch_model.train()
torch_model.load_state_dict(torch.load("pytorch_fullyConnectedLayer.pth", map_location="cpu"))

torch_input = torch.randn([2, 512])
mge_input=mge.tensor(torch_input.cpu().detach().numpy())
mge_out = model(mge_input)
torch_out = torch_model(torch_input)

ddd = np.sum((mge_out.numpy() - torch_out.cpu().detach().numpy()) ** 2)

print(ddd)
`

**Comment by Zhiy-Zhang** [comment]
```model = mge_model(w_dim, in_channels, activation=activation, bias_init=1)
model.train()
optimizer = mge.optimizer.SGD(model.parameters(), lr=lr, momentum=0.9)
model.load_state_dict(mge.load("pytorch_fullyConnectedLayer.pkl", map_location="cpu"))


torch_model = torch_model(w_dim, in_channels, activation=activation, bias_init=1)
torch_model.train()
torch_model.load_state_dict(torch.load("pytorch_fullyConnectedLayer.pth", map_location="cpu"))

torch_input = torch.randn([2, 512])
mge_input=mge.tensor(torch_input.cpu().detach().numpy())
mge_out = model(mge_input)
torch_out = torch_model(torch_input)

ddd = np.sum((mge_out.numpy() - torch_out.cpu().detach().numpy()) ** 2)

print(ddd)
```
您发的结果我这边确实也显现了，但是在验证正向时，上面的代码片段是应该始终为0的，想问下您这边是这样吗？

**Comment by Zhiy-Zhang** [comment]
```
from meg_networks import FullyConnectedLayer as mge_model
from training.networks import FullyConnectedLayer as torch_model

model = mge_model(w_dim, in_channels, activation=activation, bias_init=1)
model.train()
optimizer = mge.optimizer.SGD(model.parameters(), lr=lr, momentum=0.9)
model.load_state_dict(mge.load("pytorch_fullyConnectedLayer.pkl", map_location="cpu"))


torch_model = torch_model(w_dim, in_channels, activation=activation, bias_init=1)
torch_model.train()
torch_model.load_state_dict(torch.load("pytorch_fullyConnectedLayer.pth", map_location="cpu"))

torch_input = torch.randn([2, 512])
mge_input=mge.tensor(torch_input.cpu().detach().numpy())
mge_out = model(mge_input)
torch_out = torch_model(torch_input)

ddd = np.sum((mge_out.numpy() - torch_out.cpu().detach().numpy()) ** 2)

print(ddd)

```
您发的结果我这边确实也复现了，如果正向有对齐，那上面的代码片段应该是结果始终为0的，想问下您这边是这样的嘛？

**Comment by miemie2013** [comment]
> ```
> from meg_networks import FullyConnectedLayer as mge_model
> from training.networks import FullyConnectedLayer as torch_model
> 
> model = mge_model(w_dim, in_channels, activation=activation, bias_init=1)
> model.train()
> optimizer = mge.optimizer.SGD(model.parameters(), lr=lr, momentum=0.9)
> model.load_state_dict(mge.load("pytorch_fullyConnectedLayer.pkl", map_location="cpu"))
> 
> 
> torch_model = torch_model(w_dim, in_channels, activation=activation, bias_init=1)
> torch_model.train()
> torch_model.load_state_dict(torch.load("pytorch_fullyConnectedLayer.pth", map_location="cpu"))
> 
> torch_input = torch.randn([2, 512])
> mge_input=mge.tensor(torch_input.cpu().detach().numpy())
> mge_out = model(mge_input)
> torch_out = torch_model(torch_input)
> 
> ddd = np.sum((mge_out.numpy() - torch_out.cpu().detach().numpy()) ** 2)
> 
> print(ddd)
> ```
> 
> 您发的结果我这边确实也复现了，如果正向有对齐，那上面的代码片段应该是结果始终为0的，想问下您这边是这样的嘛？

你好，我跑了一下你给的代码，结果是2.9495295e-12，这是一个非常小的数，可以看作是0了。

**Comment by Zhiy-Zhang** [comment]
您好，我们求导是需要跟attach weight的，不然无法更新参数，看到您attch 了 ws，但您需要追加weight：
```
gm = GradManager().attach([ws])
gm.attach(model.parameters())
gm2 = GradManager().attach([ws])
gm2.attach(model.parameters())
```
第二个问题是 这里要求的是二阶导，所以在一阶导后需要将weight的梯度设为none 否则会导致梯度进行累加，更新后自然会有问题，所以您还需要这样做：

```
gm2.backward(styles2)
dstyles2_dws = ws.grad
ws.grad = None

styles_mge = styles.numpy()
for m in model.parameters():
       m.grad = None
ddd = np.sum((styles_pytorch - styles_mge) ** 2)
print('ddd=%.6f' % ddd)
```

我本地测试没有什么问题，我们在即将发布的新版本1.9中因为修复了一些高阶导的问题，因为不确定您使用的版本，如果还对不齐参数的话您可以在这几天新版本发布后再次试用哦

**Comment by miemie2013** [comment]
> 您好，我们求导是需要跟attach weight的，不然无法更新参数，看到您attch 了 ws，但您需要追加weight：
> 
> ```
> gm = GradManager().attach([ws])
> gm.attach(model.parameters())
> gm2 = GradManager().attach([ws])
> gm2.attach(model.parameters())
> ```
> 
> 第二个问题是 这里要求的是二阶导，所以在一阶导后需要将weight的梯度设为none 否则会导致梯度进行累加，更新后自然会有问题，所以您还需要这样做：
> 
> ```
> gm2.backward(styles2)
> dstyles2_dws = ws.grad
> ws.grad = None
> 
> styles_mge = styles.numpy()
> for m in model.parameters():
>        m.grad = None
> ddd = np.sum((styles_pytorch - styles_mge) ** 2)
> print('ddd=%.6f' % ddd)
> ```
> 
> 我本地测试没有什么问题，我们在即将发布的新版本1.9中因为修复了一些高阶导的问题，因为不确定您使用的版本，如果还对不齐参数的话您可以在这几天新版本发布后再次试用哦

我按照了大佬的改法写了一个，还是不能全0，但是ddd的值变小了，呜呜呜。日常期待一下天元1.9
