### ISSUE TITLE
MegEngine里边如何对transform方法重写实现feature和label做同样的数据变换呢

### ISSUE THREAD

**Issue by Leeinsn** [MegEngine/MegEngine#449]
我在用MegEngine做图像去噪的任务，想实现feature和label做同样的变换。因为MegEngine里没有转置的变换，于是自己手写了转置的操作，在此想问一下，在MegEngine中如何才能实现feature和label的同时变换。谢谢！！！

`class Transpose(T.VisionTransform):`

    def __init__(self, prob: float = 0.5, *, order=None):
        super().__init__(order)
        self.prob = prob

    def apply(self, input: Tuple):
        self._flipped = np.random.random() < self.prob
        print(input)
        self._w = self._get_image(input).shape[1]
        return super().apply(input)

    def _apply_image(self, image):
        if self._flipped:
            return F.transpose(image, (0, 2, 1))
        return image

    def _apply_mask(self, mask):
        if self._flipped:
            return F.transpose(mask, (0, 2, 1))
        return mask`

**Comment by dzy97** [comment]
请问label是指什么呢？[VisionTransform](https://www.megengine.org.cn/doc/stable/zh/reference/api/megengine.data.transform.VisionTransform.html#megengine.data.transform.VisionTransform)里似乎没有 “label” 这种数据类型？

**Comment by MegChai** [comment]
> 请问label是指什么呢？[VisionTransform](https://www.megengine.org.cn/doc/stable/zh/reference/api/megengine.data.transform.VisionTransform.html#megengine.data.transform.VisionTransform)里似乎没有 “label” 这种数据类型？

图像去噪任务中的 label 应该就是 ground truth 的图片，如果 image 是带噪点的图片，gt 即不带噪点的原始图片。没理解错的话，这里的 featrue 和 label 的 layout 应当是完全等价的。

**Comment by dzy97** [comment]
可以用同一个 sampler 造两个 dataloader，这样每次 sample 出来的索引是一致的，分别处理 feature 和 label

**Comment by Leeinsn** [comment]
> 可以用同一个 sampler 造两个 dataloader，这样每次 sample 出来的索引是一致的，分别处理 feature 和 label

谢谢大佬！！！！醍醐灌顶啊

**Comment by Leeinsn** [comment]
> 

谢谢！！！
