### ISSUE TITLE
Feature Request : 求提供官方 docker 镜像

### ISSUE THREAD

**Issue by DIYer22** [MegEngine/MegEngine#451]
docker 非常方便部署 求提供官方 docker 镜像或者 build 脚本

**Comment by CeryZhai** [comment]
> docker 非常方便部署 求提供官方 docker 镜像或者 build 脚本

https://pypi.org/project/MegEngine/ 尝试一下 pip 安装如何？pip install MegEngine

**Comment by xxr3376** [comment]
@DIYer22 你是希望自行 build 么？

**Comment by DIYer22** [comment]
我尝试了随便基于一个 cuda docker 运行 pip install MegEngine 
发现能跑 CPU 版本, 使用 GPU 失败
只是想着有官方提供的 Dockerfile 的话, 就能直接用了, 更加方便, 而不用用户自己去写和尝试 Dockerfile

**Comment by DIYer22** [comment]
@xxr3376  有 Dockerfile 就可以, 但还是觉得提供 docker image 更加规范

**Comment by CeryZhai** [comment]
> 我尝试了随便基于一个 cuda docker 运行 pip install MegEngine
> 发现能跑 CPU 版本, 使用 GPU 失败
> 只是想着有官方提供的 Dockerfile 的话, 就能直接用了, 更加方便, 而不用用户自己去写和尝试 Dockerfile

cudnn cuda 版本是多少的呢？貌似megengine 的cuda 版本默认是 10.1 的

**Comment by haolongzhangm** [comment]
* megengine whl 本身不需要用户环境安装 CUDA 用户空间环境（换言之，用户自己装什么用户空间 CUDA 10.1还是11 还是不装都没有关系的）， 只需要用户安装驱动就OK
* 如果是docker 的话， 需要用户把 cuda driver.so 映射给 docker， 换言之，你首先要保证 docker 里面执行nivdias-smi 是可以看到卡的， docker 可以参考 nvidia 官方的docker 的base 来扩展自己的docker env
* 更多讨论可以参考 https://discuss.megengine.org.cn/t/topic/1264

**Comment by haolongzhangm** [comment]
@DIYer22  就此 ISSUE 的标题而言: "求提供官方 docker 镜像", 就 linux 版本我们是提供了Dockerfile的， 见
* https://github.com/MegEngine/MegEngine/blob/master/scripts/whl/manylinux2014/Dockerfile
* 如果基于 此 Dockerfile 构建自己的 docker 的， 见 https://github.com/MegEngine/MegEngine/blob/master/scripts/whl/manylinux2014/build_image.sh
* 此 docker 是用来 构建 MegEngine的， 如果要让 docker 本身可见 host 端的 驱动， 则建议用 https://hub.docker.com/r/nvidia/cuda 或者自己映射
* 再看上面描述有提到，如果不用docker 对 MegEngine whl 而言，部署也是一键的， 并不需要用户自己安装任何东西（当然python3 ， 和 N 卡驱动还是必须的, 见： https://www.nvidia.com/download/index.aspx ）， 注意 N 驱动和 cuda 三件套是不一样的， 通俗的解释:  N 卡能打游戏，则可以运行 MegEngine CUDA 模式

**Comment by MegChai** [comment]
> 我尝试了随便基于一个 cuda docker 运行 pip install MegEngine 发现能跑 CPU 版本, 使用 GPU 失败 只是想着有官方提供的 Dockerfile 的话, 就能直接用了, 更加方便, 而不用用户自己去写和尝试 Dockerfile

感觉是 XY 问题，提供 Docker 镜像并不是使得 MegEngine 能够在上述环境使用 GPU 的解决方案。

出现能够使用 CPU 而无法使用 GPU 的情况有很多种，用户频繁遇到的一种情况是：自己所使用的 GPU 设备所需的 CUDA sm86 比较高（比如使用了 30 系的显卡），而目前官方预编译好的 MegEngine Wheel 包是不支持 30 系卡的。如果确实是这种情况，即使是提供了 Docker Image 也无法解决问题，用户得自行编译，或者使用社区其它用户使用 CUDA11 编译的版本。

**Comment by DIYer22** [comment]
问题解决了, 是我 docker 环境的问题, 的确, 只要docker环境修复了, 随手 build 的镜像也能成功调用 GPU, 太强了. 感谢大家的热心解答 @haolongzhangm  @MegChai
