### ISSUE TITLE
Different DataLayout Conversion Cost?

### ISSUE THREAD

**Issue by ybai62868** [MegEngine/MegEngine#452]
不同datalayout之间的conversion代价，megengine是通过什么方式计算得到的？

**Comment by dc3671** [comment]
是说全局图优化那篇文章里的 layout conversion 吗？我的理解是所有转换都可以拆成 reshape 和 transpose 操作，而这两个原子操作的代价是可计算的，拼出来的转换操作也就变得可计算了

**Comment by ybai62868** [comment]
是那篇文章。关于这个计算有没有一些example的code？

**Comment by chen-2569** [comment]
> 是说全局图优化那篇文章里的 layout conversion 吗？我的理解是所有转换都可以拆成 reshape 和 transpose 操作，而这两个原子操作的代价是可计算的，拼出来的转换操作也就变得可计算了

对于 RelayoutFormat 算子支持的 layout Conversion，是计算 RelayoutFormat 的时间。其他的情况计算的是通过 reshape 和 transpose 操作转换的时间。

**Comment by chen-2569** [comment]
> 是那篇文章。关于这个计算有没有一些example的code？

可以阅读一下这部分源码，在这里https://github.com/MegEngine/MegEngine/blob/master/src/gopt/impl/global_layout_transform/profiler_impl.cpp#L369

**Comment by ybai62868** [comment]
> 

好的，谢谢了。我主要想关注下RelayoutFormat的时间，比如从NCHW转到NHWC的代价，我看看。。
