### ISSUE TITLE
MegEngine 导入模块出错  err: failed to load cuda func: cuMemcpy2D_v2_ptds

### ISSUE THREAD

**Issue by wangxl0385** [MegEngine/MegEngine#454]
## 环境
1.系统环境：Ubuntu 18.04
2.MegEngine版本：1.8.2
3.python版本：3.6.9

## 复现步骤
import megengine

## 请提供完整的日志及报错信息
>>> import megengine
err: failed to load cuda func: cuMemcpy2D_v2_ptds
[1]    491 segmentation fault  python

**Comment by linjinhao00** [comment]
我来看一下。

**Comment by linjinhao00** [comment]
看起来是cuda 驱动太低了。 可以从 https://www.nvidia.com/download/index.aspx 更新一下 cuda驱动，再试试

**Comment by wangxl0426** [comment]
> 看起来是cuda 驱动太低了。 可以从 https://www.nvidia.com/download/index.aspx 更新一下 cuda驱动，再试试

谢谢回答，不过版本应该可以的。
最终的原因是我的容器是基于虚拟的GPU创建的，切换到真实的GPU上就没问题了。

**Comment by runner42195** [comment]
> 
如果是在服务器上基于虚拟的GPU安装的megengine，该如何解决这个问题呀。。。（GPU资源无法切换，cuda驱动版本已经是最新的了）

**Comment by xxr3376** [comment]
只要 cuda 的各类依赖库正常就没问题，你可以把具体的报错单独提个 issue @runner42195
