### ISSUE TITLE
请问有支持高层API如MultiheadAttention等的计划吗？

### ISSUE THREAD

**Issue by Asthestarsfalll** [MegEngine/MegEngine#462]
如题，或是有接收此类PR的计划和打算吗？

**Comment by qq332982511** [comment]
有支持这类API的计划, 但目前对接口有分歧. 提供一版用python拼出来的megengine试验版multiheadattension放在xopr仓库中 https://github.com/MegEngine/xopr/blob/main/src/xopr/module/multiheadattention.py   
可以通过`pip install git+https://github.com/MegEngine/xopr.git`安装使用, 希望对你有帮助.

**Comment by Asthestarsfalll** [comment]
感谢！
