### ISSUE TITLE
How to use megengine module with pytorch module

### ISSUE THREAD

**Issue by mohamed19871988** [MegEngine/MegEngine#471]
i need to use megengine module with pytorch module

**Comment by yeasoon** [comment]
you can reference [https://www.megengine.org.cn/doc/stable/en/reference/comparison.html#comparison](https://www.megengine.org.cn/doc/stable/en/reference/comparison.html#comparison) to get the equivalent megengine module with the same function in pytorch

**Comment by mohamed19871988** [comment]
I have bn module from pytorch and conv2d module from megengine, how to add both modules in nn. Sequential

**Comment by qq332982511** [comment]
you can rewrite bn module from pytorch with megengine functional, simply replace `import torch.nn.functional as F` with `import megengine.functional as F`

**Comment by xxr3376** [comment]
@mohamed19871988 You can't put MegEngine's module and PyTorch's module together, convert PyTorch module to MegEngine's equivalent instead.
If you have any difficulties with weight convert, check this https://github.com/MegEngine/cheat_sheet_for_pytorch_immigrant
