### ISSUE TITLE
F.nn.interpolate py_apply expects tensor as inputs

### ISSUE THREAD

**Issue by Asthestarsfalll** [MegEngine/MegEngine#477]
## 环境
1.系统环境：
2.MegEngine版本：1.9.0
3.python版本：3.7.12

## 复现步骤
```python
import megengine as mge
import megengine.functional as F
inp = mge.random.normal(size=(2, 3, 224, 224))
out = F.nn.interpolate(inp, [512, 512], mode='bilinear', align_corners=True)
print(out.shape)
```
当align_corners=True时会报错：
![image](https://user-images.githubusercontent.com/72954905/185411904-3b0cdd10-ae41-45d9-93b9-5ea76c1844c4.png)
![image](https://user-images.githubusercontent.com/72954905/185415850-e7e4b64f-2279-4e89-891f-916585602993.png)
![image](https://user-images.githubusercontent.com/72954905/185415997-58dfc115-b471-4c63-91b0-8ef1240bc1cf.png)
![image](https://user-images.githubusercontent.com/72954905/185416157-f8b577e1-8c50-4c69-9e2d-5c40bfa2ca27.png)

似乎只有gpu上会报错

**Comment by yeasoon** [comment]
Megengine1.9.1已修复这个问题，主要是concat 不再支持非tesnor类型的数据输入导致
