### ISSUE TITLE
BUG Issue

### ISSUE THREAD

**Issue by shadowwu1** [MegEngine/MegEngine#479]
## 环境
1.系统环境：
2.MegEngine版本：Master
3.python版本：3.6.5 

## 复现步骤
1. 由于安装mkl_install.sh调用过慢，所以手动下载了mkl库
2. 执行cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DMGE_WITH_CUDA=OFF -DMGE_INFERENCE_ONLY=ON，编译load_and_run
3. 报错Can not find MKL
4. 查看了一下是mkl.cmake里未找到include/mkl_cblas.h

## 请提供关键的代码片段便于追查问题
mkl.cmake

## 请提供完整的日志及报错信息
CMake Error at cmake/mkl.make:14(message):
    CMakeLists.txt:1025(include)

**Comment by qq332982511** [comment]
可以提供一下你的mkl路径, 我们预期的路径为如图 
![image](https://user-images.githubusercontent.com/12827094/187583148-8ff6bb1f-72a2-4b89-b4e8-2a2780e5984a.png)
预期要链接的库
![image](https://user-images.githubusercontent.com/12827094/187583303-ab16ee10-9761-4094-b97d-66754a778ab4.png)
如果库对不上还是建议用自带的mkl_install.sh进行下载,或者下载相同版本后参考mkl_install.sh的实现进行解压

**Comment by shadowwu1** [comment]
我没有include这个文件夹，其他的都一样，我下载的地址是https://mirror.nju.edu.cn/pub/anaconda/cloud/intel/linux-64/?C=S&O=D  文件是mkl-static-2019.5-intel_281.tar.bz2，之后是按照mkl_install.sh解压的

**Comment by shadowwu1** [comment]
我想知道你们这个压缩包有国内地址吗？

**Comment by qq332982511** [comment]
https://mirror.nju.edu.cn/pub/anaconda/cloud/intel/linux-64/mkl-include-2019.5-intel_281.tar.bz2
https://mirror.nju.edu.cn/pub/anaconda/cloud/intel/linux-64/mkl-static-2019.5-intel_281.tar.bz2
你可能需要这两个包（话说可以给prepare脚本加个开关一键切国内镜像

**Comment by shadowwu1** [comment]
嗯， 感谢 ，我这边看了一下代码，漏了一个inlude包，下载下来解压就可以运行了。
我还有个问题，我这边想转个caffe模型进行推理，发现megengine推理貌似不支持三方输入，mgeconvert也只支持onnx. 除此之外是不是必须要自己训练mge模型，才能进行推理？

**Comment by qq332982511** [comment]
可以用其他工具把caffe转onnx，再用mgeconvert把onnx转megengine

**Comment by shadowwu1** [comment]
那我只需要安装 mgeconvert的onnx部分就行了吗

**Comment by qq332982511** [comment]
对， 建议用最新的mgeconvert版本
