### ISSUE TITLE
load_and_run编译报错

### ISSUE THREAD

**Issue by shadowwu1** [MegEngine/MegEngine#480]
## 环境
1.系统环境：linux
2.MegEngine版本：master
3.python版本：3.6.7

## 复现步骤
1. 按照源码编译load_and_run 
2. scripts/cmake-build/host_build.sh -e load_and_run 这步编译通过
3. scripts/cmake-build/cross_build_android_arm_inference.sh -e load_and_run -a <arm_arch>编译报错，错误为collect2:fatal error: ld terminated with signal 11 [segmentation fault]

**Comment by qq332982511** [comment]
求更详细的报错信息

**Comment by shadowwu1** [comment]
报错信息：
FAILED:lite/load_and_run/load_and_run

collect2:fatal error: ld terminated with signal 11 [segmentation fault]
compilation terminated.
ninja:build stopped: subcommand failed

**Comment by shadowwu1** [comment]
上面编译指令弄错了，我是交叉编译linux，指令是
scripts/cmake-build/cross_build_linux_arm_inference.sh -e load_and_run -a arm64-v8a

**Comment by qq332982511** [comment]
ninja:build stopped: subcommand failed 一般是编译失败了（可能编译器版本和我们验证的版本不同导致出现werror等问题），可能需要提供详细的编译日志。或者直接根据日志直接对编译脚本、源文件做对应的修改

**Comment by shadowwu1** [comment]
我把编译指令改为scripts/cmake-build/cross_build_linux_arm_inference.sh -e
报错变成
Linking CXX shared library src/libmegengine_shared.so
FAILED: src/libmegengine_shared.so
我用find指令没找到这个动态库

**Comment by chenqy4933** [comment]
感觉是ld链接器挂了，是不是机器内存用完了啊

**Comment by qq332982511** [comment]
或许可以使用release版本的tag如v1.11.0 ， 因为release版本经过了更严格的验证 
可能需要贴出命令失败的关键信息，如
![image](https://user-images.githubusercontent.com/12827094/188049172-f054ff2c-7b4e-4c21-a4b3-2dcfb15ca322.png)
我用v1.10.0和gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu编译器验证了一把`scripts/cmake-build/cross_build_linux_arm_inference.sh -e load_and_run -a arm64-v8a`，关闭flatbuffer的`-Wimplicit-fallthrough`选项能正常编译过

**Comment by shadowwu1** [comment]
挂载的目录，内存够的，我重编后第一个报错
Linking CXX executable flatbuffers.flathash
FAILED:flatbuffer/flathash

**Comment by qq332982511** [comment]
链接器具体的错误是啥？符号未找到？

**Comment by shadowwu1** [comment]
我换成releasev1.11.0版本 还是出现一样的问题

![image](https://user-images.githubusercontent.com/46781724/188078342-a439ba28-5b70-4f31-a517-1a08eb8bbda2.png)

**Comment by shadowwu1** [comment]
难道我用的版本和你们的版本不一致吗，我这个是直接拉的github

**Comment by xxr3376** [comment]
系统环境的影响会很大，建议你直接拿个 docker 镜像里复现，如果能复现问题的话可以给个 Docker image，否则系统里环境影响因素太多了…

**Comment by qq332982511** [comment]
> 我换成releasev1.11.0版本 还是出现一样的问题
> 
> ![image](https://user-images.githubusercontent.com/46781724/188078342-a439ba28-5b70-4f31-a517-1a08eb8bbda2.png)
求贴一个完整的编译文本。。截图的信息没看到`error:`

**Comment by shadowwu1** [comment]
![Snipaste_2022-09-02_15-59-00](https://user-images.githubusercontent.com/46781724/188088419-085f2252-0108-4783-bc6c-1dfec55178cb.png)

**Comment by qq332982511** [comment]
猜可能是内存不够或者工具链自身的bug， 内存不够可以通过top看下编译时的内存占用， 工具链自身的bug可以考虑换6.5.0-2018.12-x86_64试试

**Comment by haolongzhangm** [comment]
这个就是 系统内存不足了， 

dmesg 可以找到 kill log

如果没有条件增加 DDR

则建议

* -j 后面跟的 number 小一点
* 怎就swap 分区 ,至于怎么增加swap 分区， google 哥或者度娘一下就好

**Comment by shadowwu1** [comment]
应该不是内存的问题，我这边编译x86成功了，然后测试没有问题。
交叉编译这边，我用了ninja而不是ninja -j 66同样报错，查看了build下的build_ninja实现里面会有一些link the share library 的操作，里面是链接了libmegengine_shared.so, libmegengine.so,liblite_shared.so, 这三个动态库报错了

**Comment by haolongzhangm** [comment]
signal 11 ， 一定是系统发了kill 信号过来，你可以通过 dmesg  确认一下的

注意这里不是存储不够， 是DDR 不够

直接 ninjia 默认是 用 CPU_NR + 2 线程来编译的，  只有 显示 的ninja -j1  才是一个线程， 这个逻辑和 make 是一一样的

另外gcc 我们要求最低版本，6.5 ，你这边使用的 6.2， 可按照 readme 中步骤提到的 http://releases.linaro.org/components/toolchain/binaries/ or https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads 的地方去下载一个版本


建议创建 swap 分区是没有错误的， 我们要求至少  8G DDR 来编译， 如果DDR 不够，则创建  swap

**Comment by shadowwu1** [comment]
> signal 11 ， 一定是系统发了kill 信号过来，你可以通过 dmesg 确认一下的
> 
> 注意这里不是存储不够， 是DDR 不够
> 
> 直接 ninjia 默认是 用 CPU_NR + 2 线程来编译的， 只有 显示 的ninja -j1 才是一个线程， 这个逻辑和 make 是不一样的
> 
> 另外gcc 我们要求最低版本，6.5 ，你这边使用的 6.2， 可按照 readme 中步骤提到的 http://releases.linaro.org/components/toolchain/binaries/ or https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads 的地方去下载一个版本
> 
> 建议创建 swap 分区是没有错误的， 我们要求至少 8G DDR 来编译， 如果DDR 不够，则创建 swap

感谢你的回复，我修改工具链的版本为6.5.0，成功编译了，在hisi上测试也是通过的，感谢。
