### ISSUE TITLE
[BUG Issue] DTR功能中的 eviction_threshold 这个接口是否已经失效？

### ISSUE THREAD

**Issue by mosout** [MegEngine/MegEngine#482]
## 环境
1.系统环境：Ubuntu 20.04
2.MegEngine版本：1.11
3.python版本：3.8.10

## 复现步骤

https://www.megengine.org.cn/doc/stable/zh/user-guide/model-development/dtr/index.html

根据上述文档中的操作开启DTR来跑[resnet50](https://github.com/MegEngine/Models/tree/master/official/vision/classification/resnet)，将batch-size设为115

使用下述代码开启DTR
```python
megengine.dtr.eviction_threshold = "2500MB"
megengine.dtr.enable()
```

## 问题

发现实际上显存占用保持在6GB左右并顺利完成计算，按照预期显存应该在2.5GB左右，如果无法完成重计算，应该提示out of memory

后来又尝试了使用很小的阈值比如100MB，发现显存占用仍在6GB左右，而且网络也能顺利完成计算

所以想问下 megengine.dtr.eviction_threshold 这个接口实际上是否已经是无效的了？同时想问一下如果我想要获得上述的预期的结果应该如何操作？

**Comment by xxr3376** [comment]
因为已经有了无阈值自适应方案了，`eviction_threshold` 这个接口的有效性确实最近缺乏观测。

不过值得专门指出的是：`eviction_threshold` 是一个给 DTR 算法的 hint 而非一个 limit，因此设置 eviction_threshold 并不代表运行时的显存占用量绝对不会超过此数值。

如果希望严格的控制显存的上限，最简单的手段是手工创建一个对应大小的 Tensor，因为所有原始 Tensor 一定不会被 DTR 算法 drop，所以可以起到控制显存上限的效果。

**Comment by mosout** [comment]
> 手工创建一个对应大小的 Tensor
是指在开启DTR之前创建一个在后续不会用到的全局Tensor么，然后在后面的执行过程中显存就会被局限在这个Tensor大小？

不过我试了一下，创建一个{threshold(MB)}*1024*1024/4的float类型的Tensor，但实际上占用的显存还是要比这个阈值大的

**Comment by xxr3376** [comment]
> 在后面的执行过程中显存就会被局限在这个Tensor大小

@mosout 并没有这么高端，你理解反了，创建一个全局 tensor 主要就是为了把显存占住…
从而后边执行过程中显存会被局限在 `totalsize - this_tensor_size` 的空间内，因此你在任何时候创建都可以。

**Comment by mosout** [comment]
> > 在后面的执行过程中显存就会被局限在这个Tensor大小
> 
> @mosout 并没有这么高端，你理解反了，创建一个全局 tensor 主要就是为了把显存占住… 从而后边执行过程中显存会被局限在 `totalsize - this_tensor_size` 的空间内，因此你在任何时候创建都可以。

明白了！ 顺便请教一下megengine创建这个tensor的正确姿势是什么，我用`megengine.functional.ones(((11264-args.threshold)*1024*1024/4,),dtype="float32")`这样的代码来创建tensor，但是看了下显存，并没有占据那么多的空间，似乎，tensor并没有被实际分配显存？或者说这个操作是异步的，所以我用了`megengine.core._imperative_rt.core2.full_sync()`来同步，但是好像还是不行

**Comment by xxr3376** [comment]
@mosout `ones` 本质上是把一个 size=1 的 Tensor broadcast 到一个很大的数值， MegEngine imperative 里面会直接创建一个合理设置了 stride 和 shape 的新 Tensor 描述符，数据是复用这个 size=1 的 Tensor 的，所以你会观察到几乎没占用任何显存。

你可以在 numpy 里造好这个数据`mge.Tensor(np.zeros(....).astype('float32'))`，这种时候 mge 不知道这里面所有数据都是一样的，所以只会乖乖的拷贝一遍。

**Comment by mosout** [comment]
> @mosout `ones` 本质上是把一个 size=1 的 Tensor broadcast 到一个很大的 shape， MegEngine imperative 里面会直接创建一个合理设置了 stride 和 shape 的新 Tensor 描述符，数据是复用这个 size=1 的 Tensor 的，所以你会观察到几乎没占用任何显存。
> 
> 你可以在 numpy 里造好这个数据`mge.Tensor(np.zeros(....).astype('float32'))`，这种时候 mge 不知道这里面所有数据都是一样的，所以只会乖乖的拷贝一遍。

明白了，谢谢！我试一下

**Comment by mosout** [comment]
@xxr3376 你好，我尝试了你上次说的使用一个全局tensor占位来限制DTR使用的内存的方法，却发现出现了这样的提示:

![image](https://user-images.githubusercontent.com/16584240/189069291-7ed440b3-21fe-4c3b-bee9-8b9d47b8073c.png)

然后看了下时间相比较不用全局tensor占位多了很多，但是实际上，除去占位的tensor的大小意外的空间是要大于不占位情况下DTR使用的内存的，但却出现了oom这是什么情况？

**Comment by xxr3376** [comment]
@mosout 你可能没考虑 CUDA context 本身占用的空间

**Comment by mosout** [comment]
@xxr3376 这个我考虑到了。
我创建了一个只有一个元素的tensor，然后把当前观察到的显存占用当作cuda context使用的显存。我把这个大小减掉之后仍旧出现了oom。
然后我以为减去的大小并不能反映cuda context在运行过程中实际上占用的显存，所以又多减了一个G，但是仍然出现了oom。
似乎不管怎么样megengine在运行DTR的时候都需要所有的显存，不能使用全局tensor占据空间的方式来控制显存上限。

**Comment by daquexian** [comment]
（乱入）如果阈值是 megengine 自己自适应选择的，那用户是不是并不需要考虑 cuda context 的显存

**Comment by xxr3376** [comment]
@daquexian 是的，本来 megengine 自适应的最大好处就是不需要设置阈值了（因此也不需要考虑如何精妙的算 cuda context 了）。

我理解 @mosout 上面想做的可能只是为了模拟出显存更小的场景来做对比？

**Comment by mosout** [comment]
> 我理解 @mosout 上面想做的可能只是为了模拟出显存更小的场景来做对比？

@xxr3376  是的，不过没事了，我已经找到限制显存进行对比的方法，谢谢！

**Comment by xxr3376** [comment]
@mosout 好奇一下怎么做的，求教！

**Comment by mosout** [comment]
@xxr3376 就是再开一个进程使用pytorch或者megengine创建tensor来占据目标卡上指定大小的内存，这样就行了🤣
