### ISSUE TITLE
Tensorrt execute inferences with cuda multi-streams

### ISSUE THREAD

**Issue by brilliant-soilder** [MegEngine/MegEngine#485]
To maximize GPU utilization, what should I dou to parallel cuda multiple stream streams, enabling tensorrt to achieve simultaneous inference when executing inference enqueuev2 sequences?
Like This following pic :
![0](https://user-images.githubusercontent.com/59491993/190040966-5e639e20-7085-404e-b349-5748b50b769d.png)

**Comment by CaoWGG** [comment]
For using stream in TensorRT, please refer [here](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#streaming).
