### ISSUE TITLE
Tensor创建部分的 “是否是设备的锁页内存” 是否有误？

### ISSUE THREAD

**Issue by Tumb1eweed** [MegEngine/MegEngine#489]
## 文档链接
[](https://megengine.megvii-inc.com/user-guide/deployment/lite/interface/cpp.html#reset)

## 问题描述
![image](https://user-images.githubusercontent.com/27768261/192930249-3e60df5b-cc7f-4295-b1a2-0ba8a697008c.png)
这里应该不是说device的锁页内存 而应该是host的锁页内存？

**Comment by yeasoon** [comment]
是的，这里的设备指的是计算设备，不是device的概念，is_pinned_host 选项用于指定这个tensor 分配时是否是host 上的锁页内存，用于优化h2d d2h的内存拷贝操作

**Comment by Tumb1eweed** [comment]
> 是的，这里的设备指的是计算设备，不是device的概念，is_pinned_host 选项用于指定这个tensor 分配时是否是host 上的锁页内存，用于优化h2d d2h的内存拷贝操作

嗯嗯 谢谢解答！
