### ISSUE TITLE
Help-wanted Issue: 使用CUDA编译MegEngine后, 在GPU上的tensor的get_memory_ptr返回的指针无法直接操作，而需要通过CUDA接口操作

### ISSUE THREAD

**Issue by Tumb1eweed** [MegEngine/MegEngine#493]
## 任务描述

比如auto tensor = net_->get_io_tensor(tensor_name); 该tensor在GPU上，在torch C++中可以直接操作例如output_ptr[]等操作，但使用megengine时却会导致segmentfault，需要通过CUDA接口，cudaMallocHost + cudaMemcpy拷贝到host中才能访问，这个是编译megengine时需要开启什么选项吗？还是我用法上有误呢？或是megengine开GPU memory的时候用的是cudamalloc而不是cudamallocmanaged 所以不支持统一内存？

**Comment by cqchu** [comment]
是的，出于性能的考量，megengine 现在显存分配都是使用的 cudaMalloc，想问下是有什么需求需要在 CPU 上去修改 GPU memory 呢？

**Comment by Tumb1eweed** [comment]
> 是的，出于性能的考量，megengine 现在显存分配都是使用的 cudaMalloc，想问下是有什么需求需要在 CPU 上去修改 GPU memory 呢？

哦倒没有什么需求 只是用法习惯上可能比较麻烦而已 访问gpu时需要再加一层cuda的接口访问 如果是因为性能的话就可以理解了 谢谢解答！
