### ISSUE TITLE
如何针对部分Tensor值进行修改操作

### ISSUE THREAD

**Issue by Tramac** [MegEngine/MegEngine#495]
## 背景

需求是对某个tensor中的部分值进行修改，如果通过二次索引的方式无法完成修改。

## 任务描述

tensor1 = mge.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = mge.Tensor([[False, True, False], [False, True, False], [False, True, False]])
tensor1[mask][1] = 100
print(tensor1)

`
Tensor([[1 2 3]
 [4 5 6]
 [7 8 9]], dtype=int32, device=xpux:0)
`

## 目标

期待结果是：
`
Tensor([[1 2 3]
 [4 100 6]
 [7 8 9]], dtype=int32, device=xpux:0)
`

更简单的理解：上述操作可以通过tensor1[1, 1]=100可以实现，但是通过tensor1[1][1] = 100无法实现，是否存在一种可以通过第二种方式完成的方法？

**Comment by CaoWGG** [comment]
您好，megengine 目前并不支持真正的 inplace 操作。关于 Tensor 在 mgengine 中 python 层和 c++ 层进行不同操作后的变化，可以先阅读[这里](https://www.megengine.org.cn/doc/stable/zh/development/behind/pytensor.html)的介绍。

在 `tensor1[1][1] = 100` 中，Tensor 的变化过程实际如下：
* 首先新建了一个 tmp_tensor，即 `tmp_tensor = tensor1[1]`
  在这个过程中，tensor 的变化如下：
  | Python Tenso | C++ Tensor | Storage                             |
  | ------------ | ---------- | ----------------------------------- |
  | 新建         | 新建       | 复用 tensor1 的 storage，即 ref + 1 |
* 对 tmp_tensor 赋值，即 `tmp_tensor[1] = 100`
  在这个过程中，tensor 的变化如下：
  | Python Tenso | C++ Tensor | Storage                             |
  | ------------ | ---------- | ----------------------------------- |
  | 不变         | 新建       | 新建并拷贝，tensor1 的 storage ref - 1 |

即，在这个赋值的过程中，并不会改变 tensor1 的 storage。

**Comment by Tramac** [comment]
明白了，感谢回答~
