### ISSUE TITLE
python 3.10 pip download wanted

### ISSUE THREAD

**Issue by zchrissirhcz** [MegEngine/MegEngine#496]
## 请简要描述您的需求
当前使用 python 3.10 版本， 想通过 `pip install MegEngine` 下载安装 MegEngine。

看到已经有相关 commit：
https://github.com/MegEngine/MegEngine/commit/cdf7baa245dcd8b424bb735b5ceb9877c87c2e68

不过在 pypi 上看到似乎支持到 python 3.9：
https://pypi.org/project/MegEngine/#files

**Comment by momoComeOn** [comment]
谢谢您的邮件，我会尽快回复！

**Comment by kagome1007** [comment]
我们将在下个版本支持python 3.10，预计在月底进行发布

**Comment by haolongzhangm** [comment]
@zchrissirhcz    如果着急的使用的话，也可自己在本地进行构建, 可参考  https://github.com/MegEngine/MegEngine/blob/master/scripts/whl/BUILD_PYTHON_WHL_README.md

**Comment by zchrissirhcz** [comment]
Thanks for the reply. 目前切换到了 python 3.9， 可以正常使用。
