### ISSUE TITLE
目前megengine的cuda后端是否支持softmax算子的实现呢？

### ISSUE THREAD

**Issue by zjd1988** [MegEngine/MegEngine#50]
## 请简要描述您的需求
浏览了下源码，但是没有找到softmax相应cuda代码实现，不知道是我没找到还是目前还不支持？

**Comment by qq332982511** [comment]
https://github.com/MegEngine/MegEngine/blob/master/python_module/megengine/functional/nn.py#L317

**Comment by qq332982511** [comment]
目前后端没有一个专做softmax的Opr

**Comment by zjd1988** [comment]
@qq332982511  ok，了解了，谢谢啦。
