### ISSUE TITLE
Linux下源码编译失败, 报错 /usr/bin/ld.gold: error: cannot find -lMKL_CORE_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by Wanglongzhi2001** [MegEngine/MegEngine#512]
## 背景

OS: Ubuntu20.04
CUDA version: 11.8
cudnn version: 8.9.0
TensorRT version: 8.5.1
cmake version: 3.16.3
gcc version: 9.4.0
## 任务描述

根据 root/README_CN.md进行源码编译：
(1) ./third_party/prepare.sh
(2) ./third_party/install-mkl.sh
(3) install build-essential git git-lfs gfortran libgfortran-6-dev autoconf gnupg flex bison gperf curl zlib1g-dev gcc-multilib g++-multilib lib32ncurses5-dev libxml2-utils xsltproc unzip libtool librdmacm-dev rdmacm-utils python3-dev python3-numpy texinfo以及export cuda和cudnn和tensorrt的路径
(4) ./scripts/cmake-build/host_build.sh -d -c
到[2568/2580] Linking CXX executable lite/rc4_encryptor时开始报错，报错信息为：
FAILED: lite/rc4_encryptor 
: && /usr/bin/c++  -include /home/wlz/Dev/MyPR/MegEngine/src/bin_reduce_cmake.h -ffunction-sections -fdata-sections -Wall -Wextra -Wno-unused-parameter -Wno-extra -m64 -msse4.2 -mfpmath=sse  -fvisibility=hidden -O0 -g  -Wl,--gc-sections -flto=full -fuse-ld=gold lite/CMakeFiles/rc4_encryptor.dir/tools/rc4_encrypt.cpp.o  -o lite/rc4_encryptor -L/usr/local/cuda/targets/x86_64-linux/lib   -L/usr/local/cuda/targets/x86_64-linux/lib/stubs -Wl,-rpath,/usr/local/cuda/targets/x86_64-linux/lib:  lite/liblite_static.a  flatbuffers/libflatbuffers.a  -lrt  -latomic  cpuinfo/libcpuinfo.a  cpuinfo/deps/clog/libclog.a  third_party/intel-mkl-dnn/src/libdnnl.a  -pthread  -Wl,--start-group  -lMKL_CORE_LIBRARY-NOTFOUND  -lMKL_SEQUENTIAL_LIBRARY-NOTFOUND  -lMKL_IPL_LIBRARY-NOTFOUND  -Wl,--end-group  -lpthread  /usr/lib/libnvinfer.so  /usr/lib/libnvinfer_plugin.so  /usr/local/cudnn/cudnn-linux-x86_64-8.9.0.131_cuda12-archive/lib/libcudnn.so  -lcusolver_static  -lcurand_static  -lculibos  -lcudart_static  -lcusparse_static  -lcublas_static  -lcublasLt_static  -lculibos  -lcudart_static  -lcusparse_static  -lcublas_static  -lcublasLt_static  liblapack_static_copy.a  liblapack_static_copy.a  -lnvrtc  -ldl  -Wl,--no-undefined  -lnvToolsExt -lrt -ldl  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl && :
/usr/bin/ld.gold：错误： cannot find -lMKL_CORE_LIBRARY-NOTFOUND
/usr/bin/ld.gold：错误： cannot find -lMKL_SEQUENTIAL_LIBRARY-NOTFOUND
/usr/bin/ld.gold：错误： cannot find -lMKL_IPL_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status

## 目标

看到#60 这个issue和我有同样的问题，说是下载的mkl有问题，我尝试自己下载最新的mkl库并将其lib文件夹复制到thirdparty下的mkl文件夹里不起作用，并且尝试使用ld -lMKL_CORE_LIBRARY-NOTFOUND --verbose命令寻找其找寻的文件地址并进行软链接，仍然无效。如果能得到你们的帮助来成功编译的话就太感谢了。

**Comment by Wanglongzhi2001** [comment]
参考issue #479 后，该问题已解决

**Comment by momoComeOn** [comment]
谢谢您的邮件，我会尽快回复！
