### ISSUE TITLE
如何测试自定义的带 CUDA 后端的算子

### ISSUE THREAD

**Issue by Wanglongzhi2001** [MegEngine/MegEngine#513]
## 背景

OS: WSL2 (Ubuntu20.04)
显卡: P106
CUDA version: 11.8
已成功编译并运行CUDA测试
![image](https://github.com/MegEngine/MegEngine/assets/69797242/6ec09e1f-9907-4e49-ab78-a9ae2122ad99)

在测试自定义CUDA算子的时候报如下错误：
megdnn error: unsupported cuda opr, try export RUNTIME_OVERRIDE_LOG_LEVEL=0 to get more info
## 任务描述

我在MegEngine文档里看到说测试自定义的带CUDA后端的算子，需要编译对应显卡的代码
![image](https://github.com/MegEngine/MegEngine/assets/69797242/bf016f18-99ef-4aa4-b4b7-feeefa787b15)

但是没有[third_party/getcudacap.sh](https://github.com/MegEngine/MegEngine/blob/master/third_party/getcudacap.sh)这个文件

## 目标

希望告知一下如何测试自定义的CUDA算子

**Comment by Ysllllll** [comment]
该报错表明没有定义对应的cuda opr，需要先定义该opr，这一流程可以参考下文档：https://www.megengine.org.cn/doc/stable/zh/development/how-to/add-an-operator.html

**Comment by Wanglongzhi2001** [comment]
> 该报错表明没有定义对应的cuda opr，需要先定义该opr，这一流程可以参考下文档：https://www.megengine.org.cn/doc/stable/zh/development/how-to/add-an-operator.html

您好，首先感谢您的回复。我已经按照文档定义了opr，并且在naive版本下通过了测试，CUDA版本仍然报这个错误

**Comment by Ysllllll** [comment]
> 

cuda backend也添加了吗，文档中的添加流程只涉及naive opr。与naive同级的cuda文件夹中，需要添加自定义算子的cuda/my_opr/opr_impl.h，以及cuda/my_opr/opr_impl.cpp文件，这两个文件是自定义算子的cuda实现，以及在cuda/handle_create.cpp中include对应的头文件，即my_opr/opr_impl.h。

**Comment by Wanglongzhi2001** [comment]
> > 
> 
> cuda backend也添加了吗，文档中的添加流程只涉及naive opr。与naive同级的cuda文件夹中，需要添加自定义算子的cuda/my_opr/opr_impl.h，以及cuda/my_opr/opr_impl.cpp文件，这两个文件是自定义算子的cuda实现，以及在cuda/handle_create.cpp中include对应的头文件，即my_opr/opr_impl.h。

是的，这些都添加了。仅仅是这样就可以了吗，不需要像文档所说的编译显卡代码吗

**Comment by Ysllllll** [comment]
> > > 
> > 
> > 
> > cuda backend也添加了吗，文档中的添加流程只涉及naive opr。与naive同级的cuda文件夹中，需要添加自定义算子的cuda/my_opr/opr_impl.h，以及cuda/my_opr/opr_impl.cpp文件，这两个文件是自定义算子的cuda实现，以及在cuda/handle_create.cpp中include对应的头文件，即my_opr/opr_impl.h。
> 
> 是的，这些都添加了。仅仅是这样就可以了吗，不需要像文档所说的编译显卡代码吗

你已经编译出来了呀，上面的`./megdnn_test --gtest_filter=CUDA.DROPOUT_F32`能够运行。另外上面提到的“并且在naive版本下通过了测试”，是指使用 `./megdnn_test --gtest_filter=NAIVE.MYOPRTEST`通过测试吗，如果这里通过了表明naive这边的opr定义ok，只需要排查cuda这边的opr定义的完整性。另外请确定下cuda/handle_create.cpp中有MEGDNN_SPECIALIZE_CREATE_OPERATOR(MY_OPR_FORWARD);

**Comment by Wanglongzhi2001** [comment]
> > > > 
> > > 
> > > 
> > > cuda backend也添加了吗，文档中的添加流程只涉及naive opr。与naive同级的cuda文件夹中，需要添加自定义算子的cuda/my_opr/opr_impl.h，以及cuda/my_opr/opr_impl.cpp文件，这两个文件是自定义算子的cuda实现，以及在cuda/handle_create.cpp中include对应的头文件，即my_opr/opr_impl.h。
> > 
> > 
> > 是的，这些都添加了。仅仅是这样就可以了吗，不需要像文档所说的编译显卡代码吗
> 
> 不需要，你上面的`./megdnn_test --gtest_filter=CUDA.DROPOUT_F32`已经能够跑起来了。另外上面提到的“并且在naive版本下通过了测试”，是指使用 `./megdnn_test --gtest_filter=NAIVE.MYOPRTEST`通过测试吗，如果这里通过了表明naive这边的opr定义ok，只需要排查cuda这边的opr定义的完整性。另外请确定下cuda/handle_create.cpp中有MEGDNN_SPECIALIZE_CREATE_OPERATOR(MY_OPR_FORWARD);

首先感谢您及时的回复，"是指使用 ./megdnn_test --gtest_filter=NAIVE.MYOPRTEST通过测试吗"：是的。"另外请确定下cuda/handle_create.cpp中有MEGDNN_SPECIALIZE_CREATE_OPERATOR(MY_OPR_FORWARD);"：确实没有添加这个MEGDNN_SPECIALIZE_CREATE_OPERATOR，我添加后试试，出结果后通知您。再次感谢您的回复^_^

**Comment by Wanglongzhi2001** [comment]
> > > > 
> > > 
> > > 
> > > cuda backend也添加了吗，文档中的添加流程只涉及naive opr。与naive同级的cuda文件夹中，需要添加自定义算子的cuda/my_opr/opr_impl.h，以及cuda/my_opr/opr_impl.cpp文件，这两个文件是自定义算子的cuda实现，以及在cuda/handle_create.cpp中include对应的头文件，即my_opr/opr_impl.h。
> > 
> > 
> > 是的，这些都添加了。仅仅是这样就可以了吗，不需要像文档所说的编译显卡代码吗
> 
> 不需要，你上面的`./megdnn_test --gtest_filter=CUDA.DROPOUT_F32`已经能够跑起来了。另外上面提到的“并且在naive版本下通过了测试”，是指使用 `./megdnn_test --gtest_filter=NAIVE.MYOPRTEST`通过测试吗，如果这里通过了表明naive这边的opr定义ok，只需要排查cuda这边的opr定义的完整性。另外请确定下cuda/handle_create.cpp中有MEGDNN_SPECIALIZE_CREATE_OPERATOR(MY_OPR_FORWARD);

再次感谢您的回复，问题已经解决了，问题就出现在没有添加MEGDNN_SPECIALIZE_CREATE_OPERATOR. ^_^
