### ISSUE TITLE
cmake 版本问题

### ISSUE THREAD

**Issue by zjd1988** [MegEngine/MegEngine#57]
## 请简要描述您的需求
在参考https://github.com/MegEngine/MegEngine/blob/master/README_CN.md 进行源码编译时，
执行以下脚本时，会出错（使用cmake3.13.5版本）
cmake .. -DMGE_WITH_CUDA=OFF -DMGE_WITH_TEST=ON

-- Building MegBrain 8.4.1
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXX_SUPPORT_WCLASS_MEMACCESS
-- Performing Test CXX_SUPPORT_WCLASS_MEMACCESS - Failed
-- Performing Test CXX_SUPPORT_GOLD
-- Performing Test CXX_SUPPORT_GOLD - Success
-- Using GNU gold linker.
-- Disable JIT support, as CUDA is not enabled.
-- Disable TensorRT support, as CUDA is not enabled.
-- Found PythonInterp: /home/xj-zjd/anaconda3/bin/python3 (found suitable version "3.7.3", minimum required is "3") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Found PythonInterp: /home/xj-zjd/anaconda3/bin/python3 (found version "3.7.3") 
-- Disable distributed support, as CUDA is not enabled.
-- Looking for strtof_l
-- Looking for strtof_l - found
-- Looking for strtoull_l
-- Looking for strtoull_l - found
-- Build with MKL in /home/xj-zjd/work_space/self_work/megengine_code/MegEngine/third_party/mkl/x86_64
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- GPU support is disabled
-- Intel(R) MKL: include /home/xj-zjd/work_space/self_work/megengine_code/MegEngine/third_party/mkl/x86_64/include
-- Intel(R) MKL: lib libmkl
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.7.4") 
CMake Error at python_module/CMakeLists.txt:1 (cmake_policy):
  _**Policy "CMP0086" is not known to this version of CMake.**_

-- Found PythonLibs: /home/xj-zjd/anaconda3/lib/libpython3.7m.so (found suitable exact version "3.7.3") 
git found: /usr/bin/git
-- Found NumPy: /home/xj-zjd/anaconda3/lib/python3.7/site-packages/numpy/core/include (found version "1.16.4") 
-- NumPy ver. 1.16.4 found (include: /home/xj-zjd/anaconda3/lib/python3.7/site-packages/numpy/core/include)
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8") 
-- Configuring incomplete, errors occurred!
See also "/home/xj-zjd/work_space/self_work/megengine_code/MegEngine/build/CMakeFiles/CMakeOutput.log".
See also "/home/xj-zjd/work_space/self_work/megengine_code/MegEngine/build/CMakeFiles/CMakeError.log".

google了一下，发现可能是这个原因
![企业微信截图_15946463664540](https://user-images.githubusercontent.com/7134030/87309002-9a981300-c54e-11ea-89df-ad4441aa44fa.png)

这个Policy应该是3.14才能支持

**Comment by ChaiMind** [comment]
cmake 版本可以自行进行安装和升级的，与框架设计无关，建议你升级编译所用的 cmake 版本

**Comment by zjd1988** [comment]
@ChaiMind  嗯，明白，其实我升级过一次了，第一次未升级时，提示需要安装cmake3.13以上版本，升级成3.13.5时则出现的这个问题，建议你们可以修改下cmake脚本，这样就可以一步升级到位了。😂

**Comment by ChaiMind** [comment]
> @ChaiMind 嗯，明白，其实我升级过一次了，第一次未升级时，提示需要安装cmake3.13以上版本，升级成3.13.5时则出现的这个问题，建议你们可以修改下cmake脚本，这样就可以一步升级到位了。😂

cmake 是用来（跨平台）编译的工具，逻辑上是 cmake 根据工程项目中给定的 CMakeLists.txt 文件中的相关参数配置进行编译，而其本身的安装是由用户提前在系统上弄好的。所以也只能在 readme 中提醒用户编译时所需的 cmake 的最低版本，而不能替用户自动地完成安装和升级操作。

**Comment by ChaiMind** [comment]
我的建议是在 [Readme](https://github.com/MegEngine/MegEngine#prerequisites) 中添加对 cmake 最低版本需求的说明：

> But some dependencies should be manually installed:
> 
> CUDA(>=10.1), cuDNN(>=7.6)are required when building MegEngine with CUDA support (default ON)
> TensorRT(>=5.1.5) is required when building with TensorRT support (default ON)
> LLVM/Clang(>=6.0) is required when building with Halide JIT support (default ON)
> Python(>=3.5), Numpy, SWIG(>=3.0) are required to build Python modules. (default ON)
> **Cmake(>=3.15) are required to manage the build process.**

@xxr3376

**Comment by ChaiMind** [comment]
> @ChaiMind 嗯，明白，其实我升级过一次了，第一次未升级时，提示需要安装cmake3.13以上版本，升级成3.13.5时则出现的这个问题，建议你们可以修改下cmake脚本，这样就可以一步升级到位了。😂

方便给出你进行编译的系统版本和环境等参数吗？看看后续的编译流程能不能成功。

**Comment by zjd1988** [comment]
@ChaiMind 不好意思，现在下班了，明天再升级到3.14试试，然后贴下结果。

**Comment by xxr3376** [comment]
@ChaiMind 感觉我们应该把 `require_minimum_version` 改到 `3.14`（并修复一切可能导致的 cmake behavior 改变），这样就免除了一次额外的说明？

**Comment by ChaiMind** [comment]
> @ChaiMind 感觉我们应该把 `require_minimum_version` 改到 `3.14`（并修复一切可能导致的 cmake behavior 改变），这样就免除了一次额外的说明？

赞成，不过由于不确定最终的最低所需版本是否是 3.14 ，可以等 @zjd1988 明天升级后看是否能成功编译（也有可能后面的一些配置需要升级到 3.15 甚至 3.16）

**Comment by xxr3376** [comment]
目前确认一定可以使用的版本有：`3.14.4`、`3.16.3`

**Comment by zjd1988** [comment]
Hi @ChaiMind  @xxr3376  ，刚在本地测试了cmake .. -DMGE_WITH_CUDA=OFF -DMGE_WITH_TEST=ON 命令和编译过程
能够正常编译。（使用cmake 3.14.7）

![企业微信截图_15946899218073](https://user-images.githubusercontent.com/7134030/87369880-255f2900-c5b4-11ea-92bc-91fef15ceef9.png)


还有一个疑问，我在执行
cmake .. -DMGE_INFERENCE_ONLY=ON -DMGE_WITH_TEST=OFF

提示找不到cudnn库
看了下cmake/cudnn.cmake文件


![企业微信截图_15946937234716](https://user-images.githubusercontent.com/7134030/87373866-116bf500-c5bd-11ea-8496-2a51c0b18326.png)

建议可以通过搜索CUDA的路径来定位CUDNN，一般cudnn和cuda都是安装到一起的。
因为按照编译文档，一般不会手动去指定CUDNN_ROOT_DIR，这样的话${CUDNN_ROOT_DIR} 会为空，导致cmake 出问题，然后才会去定位问题

tensorrt.cmake也有一样的问题。

**Comment by xxr3376** [comment]
@zjd1988 目前这个拆分的编写方式是特意这样实现的，目的就是在不安装到一起的时候能指定位置。（因为系统里同时安装了 cudnn 多个版本的时候希望能区分开，而不是安装到一起相互覆盖）

如果你不希望手动指定 `CUDNN_ROOT_DIR`，可以考虑设置 `LD_LIBRARY_PATH`。

**Comment by zjd1988** [comment]
@xxr3376  嗯，明白，谢谢回复。
