### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by stoneMo** [MegEngine/MegEngine#59]
Tensor clamp
## 背景

I am doing a project regarding object detection. So I need to clamp the predicted boxes. Does the tensor in the MegEngine have clamp methods like tensors in the PyTorch framework? Thank you in advance.

**Comment by xxr3376** [comment]
@stoneMo There's `megengine.functional.clamp`.

Sadly our [API reference](https://megengine.org.cn/doc/latest/api_zh/megengine.functional.html?highlight=functional#module-megengine.functional.elemwise) doesn't genreate document about this, let me check it.

**Comment by ChaiMind** [comment]
https://github.com/MegEngine/MegEngine/blob/54888f9adf814c6c1ac006e865aa4599caacb642/python_module/megengine/functional/elemwise.py#L17

`"clamp"` should be added in list `__all__` showed above.

**Comment by stoneMo** [comment]
Thanks for your response. I found it in the file mentioned above.
