### ISSUE TITLE
benchmark_basic_types 测试用例代码问题

### ISSUE THREAD

**Issue by zjd1988** [MegEngine/MegEngine#61]
## 请简要描述您的需求
最近打算好好看看Megengine代码，先看的dnn模块，打算从测试用例入手，在看benchmark_basic_types.cpp文件发现有些问题

![企业微信截图_15950673418073](https://user-images.githubusercontent.com/7134030/87850427-c2a6be00-c922-11ea-8344-751254ead0e2.png)
TensorShape 的最大维度为7
但是switch只写了6个，还有就是在单步调试时发现
TEST(BENCHMARK_BASIC_TYPES, EQ_SHAPE)函数中
static TensorShape s0, s1[NR_TEST];
s0的ndim总是为0，这样是不是测试benchmark有点问题.

同理，eq_layout1也有一样的问题.

**Comment by sethbrin** [comment]
感谢指出，这里确实存在两个问题：
1. switch 只写了6，原因是之前MAX_NDIM 从6升到7的时候未修改对应的testcase
2. s0 未初始化，这里主要测试目的是对比eq_layout 和 eq_layout1的性能，s0 应该给定一个固定的shape或者一个随机的shape。

我们后续会修复该问题，也欢迎您参与到我们的开发中来，一起改进 MegEngine ：）

**Comment by zjd1988** [comment]
@sethbrin  谢谢回复，会持续关注和学习MegEngine。

**Comment by ChaiMind** [comment]
Fixed in commit https://github.com/MegEngine/MegEngine/commit/8b183f2c704ba80d72a0ea5dca21eef025cc5311 👍👍👍
