### ISSUE TITLE
Is there any method like torch.diag that can return the diagonal of a given tensor? Thanks in advance. 

### ISSUE THREAD

**Issue by stoneMo** [MegEngine/MegEngine#63]

**Comment by lqy-megvii** [comment]
Hi, you can use `megengine.functional.nn.eye` together with element-wise operations to get the diagonal of a given tensor.

https://github.com/MegEngine/MegEngine/blob/master/python_module/megengine/functional/nn.py#L709

**Comment by stoneMo** [comment]
Thanks for your response.

**Comment by hiyyg** [comment]
@lqy-megvii Hi, how to achieve this specifically? The link is 404.

**Comment by hiyyg** [comment]
OK, use `F.cond_take(F.eye(X.shape[0]).astype("bool"), X)`. It would be nicer if there is a diag function.

**Comment by MegChai** [comment]
> OK, use `F.cond_take(F.eye(X.shape[0]).astype("bool"), X)`. It would be nicer if there is a diag function.

Hey, @hiyyg ~ Could you please open a new issue to let me know there are more requests on the `diag` function?

> https://github.com/MegEngine/MegEngine/blob/master/python_module/megengine/functional/nn.py#L709

This file was moved to https://github.com/MegEngine/MegEngine/blob/master/imperative/python/megengine/functional/nn.py

But the best way to find API support is by [reading our official doc](https://megengine.org.cn/doc/stable/zh/reference/functional.html) or the latest source code.

**Comment by hiyyg** [comment]
Sure
