### ISSUE TITLE
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::MegDNNError cuda error invalid device function(98) occurred;

### ISSUE THREAD

**Issue by stoneMo** [MegEngine/MegEngine#64]
## 环境
1.系统环境：Redhat Linux Enterprise 
2.MegEngine版本：0.5.1
3.python版本：3.6.10

## 复现步骤
1. 
2.
3.

## 请提供完整的日志及报错信息
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::MegDNNError
cuda error invalid device function(98) occurred; expr: cudaOccupancyMaxPotentialBlockSizeVariableSMem( &ret.grid_size, &ret.block_size, kern, s)
+ bt:/mnt/xfs1/home/intern6/anaconda3/envs/CRDET/lib/python3.6/site-packages/megengine/_internal/_mgb.cpython-36m-x86_64-linux-gnu.so{1e55711,21124c4,21124f2,2b284d5}
| Associated operator: id=7 name=asFloat32(1[5])[7] type=mgb::opr::TypeCvt
|   input variables: 
|     0: {id:6, layout:{1(1)}, Int32, owner:1[5]{ImmutableTensor}, name:1[5], slot:0, gpu0:0, s, 2, 2}
|   output variables: 
|     0: {id:8, layout:{1(1)}, Float32, owner:asFloat32(1[5])[7]{TypeCvt}, name:asFloat32(1[5])[7], slot:0, gpu0:0, d, 2, 2}

**Comment by qq332982511** [comment]
能提供一下gpu型号吗（给个nvidia-smi）

**Comment by stoneMo** [comment]
Tesla K-80

**Comment by qq332982511** [comment]
卡的版本太老，没编译对应的二进制。

**Comment by niuhope** [comment]
默认的CMake如果CUDA版本为9.0以上是不编译sm35，所以应该是没有编译对应sm的CUDA code。可以看看https://github.com/MegEngine/MegEngine/blob/master/CMakeLists.txt#L287，对应你的CUDA版本下面加上set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_35,code=sm_35")，或者换列表里对应的卡

**Comment by stoneMo** [comment]
好的，我装的是cuda10.1， 对应的版本下面没有set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_35,code=sm_35")嘛

**Comment by stoneMo** [comment]
所以不是必须要求是cuda10.1嘛？

**Comment by ChaiMind** [comment]
> 好的，我装的是cuda10.1， 对应的版本下面没有set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_35,code=sm_35")嘛

可以按照 @niuhope 说的自行修改添加对 sm_35 的支持，人为加上这一行后重新编译。

```
if(${CMAKE_CUDA_COMPILER_VERSION} VERSION_GREATER "10.0.0" OR ${CMAKE_CUDA_COMPILER_VERSION} VERSION_EQUAL "10.0.0")
                set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_35,code=sm_35")
                set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_52,code=sm_52")
                set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_60,code=sm_60")
                set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_61,code=sm_61")
                set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_70,code=sm_70")
                set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_75,code=sm_75")
                set(MGE_CUDA_GENCODE "${MGE_CUDA_GENCODE} -gencode arch=compute_75,code=compute_75")
```

**Comment by qq332982511** [comment]
https://www.techpowerup.com/gpu-specs/
可以在这个网站查询显卡支持的arch

**Comment by ChaiMind** [comment]
@qq332982511 你指的是否是如图所示的信息：

![image](https://user-images.githubusercontent.com/21091736/88366998-3fbbb280-cdbd-11ea-97e4-d905fc47d780.png)

*Note that `compute_XX` refers to a PTX version and `sm_XX` refers to a cubin version.*

因此图中的 CUDA 3.7 对应 3.5 cubin，另外很好奇该如何根据以下信息分析定位到对应原因的：

```
cuda error invalid device function(98) occurred; 
```

通常我会根据经验认为是 CUDA 运行时和对应的 NVCC 版本不匹配，但该问题将导致另外情况的报错。

Refs:
- CUDA Runtime API - [cudaOccupancyMaxPotentialBlockSizeVariableSMem](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__HIGHLEVEL.html#group__CUDART__HIGHLEVEL_1g77b3bfb154b86e215a5bc01509ce8ea6)
- [Pascal Compatibility Guide for CUDA Applications](https://docs.nvidia.com/cuda/pascal-compatibility-guide/index.html) （我通过该网页补充了相关概念）

**Comment by qq332982511** [comment]
cudaOccupancyMaxPotentialBlockSizeVariableSMem的参数func需要提供设备函数，报错是cuda error invalid device function，根据@niuhope 的多年踩坑经验，应该是对应设备的device函数不存在

**Comment by ChaiMind** [comment]
> cudaOccupancyMaxPotentialBlockSizeVariableSMem的参数func需要提供设备函数，报错是cuda error invalid device function，根据@niuhope 的多年踩坑经验，应该是对应设备的device函数不存在

十分感谢！ 😄 后来在 StackOverflow 找到了类似的解释：[CUDA - invalid device function, how to know \[architecture, code\]?
](https://stackoverflow.com/questions/28451859/cuda-invalid-device-function-how-to-know-architecture-code)

之前误认为这个问题是特定于 cudaOccupancyMaxPotentialBlockSizeVariableSMem 函数产生，看来还是较为常见。
