### ISSUE TITLE
error: invalid use of ‘auto’ const std::string& pre) -> auto { ^ .... during the process of "make -j4"

### ISSUE THREAD

**Issue by stoneMo** [MegEngine/MegEngine#66]
## 环境
1.系统环境：Red hat Linux Enterprise 
2.MegEngine版本：
3.python版本：

## 复现步骤
1.
2.
3.

## 请提供完整的日志及报错信息
(base) [intern6@node011 build]$ make -j4
-- Building MegBrain 8.6.0
-- Using GNU gold linker.
-- Found PythonInterp: /mnt/xfs1/home/intern6/anaconda3/envs/CRDET/bin/python3 (found suitable version "3.6.10", minimum required is "3") 
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Found PythonInterp: /mnt/xfs1/home/intern6/anaconda3/envs/CRDET/bin/python3 (found version "3.6.10") 
-- Found CuDNN: /cm/shared/apps/cudnn/7.4.2 (found version: 7.4)
-- Found TensorRT: /mnt/xfs1/home/intern6/software/TensorRT-5.1.5.0 (found version: 5.1.5)
-- Build with MKL in /mnt/xfs1/home/intern6/software/MegEngine/third_party/mkl/x86_64
-- GPU support is disabled
-- Intel(R) MKL: include /mnt/xfs1/home/intern6/software/MegEngine/third_party/mkl/x86_64/include
-- Intel(R) MKL: lib libmkl
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
git found: /mnt/xfs1/home/intern6/git/libexec/git-core/git
-- NumPy ver. 1.18.5 found (include: /mnt/xfs1/home/intern6/anaconda3/envs/CRDET/lib/python3.6/site-packages/numpy/core/include)
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/xfs1/home/intern6/software/MegEngine/build
[  2%] Built target halide
[  2%] Built target zmq
[  2%] Built target protobuf
[  3%] Built target flatc
[  3%] Built target flatbuffers
[  3%] Built target flathash
[  3%] Built target cuda-stub
[  3%] Built target lapack_static_weak_target
[  3%] Built target _opr_param_defs
[  4%] Built target gtest
[  4%] Built target ucx
[  4%] Built target dnnl_common
[  4%] Built target nccl
[  4%] Built target mgb_proto_target
[  4%] Built target _mgb_opr_param_defs
[  6%] Built target mgb_serialization_schema_fbs
[  6%] Built target mgb_opr_py
[  9%] Built target mgb_swig_compilation
[ 12%] Built target dnnl_cpu
[ 12%] Built target version_ld
[ 12%] Built target dnnl
[ 13%] Built target megray
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/add_update.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/argmxx/base_impl.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/basic_types.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/argsort.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/batch_conv_bias.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/batch_normalization.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/batched_matrix_mul.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/checksum.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/concat_split.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/cond_take/opr_impl.cpp.o
[ 13%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/conv_bias.cpp.o
[ 14%] Building CXX object dnn/src/CMakeFiles/megdnn.dir/common/conv_pooling.cpp.o
/mnt/xfs1/home/intern6/software/MegEngine/dnn/src/common/conv_bias.cpp: In static member function ‘static megdnn::ConvBiasForward::WinogradParam megdnn::ConvBiasForward::parse_winograd_name(const string&)’:
/mnt/xfs1/home/intern6/software/MegEngine/dnn/src/common/conv_bias.cpp:337:49: error: invalid use of ‘auto’
                      const std::string& pre) -> auto {
                                                 ^
make[2]: *** [dnn/src/CMakeFiles/megdnn.dir/common/conv_bias.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [dnn/src/CMakeFiles/megdnn.dir/all] Error 2
make: *** [all] Error 2

**Comment by lqy-megvii** [comment]
Which gcc version are you using?

**Comment by haolongzhangm** [comment]
pls refs scripts/cmake-build/BUILD_README.md  to install build env or consider upgrade u gcc
