### ISSUE TITLE
BUG Issue

### ISSUE THREAD

**Issue by megvii-mge** [MegEngine/MegEngine#68]
## 环境
1.系统环境及版本：（例 Ubuntu 18.04）
2.MegEngine版本：（若您是自行编译，请提供 fork 时对应 commit id 、编辑器及版本）
3.python版本：
4.CPU/GPU ：（若您使用GPU进行训练，请提供您的CUDA和cuDNN版本号）
5.Git 版本:
6.GCC版本：

## 复现步骤
1.
2.
3.

**Comment by ChaiMind** [comment]
Update file `MegEngine/.github/ISSUE_TEMPLATE/bug-issue.md` [Here](https://github.com/MegEngine/MegEngine/blob/master/.github/ISSUE_TEMPLATE/bug-issue.md)
