### ISSUE TITLE
Feature Request 是否有windows构建的计划？

### ISSUE THREAD

**Issue by One-sixth** [MegEngine/MegEngine#70]
是否有windows本地构建的计划？而不是在WSL里面运行

**Comment by xxr3376** [comment]
正在进行中，但是考虑到 WSL2 已经开始支持了 CUDA，因此 Windows 版本预计不会做深度优化。

**Comment by haolongzhangm** [comment]
@One-sixth  如果是部署需求的话， 目前版本已经是OK的， 详细见

scripts/cmake-build/host_build.sh
scripts/cmake-build/BUILD_README.md

如果是python 侧使用需求的话，如上面描述，正在进行中...

**Comment by One-sixth** [comment]
谢谢答复，了解了，我主要是windows python侧使用的，希望用于windows的包能早日释出。

**Comment by ChaiMind** [comment]
现在可以查阅微软的官方文档，尝试在 WSL2 中启用 CUDA：

- [Enable NVIDIA CUDA in WSL 2](https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-cuda-in-wsl)

**Comment by xxr3376** [comment]
@One-sixth 多亏了 @haolongzhangm 的辛苦工作，已经完成第一个版本的打包工作，你可以通过 `pip3 install megengine==1.0.0rc1 -f https://megengine.org.cn/whl/mge.html` 来体验 Windows / Mac / Linux 版本
