### ISSUE TITLE
BUG Issue

### ISSUE THREAD

**Issue by lizhixi212** [MegEngine/MegEngine#82]
## 环境
项目框架:MegEngine 0.4.0
项目环境:Python 3.7

### 代码如下
```
from megengine import hub
model = hub.load('megengine/models', 'resnet18', pretrained=True)
model.eval()
 
import cv2
import numpy as np
import megengine.data.transform as T
import megengine.functional as F

image = cv2.imread("cat.jpg")
transform = T.Compose([
    T.Resize(256),
    T.CenterCrop(224),
    T.Normalize(mean=[103.530, 116.280, 123.675], std=[57.375, 57.120, 58.395]),
    T.ToMode("CHW")
])
processed_img = transform.apply(image)[np.newaxis, :] # CHW -> 1CHW？
logits = model(processed_img)
probs = F.softmax(logits)
print(probs)
```
## 日志及报错信息
```
14 15:27:38[mgb] ERR megbrain is about to die abruptly; you can set MGB_WAIT_TERMINATE and rerun to wait for gdb attach: caught deadly signal 11(Segmentation fault)
14 15:27:38[mgb] ERR bt:/lib/x86_64-linux-gnu/libpthread-2.27.so{12890}/home/megstudio/miniconda3/envs/xuan/lib/python3.8/site-packages/megengine/_internal/_mgb.cpython-38-x86_64-linux-gnu.so{5e0f613}
```

**Comment by Yongchang-Li** [comment]
这因该时MegStudio的错误吧？

**Comment by Yongchang-Li** [comment]
![image](https://user-images.githubusercontent.com/53890383/90267127-b4977f00-de87-11ea-8e99-f9e028618d98.png)
![image](https://user-images.githubusercontent.com/53890383/90267325-f45e6680-de87-11ea-8094-91341081e21b.png)
### 这是根本就没有运行啊！！！

**Comment by Yongchang-Li** [comment]
![image](https://user-images.githubusercontent.com/53890383/90268578-cc700280-de89-11ea-84ce-04fce8f47e4d.png)
使用GPU后，就可以正确运行了，但是这个代码，并没有对CPU,CPU有特别的说明，我怎么知道用那种？

**Comment by Yongchang-Li** [comment]
![image](https://user-images.githubusercontent.com/53890383/90269940-0510db80-de8c-11ea-8547-6cf4943aaa26.png)
似乎时有这个cuda提示，就要使用GPU?

**Comment by ChaiMind** [comment]
MegEngine 会自动地检测当前环境是否有 GPU 硬件以及配置好了相应的驱动，没有的话会采用 CPU 模式。

我们会在后续的版本迭代中改进更加友好的报错提示，谢谢你的相关建议。

ResNet 可以算是结构比较大的网络模型了，因此对深度学习有一定基础了解的用户应该知道训练该模型需要用到 GPU，单纯靠 CPU 进行训练会耗费大量的时间（或者说根本不现实）。实际上对于各类深度学习框架， CPU 环境下只适合用来了解 API 或是训练小型的 Demo 数据以及网络模型。如果你是参加了最近零基础入门课程的用户，可以注意到（[视频](https://www.bilibili.com/video/BV1oi4y1u73B) 37 分钟处开始）老师在讲解 ResNet 网络模型时并没有在 CPU 版本的 notebook 中执行模型的训练过程，而是切换到了一个带有 GPU 环境的 notebook，并对 ResNet 的训练需求进行了相应的说明。

如果你还未加入零基础入门旷视天元 MegEngine 课程，欢迎中途加入学习（微信群或者 QQ 号均可获取直播通知）。

此类问题在无法确认是 BUG 的情况下，建议先在 QQ 交流群（1029741705）中进行讨论，确定最终的问题类型后再以 Issue  形式进行反馈，因为上面的信息流过于零散且造成了误导，对于其它点进此 Issue 的用户并没有帮助。同时由于你的标题不符合实际情况，该 Issue 将被关闭，还请理解。共建和谐开源社区，需要你我共同努力~
