### ISSUE TITLE
加载模型，数据集网速都巨慢？

### ISSUE THREAD

**Issue by lizhixi212** [MegEngine/MegEngine#83]
![image](https://user-images.githubusercontent.com/53890383/90268080-068cd480-de89-11ea-81d4-73f681a4c315.png)
我吐了，为什么MegStudio中加载模型，数据集都巨慢？
向2G致敬？？？

**Comment by ChaiMind** [comment]
`hub.load` 需要从另外的 [Models](https://github.com/MegEngine/Models) / [Hub](https://github.com/MegEngine/Hub) 仓库加载，与所在配置环境的网络状况有关。需要使用 Hub 里面的 Model 的话，建议在自己的机器上安装 MegEngine. 另外如果需要复现 ResNet，建议使用带有 GPU 设备的环境。

**Comment by ChaiMind** [comment]
由于该问题本身实质与 MegEngine 无关，该 Issue 将被关闭。
