### ISSUE TITLE
3Dconv

### ISSUE THREAD

**Issue by heiheihei-ops** [MegEngine/MegEngine#86]
请问一下，megengine是没有实现3D卷积的接口吗，我似乎没有在文档中找到。

**Comment by ChaiMind** [comment]
是的，目前还没有提供 conv3d 接口

**Comment by heiheihei-ops** [comment]
请问有其他的实现方式吗

**Comment by ChaiMind** [comment]
> 请问有其他的实现方式吗

预计 9 月份会发布 1.0 版本，后续会丰富更多的 API 接口，con3d 应该会较早提供。

**Comment by heiheihei-ops** [comment]
好的谢谢
