### ISSUE TITLE
将 megengine.functional 中的 matrix_mul 改名为 matmul

### ISSUE THREAD

**Issue by Leymore** [MegEngine/MegEngine#88]
将 megengine.functional 中的 matrix_mul 改名为 matmul

## 背景
在许多常用库中，使用 matmul 来命名 "矩阵乘" 的操作，例如：
numpy https://numpy.org/doc/stable/reference/generated/numpy.matmul.html
pytorch https://pytorch.org/docs/stable/generated/torch.matmul.html
tensorflow https://www.tensorflow.org/api_docs/python/tf/linalg/matmul
而在 megengine 中，该操作的名字是 matrix_mul。
https://github.com/MegEngine/MegEngine/blob/aa147b7426036a485f59d60f608d5ced49230421/python_module/megengine/functional/nn.py#L757
我认为这是不符合直觉的。

## 需求描述
将 megengine.functional 中的 matrix_mul 改名为 matmul。
另外，文档例子中这两行似乎是多余的 :)
https://github.com/MegEngine/MegEngine/blob/aa147b7426036a485f59d60f608d5ced49230421/python_module/megengine/functional/nn.py#L773-L774

**Comment by ChaiMind** [comment]
已经收到你的建议了，需要内部做进一步的讨论。

**Comment by ChaiMind** [comment]
> 另外，文档例子中这两行似乎是多余的 :)

这里的作用是让示例代码看起来表意更直接，并不是从代码有效性层面考虑的。 :)

**Comment by xxr3376** [comment]
fixed in 6b380e896580919cada2846b80a82c7ff6448083
