### ISSUE TITLE
发布会的视频还有录播吗？

### ISSUE THREAD

**Issue by newdimitri** [MegEngine/MegEngine#9]
## 请简要描述您的需求
作为中小企业的CTO，一直关注旷视的深度学习平台，但我错过了发布会的直播，想问之后提供录播吗？

**Comment by mp817** [comment]
有录播回放，因为刚刚结束发布会，现在正在视频后期制作中，敬请期待！

**Comment by newdimitri** [comment]
秒回啊，是冠哥在搭理GitHub吗

**Comment by megvii-mge** [comment]
您好，旷视天元发布会视频录播已发布，请您前往 https://events.megengine.org.cn/，感谢您对 MegEngine 项目的关注！

**Comment by newdimitri** [comment]
收到，谢谢。
