### ISSUE TITLE
关于local_conv2d

### ISSUE THREAD

**Issue by Feynman1999** [MegEngine/MegEngine#92]
## 环境
1.系统环境：ubantu18.04
2.MegEngine版本： 0.6
3.python版本：3.7

## 复现步骤
![](https://s1.ax1x.com/2020/08/29/dHISmQ.png)

请问我有这样一段代码  当H调大时(H=64)就会报错是什么原因呢

## 请提供完整的日志及报错信息
![](https://s1.ax1x.com/2020/08/30/dHIyjS.png)

**Comment by xiaocenxiaocen** [comment]
这个算子底下有两个算法能算，如果batch size是32的倍数的话，会用cuda-convnet2里的实现，不然的话会用一个fallback的实现，fallback的实现有限制，shared memory不能用太大。
我觉得可以把batch size调成32的倍数，这样支持的情况比较多，而且速度会比较快。

**Comment by MegChai** [comment]
local_conv 的实现中 kernel 的参数数量会和 input 的宽高有关系（针对每个单独的像素点都会单独地生成一个 filter），当这两个数值过大时，会导致计算出所需的 kernel 参数量过大，但在底层限制住了所能够生成的 kernel 的参数数量，在平时使用的时候模型结构里也不会把这个 local_conv 作用在输入的 H W 很大的时候。
