### ISSUE TITLE
编译 https://github.com/MegEngine/Inference-Demo/tree/master/native/shufflenet_interface，没有结果

### ISSUE THREAD

**Issue by aspnetcs** [MegEngine/MegEngine#95]
## 请简要描述您的需求
编译 https://github.com/MegEngine/Inference-Demo/tree/master/native/shufflenet_interface，没有结果
![shufflenet](https://user-images.githubusercontent.com/14257859/91777895-aa190b80-ec23-11ea-8293-7b8461afa48c.jpg)
没有编译出结果，zahu咋回事？

**Comment by CaramelFc** [comment]
`./build_inference.sh`需要跟参数
```shell
    1-> build sdk
    2-> install test only
    4-> run test
    8-> delete sdk
    16-> install all
```

**Comment by ChaiMind** [comment]
如果不知道 bash 脚本如何使用，最简单的方式是阅读它的源码：

https://github.com/MegEngine/Inference-Demo/blob/master/native/shufflenet_interface/build_inference.sh

$BUILD_CMD 接受的几个参数分别是 1 2 4 8 16

你在 #99 中的使用方式不正确，另外请不要另外开新的 issue 讨论同一个问题。

**Comment by aspnetcs** [comment]
好的，
能够在windows下面，编译https://github.com/MegEngine/Inference-Demo/tree/master/native/shufflenet_interface吗？

**Comment by ChaiMind** [comment]
- app 示例基于 Gradle 构建系统，如需要构建 apk，在 camera_app/Camera2Basic/ 中使用"gradlew build", 或者使用Android Studio的"Import Project"功能
- app 所依赖的 native 动态库，由 cmake 构建，可以通过 native/shufflenet_interface/ 中 build_inference.sh完成编译

在项目的文档中均有说明。

如果你没有任何相关开发经验，建议参考文档和视频教程：

- [Android Camera Inference Demo](https://github.com/MegEngine/Inference-Demo)
- [【机器之心X旷视 】旷视天元MegEngine推理端部署](https://www.bilibili.com/video/BV1ek4y127sP)
- [【机器之心X旷视 】旷视天元MegEngine部署进阶：推理端优化](https://www.bilibili.com/video/BV1uy4y1y7S6)

如果你不阅读文档和教程，也不看视频操作流程，恐怕很难提供更多的帮助。
