### ISSUE TITLE
显存暴增导致oom

### ISSUE THREAD

**Issue by zdyshine** [MegEngine/MegEngine#98]
## 背景

![image](https://user-images.githubusercontent.com/35593072/91875264-d9745a80-ecad-11ea-9754-0db24da3d31e.png)
请问这是啥情况啊，现在只能用很小的网络进行推理训练，这不科学啊。。。

**Comment by zdyshine** [comment]
一开始训练加载网络的时候，显存会暴增，然后很快显存使用就降下来。训练到推理的时候，显存又突然暴增，之后很快就可以降下来，这个是啥情况啊。。。

**Comment by ChaiMind** [comment]
请参考已存在的 Issues 如 #5 #85 #93 看是否能解答你的疑惑

**Comment by MegChai** [comment]
在最新的 v1.0.0 正式版中使用了全新的动态图机制，不会出现显存暴增的情况啦，欢迎体验~~
