### ISSUE TITLE
编译 https://github.com/MegEngine/Inference-Demo/tree/master/native/shufflenet_interface，出错了

### ISSUE THREAD

**Issue by aspnetcs** [MegEngine/MegEngine#99]
![捕获](https://user-images.githubusercontent.com/14257859/92000851-94fdc300-ed70-11ea-9fa0-f25a6e930fe9.PNG)
## 请简要描述您的需求
编译 https://github.com/MegEngine/Inference-Demo/tree/master/native/shufflenet_interface，出错了

**Comment by ChaiMind** [comment]
#95 请不要重复发布问题相似的 issue
